/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints;

import jolt.math.TwoBodyConstraintSettings;
import jolt.enums.EConstraintSpace;
import jolt.math.Vec3;

public final class HingeConstraintSettings extends TwoBodyConstraintSettings {

    static public final HingeConstraintSettings NULL = HingeConstraintSettings.native_new();

    public HingeConstraintSettings() {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected HingeConstraintSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static HingeConstraintSettings native_new() {
        return new HingeConstraintSettings((byte) 0, (char) 0);
    }

    public EConstraintSpace get_mSpace() {
        return null;
    }

    public void set_mSpace(EConstraintSpace mSpace) {
    }

    public Vec3 get_mPoint1() {
        return null;
    }

    public void set_mPoint1(Vec3 mPoint1) {
    }

    public Vec3 get_mHingeAxis1() {
        return null;
    }

    public void set_mHingeAxis1(Vec3 mHingeAxis1) {
    }

    public Vec3 get_mNormalAxis1() {
        return null;
    }

    public void set_mNormalAxis1(Vec3 mNormalAxis1) {
    }

    public Vec3 get_mPoint2() {
        return null;
    }

    public void set_mPoint2(Vec3 mPoint2) {
    }

    public Vec3 get_mHingeAxis2() {
        return null;
    }

    public void set_mHingeAxis2(Vec3 mHingeAxis2) {
    }

    public Vec3 get_mNormalAxis2() {
        return null;
    }

    public void set_mNormalAxis2(Vec3 mNormalAxis2) {
    }

    public float get_mLimitsMin() {
        return 0;
    }

    public void set_mLimitsMin(float mLimitsMin) {
    }

    public float get_mLimitsMax() {
        return 0;
    }

    public void set_mLimitsMax(float mLimitsMax) {
    }

    public SpringSettings get_mLimitsSpringSettings() {
        return null;
    }

    public void set_mLimitsSpringSettings(SpringSettings mLimitsSpringSettings) {
    }

    public float get_mMaxFrictionTorque() {
        return 0;
    }

    public void set_mMaxFrictionTorque(float mMaxFrictionTorque) {
    }

    public MotorSettings get_mMotorSettings() {
        return null;
    }

    public void set_mMotorSettings(MotorSettings mMotorSettings) {
    }
}
