/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints;

import jolt.math.TwoBodyConstraintSettings;
import jolt.math.Vec3;
import jolt.math.Quat;
import jolt.enums.EPathRotationConstraintType;

public final class PathConstraintSettings extends TwoBodyConstraintSettings {

    static public final PathConstraintSettings NULL = PathConstraintSettings.native_new();

    public PathConstraintSettings() {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected PathConstraintSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static PathConstraintSettings native_new() {
        return new PathConstraintSettings((byte) 0, (char) 0);
    }

    public PathConstraintPath get_mPath() {
        return null;
    }

    public void set_mPath(PathConstraintPath mPath) {
    }

    public Vec3 get_mPathPosition() {
        return null;
    }

    public void set_mPathPosition(Vec3 mPathPosition) {
    }

    public Quat get_mPathRotation() {
        return null;
    }

    public void set_mPathRotation(Quat mPathRotation) {
    }

    public float get_mPathFraction() {
        return 0;
    }

    public void set_mPathFraction(float mPathFraction) {
    }

    public float get_mMaxFrictionForce() {
        return 0;
    }

    public void set_mMaxFrictionForce(float mMaxFrictionForce) {
    }

    public EPathRotationConstraintType get_mRotationConstraintType() {
        return null;
    }

    public void set_mRotationConstraintType(EPathRotationConstraintType mRotationConstraintType) {
    }

    public MotorSettings get_mPositionMotorSettings() {
        return null;
    }

    public void set_mPositionMotorSettings(MotorSettings mPositionMotorSettings) {
    }
}
