/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints;

import jolt.math.TwoBodyConstraintSettings;
import jolt.enums.EConstraintSpace;
import jolt.math.Vec3;

public final class RackAndPinionConstraintSettings extends TwoBodyConstraintSettings {

    static public final RackAndPinionConstraintSettings NULL = RackAndPinionConstraintSettings.native_new();

    public RackAndPinionConstraintSettings() {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected RackAndPinionConstraintSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static RackAndPinionConstraintSettings native_new() {
        return new RackAndPinionConstraintSettings((byte) 0, (char) 0);
    }

    public void SetRatio(int inNumTeethRack, float inRackLength, int inNumTeethPinion) {
    }

    public EConstraintSpace get_mSpace() {
        return null;
    }

    public void set_mSpace(EConstraintSpace mSpace) {
    }

    public Vec3 get_mHingeAxis() {
        return null;
    }

    public void set_mHingeAxis(Vec3 mHingeAxis) {
    }

    public Vec3 get_mSliderAxis() {
        return null;
    }

    public void set_mSliderAxis(Vec3 mSliderAxis) {
    }

    public float get_mRatio() {
        return 0;
    }

    public void set_mRatio(float mRatio) {
    }
}
