/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.character;

public final class CharacterVsCharacterCollisionSimple extends CharacterVsCharacterCollision {

    static public final CharacterVsCharacterCollisionSimple NULL = CharacterVsCharacterCollisionSimple.native_new();

    public CharacterVsCharacterCollisionSimple() {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CharacterVsCharacterCollisionSimple(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static CharacterVsCharacterCollisionSimple native_new() {
        return new CharacterVsCharacterCollisionSimple((byte) 0, (char) 0);
    }

    public void Add(CharacterVirtual inCharacter) {
    }

    public void Remove(CharacterVirtual inCharacter) {
    }
}
