/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.character;

import com.github.xpenatan.jParser.api.NativeObject;

public final class CharacterID extends NativeObject {

    static public final CharacterID NULL = CharacterID.native_new();

    public CharacterID() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CharacterID(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static CharacterID native_new() {
        return new CharacterID((byte) 0, (char) 0);
    }

    public int GetValue() {
        return 0;
    }

    public boolean IsInvalid() {
        return false;
    }

    public static CharacterID sNextCharacterID() {
        return null;
    }

    public static void sSetNextCharacterID(int inNextValue) {
    }
}
