/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.character;

import jolt.math.Vec3;
import jolt.math.Quat;
import jolt.physics.PhysicsSystem;
import jolt.math.Mat44;
import jolt.physics.body.BodyID;
import jolt.physics.collision.broadphase.BroadPhaseLayerFilter;
import jolt.physics.collision.ObjectLayerFilter;
import jolt.physics.body.BodyFilter;
import jolt.physics.collision.ShapeFilter;
import jolt.core.TempAllocator;
import jolt.physics.collision.shape.Shape;
import jolt.physics.collision.TransformedShape;
import com.github.xpenatan.jParser.api.NativeObject;
import jolt.Jolt;

public final class CharacterVirtual extends CharacterBase {

    static public final CharacterVirtual NULL = CharacterVirtual.native_new();

    public CharacterVirtual(CharacterVirtualSettings inSettings, Vec3 inPosition, Quat inRotation, PhysicsSystem inSystem) {
        super((byte) 1, (char) 1);
    }

    public CharacterVirtual(CharacterVirtualSettings inSettings, Vec3 inPosition, Quat inRotation, long inUserData, PhysicsSystem inSystem) {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CharacterVirtual(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static CharacterVirtual native_new() {
        return new CharacterVirtual((byte) 0, (char) 0);
    }

    public CharacterID GetID() {
        return null;
    }

    public void SetListener(CharacterContactListener inListener) {
    }

    public void SetCharacterVsCharacterCollision(CharacterVsCharacterCollision inCharacterVsCharacterCollision) {
    }

    public NativeObject GetListenerNative() {
        return null;
    }

    public Vec3 GetLinearVelocity() {
        return null;
    }

    public void SetLinearVelocity(Vec3 inLinearVelocity) {
    }

    public Vec3 GetPosition() {
        return null;
    }

    public void SetPosition(Vec3 inPosition) {
    }

    public Quat GetRotation() {
        return null;
    }

    public void SetRotation(Quat inRotation) {
    }

    public Vec3 GetCenterOfMassPosition() {
        return null;
    }

    public Mat44 GetWorldTransform() {
        return null;
    }

    public Mat44 GetCenterOfMassTransform() {
        return null;
    }

    public float GetMass() {
        return 0;
    }

    public void SetMass(float inMass) {
    }

    public float GetMaxStrength() {
        return 0;
    }

    public void SetMaxStrength(float inMaxStrength) {
    }

    public float GetPenetrationRecoverySpeed() {
        return 0;
    }

    public void SetPenetrationRecoverySpeed(float inSpeed) {
    }

    public float GetCharacterPadding() {
        return 0;
    }

    public int GetMaxNumHits() {
        return 0;
    }

    public void SetMaxNumHits(int inMaxHits) {
    }

    public float GetHitReductionCosMaxAngle() {
        return 0;
    }

    public void SetHitReductionCosMaxAngle(float inCosMaxAngle) {
    }

    public boolean GetMaxHitsExceeded() {
        return false;
    }

    public Vec3 GetShapeOffset() {
        return null;
    }

    public void SetShapeOffset(Vec3 inShapeOffset) {
    }

    public long GetUserData() {
        return 0;
    }

    public void SetUserData(long inUserData) {
    }

    public BodyID GetInnerBodyID() {
        return null;
    }

    public void StartTrackingContactChanges() {
    }

    public void FinishTrackingContactChanges() {
    }

    public Vec3 CancelVelocityTowardsSteepSlopes(Vec3 inDesiredVelocity) {
        return null;
    }

    public void Update(float inDeltaTime, Vec3 inGravity, BroadPhaseLayerFilter inBroadPhaseLayerFilter, ObjectLayerFilter inObjectLayerFilter, BodyFilter inBodyFilter, ShapeFilter inShapeFilter, TempAllocator inAllocator) {
    }

    public boolean CanWalkStairs(Vec3 inLinearVelocity) {
        return false;
    }

    public boolean WalkStairs(float inDeltaTime, Vec3 inStepUp, Vec3 inStepForward, Vec3 inStepForwardTest, Vec3 inStepDownExtra, BroadPhaseLayerFilter inBroadPhaseLayerFilter, ObjectLayerFilter inObjectLayerFilter, BodyFilter inBodyFilter, ShapeFilter inShapeFilter, TempAllocator inAllocator) {
        return false;
    }

    public boolean StickToFloor(Vec3 inStepDown, BroadPhaseLayerFilter inBroadPhaseLayerFilter, ObjectLayerFilter inObjectLayerFilter, BodyFilter inBodyFilter, ShapeFilter inShapeFilter, TempAllocator inAllocator) {
        return false;
    }

    public void ExtendedUpdate(float inDeltaTime, Vec3 inGravity, ExtendedUpdateSettings inSettings, BroadPhaseLayerFilter inBroadPhaseLayerFilter, ObjectLayerFilter inObjectLayerFilter, BodyFilter inBodyFilter, ShapeFilter inShapeFilter, TempAllocator inAllocator) {
    }

    public void RefreshContacts(BroadPhaseLayerFilter inBroadPhaseLayerFilter, ObjectLayerFilter inObjectLayerFilter, BodyFilter inBodyFilter, ShapeFilter inShapeFilter, TempAllocator inAllocator) {
    }

    public void UpdateGroundVelocity() {
    }

    public boolean SetShape(Shape inShape, float inMaxPenetrationDepth, BroadPhaseLayerFilter inBroadPhaseLayerFilter, ObjectLayerFilter inObjectLayerFilter, BodyFilter inBodyFilter, ShapeFilter inShapeFilter, TempAllocator inAllocator) {
        return false;
    }

    public void SetInnerBodyShape(Shape inShape) {
    }

    public TransformedShape GetTransformedShape() {
        return null;
    }

    public boolean HasCollidedWith(BodyID inBodyID) {
        return false;
    }

    public boolean HasCollidedWithCharacterID(CharacterID inCharacterID) {
        return false;
    }

    public boolean HasCollidedWithCharacter(CharacterVirtual inCharacter) {
        return false;
    }

    public ArrayCharacterVirtualContact GetActiveContacts() {
        return null;
    }

    public CharacterContactListener GetListener() {
        return Jolt.GetCharacterContactListener(this);
    }
}
