/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.skeleton;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.Vec3;
import jolt.math.ArrayMat44;
import jolt.math.Mat44;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class SkeletonPose extends NativeObject {

    private Skeleton Skeleton_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_0;

    private SkeletalAnimationJointState SkeletalAnimationJointState_TEMP_GEN_0;

    private ArrayMat44 ArrayMat44_TEMP_GEN_0;

    private Mat44 Mat44_TEMP_GEN_0;

    static public final SkeletonPose NULL = SkeletonPose.native_new();

    public SkeletonPose() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected SkeletonPose(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static SkeletonPose native_new() {
        return new SkeletonPose((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetSkeleton(Skeleton inSkeleton) {
        internal_native_SetSkeleton(native_address, inSkeleton.native_address);
    }

    public static void internal_native_SetSkeleton(long this_addr, long inSkeleton_addr) {
        try {
            FFMHandles.internal_native_SetSkeleton__JJ.invokeExact(this_addr, inSkeleton_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Skeleton GetSkeleton() {
        long addr = internal_native_GetSkeleton_addr(native_address);
        if (addr == 0)
            return Skeleton.NULL;
        if (Skeleton_TEMP_GEN_0 == null)
            Skeleton_TEMP_GEN_0 = Skeleton.native_new();
        Skeleton_TEMP_GEN_0.internal_reset(addr, false);
        return Skeleton_TEMP_GEN_0;
    }

    public static long internal_native_GetSkeleton_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetSkeleton_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetRootOffset(Vec3 inOffset) {
        internal_native_SetRootOffset(native_address, inOffset.native_address);
    }

    public static void internal_native_SetRootOffset(long this_addr, long inOffset_addr) {
        try {
            FFMHandles.internal_native_SetRootOffset__JJ.invokeExact(this_addr, inOffset_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 GetRootOffset() {
        long addr = internal_native_GetRootOffset_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.native_new();
        Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetRootOffset_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetRootOffset_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetJointCount() {
        return internal_native_GetJointCount(native_address);
    }

    public static int internal_native_GetJointCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetJointCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public SkeletalAnimationJointState GetJoint(int inJoint) {
        long addr = internal_native_GetJoint_addr(native_address, inJoint);
        if (addr == 0)
            return SkeletalAnimationJointState.NULL;
        if (SkeletalAnimationJointState_TEMP_GEN_0 == null)
            SkeletalAnimationJointState_TEMP_GEN_0 = SkeletalAnimationJointState.native_new();
        SkeletalAnimationJointState_TEMP_GEN_0.internal_reset(addr, false);
        return SkeletalAnimationJointState_TEMP_GEN_0;
    }

    public static long internal_native_GetJoint_addr(long this_addr, int inJoint) {
        try {
            return (long) FFMHandles.internal_native_GetJoint_addr__JI.invokeExact(this_addr, inJoint);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ArrayMat44 GetJointMatrices() {
        long addr = internal_native_GetJointMatrices_addr(native_address);
        if (addr == 0)
            return ArrayMat44.NULL;
        if (ArrayMat44_TEMP_GEN_0 == null)
            ArrayMat44_TEMP_GEN_0 = ArrayMat44.native_new();
        ArrayMat44_TEMP_GEN_0.internal_reset(addr, false);
        return ArrayMat44_TEMP_GEN_0;
    }

    public static long internal_native_GetJointMatrices_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetJointMatrices_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Mat44 GetJointMatrix(int inJoint) {
        long addr = internal_native_GetJointMatrix_addr(native_address, inJoint);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_0 == null)
            Mat44_TEMP_GEN_0 = Mat44.native_new();
        Mat44_TEMP_GEN_0.internal_reset(addr, false);
        return Mat44_TEMP_GEN_0;
    }

    public static long internal_native_GetJointMatrix_addr(long this_addr, int inJoint) {
        try {
            return (long) FFMHandles.internal_native_GetJointMatrix_addr__JI.invokeExact(this_addr, inJoint);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void CalculateJointMatrices() {
        internal_native_CalculateJointMatrices(native_address);
    }

    public static void internal_native_CalculateJointMatrices(long this_addr) {
        try {
            FFMHandles.internal_native_CalculateJointMatrices__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void CalculateJointStates() {
        internal_native_CalculateJointStates(native_address);
    }

    public static void internal_native_CalculateJointStates(long this_addr) {
        try {
            FFMHandles.internal_native_CalculateJointStates__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_skeleton_skeletonpose_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_skeleton_skeletonpose_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetSkeleton__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_skeleton_skeletonpose_setskeleton", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetSkeleton_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_skeleton_skeletonpose_getskeleton_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetRootOffset__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_skeleton_skeletonpose_setrootoffset", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetRootOffset_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_skeleton_skeletonpose_getrootoffset_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetJointCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_skeleton_skeletonpose_getjointcount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetJoint_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_skeleton_skeletonpose_getjoint_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetJointMatrices_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_skeleton_skeletonpose_getjointmatrices_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetJointMatrix_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_skeleton_skeletonpose_getjointmatrix_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_CalculateJointMatrices__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_skeleton_skeletonpose_calculatejointmatrices", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CalculateJointStates__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_skeleton_skeletonpose_calculatejointstates", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));
    }
}
