/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ArrayWheelSettings extends NativeObject {

    static public final ArrayWheelSettings NULL = ArrayWheelSettings.native_new();

    public ArrayWheelSettings() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ArrayWheelSettings(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ArrayWheelSettings native_new() {
        return new ArrayWheelSettings((byte) 0, (char) 0);
    }

    public boolean empty() {
        return false;
    }

    public int size() {
        return 0;
    }

    public WheelSettings at(int inIndex) {
        return null;
    }

    public void push_back(WheelSettings inValue) {
    }

    public void resize(int inSize) {
    }

    public void clear() {
    }
}
