/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import jolt.physics.constraints.ConstraintSettings;
import jolt.math.Vec3;

public final class VehicleConstraintSettings extends ConstraintSettings {

    static public final VehicleConstraintSettings NULL = VehicleConstraintSettings.native_new();

    public VehicleConstraintSettings() {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleConstraintSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleConstraintSettings native_new() {
        return new VehicleConstraintSettings((byte) 0, (char) 0);
    }

    public Vec3 get_mUp() {
        return null;
    }

    public void set_mUp(Vec3 mUp) {
    }

    public Vec3 get_mForward() {
        return null;
    }

    public void set_mForward(Vec3 mForward) {
    }

    public float get_mMaxPitchRollAngle() {
        return 0;
    }

    public void set_mMaxPitchRollAngle(float mMaxPitchRollAngle) {
    }

    public ArrayWheelSettings get_mWheels() {
        return null;
    }

    public void set_mWheels(ArrayWheelSettings mWheels) {
    }

    public ArrayVehicleAntiRollBar get_mAntiRollBars() {
        return null;
    }

    public void set_mAntiRollBars(ArrayVehicleAntiRollBar mAntiRollBars) {
    }

    public VehicleControllerSettings get_mController() {
        return null;
    }

    public void set_mController(VehicleControllerSettings mController) {
    }
}
