/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

public final class VehicleTrack extends VehicleTrackSettings {

    static public final VehicleTrack NULL = VehicleTrack.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleTrack(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleTrack native_new() {
        return new VehicleTrack((byte) 0, (char) 0);
    }

    public float get_mAngularVelocity() {
        return 0;
    }

    public void set_mAngularVelocity(float mAngularVelocity) {
    }
}
