/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

public final class WheelSettingsTV extends WheelSettings {

    static public final WheelSettingsTV NULL = WheelSettingsTV.native_new();

    public WheelSettingsTV() {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WheelSettingsTV(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static WheelSettingsTV native_new() {
        return new WheelSettingsTV((byte) 0, (char) 0);
    }

    public float get_mLongitudinalFriction() {
        return 0;
    }

    public void set_mLongitudinalFriction(float mLongitudinalFriction) {
    }

    public float get_mLateralFriction() {
        return 0;
    }

    public void set_mLateralFriction(float mLateralFriction) {
    }
}
