/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class PhysicsStepListenerContext extends NativeObject {

    private PhysicsSystem PhysicsSystem_TEMP_GEN_0;

    static public final PhysicsStepListenerContext NULL = PhysicsStepListenerContext.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected PhysicsStepListenerContext(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static PhysicsStepListenerContext native_new() {
        return new PhysicsStepListenerContext((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mDeltaTime() {
        return internal_native_get_mDeltaTime(native_address);
    }

    public static float internal_native_get_mDeltaTime(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mDeltaTime__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mDeltaTime(float mDeltaTime) {
        internal_native_set_mDeltaTime(native_address, mDeltaTime);
    }

    public static void internal_native_set_mDeltaTime(long this_addr, float mDeltaTime) {
        try {
            FFMHandles.internal_native_set_mDeltaTime__JF.invokeExact(this_addr, mDeltaTime);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_mIsFirstStep() {
        return internal_native_get_mIsFirstStep(native_address);
    }

    public static boolean internal_native_get_mIsFirstStep(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_mIsFirstStep__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mIsFirstStep(boolean mIsFirstStep) {
        internal_native_set_mIsFirstStep(native_address, mIsFirstStep);
    }

    public static void internal_native_set_mIsFirstStep(long this_addr, boolean mIsFirstStep) {
        try {
            FFMHandles.internal_native_set_mIsFirstStep__JZ.invokeExact(this_addr, mIsFirstStep);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean get_mIsLastStep() {
        return internal_native_get_mIsLastStep(native_address);
    }

    public static boolean internal_native_get_mIsLastStep(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_get_mIsLastStep__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mIsLastStep(boolean mIsLastStep) {
        internal_native_set_mIsLastStep(native_address, mIsLastStep);
    }

    public static void internal_native_set_mIsLastStep(long this_addr, boolean mIsLastStep) {
        try {
            FFMHandles.internal_native_set_mIsLastStep__JZ.invokeExact(this_addr, mIsLastStep);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public PhysicsSystem get_mPhysicsSystem() {
        long addr = internal_native_get_mPhysicsSystem_addr(native_address);
        if (addr == 0)
            return PhysicsSystem.NULL;
        if (PhysicsSystem_TEMP_GEN_0 == null)
            PhysicsSystem_TEMP_GEN_0 = PhysicsSystem.native_new();
        PhysicsSystem_TEMP_GEN_0.internal_reset(addr, false);
        return PhysicsSystem_TEMP_GEN_0;
    }

    public static long internal_native_get_mPhysicsSystem_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mPhysicsSystem_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mPhysicsSystem(PhysicsSystem mPhysicsSystem) {
        internal_native_set_mPhysicsSystem(native_address, mPhysicsSystem.native_address);
    }

    public static void internal_native_set_mPhysicsSystem(long this_addr, long mPhysicsSystem_addr) {
        try {
            FFMHandles.internal_native_set_mPhysicsSystem__JJ.invokeExact(this_addr, mPhysicsSystem_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_physicssteplistenercontext_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mDeltaTime__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_physicssteplistenercontext_get_mdeltatime", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mDeltaTime__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_physicssteplistenercontext_set_mdeltatime", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_mIsFirstStep__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_physicssteplistenercontext_get_misfirststep", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mIsFirstStep__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_physicssteplistenercontext_set_misfirststep", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_mIsLastStep__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_physicssteplistenercontext_get_mislaststep", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mIsLastStep__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_physicssteplistenercontext_set_mislaststep", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_get_mPhysicsSystem_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_physicssteplistenercontext_get_mphysicssystem_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mPhysicsSystem__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_physicssteplistenercontext_set_mphysicssystem", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
