/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import jolt.physics.PhysicsStepListener;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class VehicleConstraintStepListener extends PhysicsStepListener {

    static public final VehicleConstraintStepListener NULL = VehicleConstraintStepListener.native_new();

    public VehicleConstraintStepListener(VehicleConstraint inConstraint) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_VehicleConstraint_addr(inConstraint.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_VehicleConstraint_addr(long inConstraint_addr) {
        try {
            return (long) FFMHandles.internal_native_create_VehicleConstraint_addr__J.invokeExact(inConstraint_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleConstraintStepListener(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleConstraintStepListener native_new() {
        return new VehicleConstraintStepListener((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_VehicleConstraint_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_vehicleconstraintsteplistener_create_vehicleconstraint_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_vehicleconstraintsteplistener_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));
    }
}
