/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import jolt.core.LinearCurve;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class WheelSettingsWV extends WheelSettings {

    private LinearCurve LinearCurve_TEMP_GEN_0;

    private LinearCurve LinearCurve_TEMP_GEN_1;

    static public final WheelSettingsWV NULL = WheelSettingsWV.native_new();

    public WheelSettingsWV() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected WheelSettingsWV(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static WheelSettingsWV native_new() {
        return new WheelSettingsWV((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mInertia() {
        return internal_native_get_mInertia(native_address);
    }

    public static float internal_native_get_mInertia(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mInertia__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mInertia(float mInertia) {
        internal_native_set_mInertia(native_address, mInertia);
    }

    public static void internal_native_set_mInertia(long this_addr, float mInertia) {
        try {
            FFMHandles.internal_native_set_mInertia__JF.invokeExact(this_addr, mInertia);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mAngularDamping() {
        return internal_native_get_mAngularDamping(native_address);
    }

    public static float internal_native_get_mAngularDamping(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mAngularDamping__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mAngularDamping(float mAngularDamping) {
        internal_native_set_mAngularDamping(native_address, mAngularDamping);
    }

    public static void internal_native_set_mAngularDamping(long this_addr, float mAngularDamping) {
        try {
            FFMHandles.internal_native_set_mAngularDamping__JF.invokeExact(this_addr, mAngularDamping);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mMaxSteerAngle() {
        return internal_native_get_mMaxSteerAngle(native_address);
    }

    public static float internal_native_get_mMaxSteerAngle(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mMaxSteerAngle__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mMaxSteerAngle(float mMaxSteerAngle) {
        internal_native_set_mMaxSteerAngle(native_address, mMaxSteerAngle);
    }

    public static void internal_native_set_mMaxSteerAngle(long this_addr, float mMaxSteerAngle) {
        try {
            FFMHandles.internal_native_set_mMaxSteerAngle__JF.invokeExact(this_addr, mMaxSteerAngle);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public LinearCurve get_mLongitudinalFriction() {
        long addr = internal_native_get_mLongitudinalFriction_addr(native_address);
        if (addr == 0)
            return LinearCurve.NULL;
        if (LinearCurve_TEMP_GEN_0 == null)
            LinearCurve_TEMP_GEN_0 = LinearCurve.native_new();
        LinearCurve_TEMP_GEN_0.internal_reset(addr, false);
        return LinearCurve_TEMP_GEN_0;
    }

    public static long internal_native_get_mLongitudinalFriction_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mLongitudinalFriction_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mLongitudinalFriction(LinearCurve mLongitudinalFriction) {
        internal_native_set_mLongitudinalFriction(native_address, mLongitudinalFriction.native_address);
    }

    public static void internal_native_set_mLongitudinalFriction(long this_addr, long mLongitudinalFriction_addr) {
        try {
            FFMHandles.internal_native_set_mLongitudinalFriction__JJ.invokeExact(this_addr, mLongitudinalFriction_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public LinearCurve get_mLateralFriction() {
        long addr = internal_native_get_mLateralFriction_addr(native_address);
        if (addr == 0)
            return LinearCurve.NULL;
        if (LinearCurve_TEMP_GEN_1 == null)
            LinearCurve_TEMP_GEN_1 = LinearCurve.native_new();
        LinearCurve_TEMP_GEN_1.internal_reset(addr, false);
        return LinearCurve_TEMP_GEN_1;
    }

    public static long internal_native_get_mLateralFriction_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mLateralFriction_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mLateralFriction(LinearCurve mLateralFriction) {
        internal_native_set_mLateralFriction(native_address, mLateralFriction.native_address);
    }

    public static void internal_native_set_mLateralFriction(long this_addr, long mLateralFriction_addr) {
        try {
            FFMHandles.internal_native_set_mLateralFriction__JJ.invokeExact(this_addr, mLateralFriction_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mMaxBrakeTorque() {
        return internal_native_get_mMaxBrakeTorque(native_address);
    }

    public static float internal_native_get_mMaxBrakeTorque(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mMaxBrakeTorque__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mMaxBrakeTorque(float mMaxBrakeTorque) {
        internal_native_set_mMaxBrakeTorque(native_address, mMaxBrakeTorque);
    }

    public static void internal_native_set_mMaxBrakeTorque(long this_addr, float mMaxBrakeTorque) {
        try {
            FFMHandles.internal_native_set_mMaxBrakeTorque__JF.invokeExact(this_addr, mMaxBrakeTorque);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mMaxHandBrakeTorque() {
        return internal_native_get_mMaxHandBrakeTorque(native_address);
    }

    public static float internal_native_get_mMaxHandBrakeTorque(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mMaxHandBrakeTorque__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mMaxHandBrakeTorque(float mMaxHandBrakeTorque) {
        internal_native_set_mMaxHandBrakeTorque(native_address, mMaxHandBrakeTorque);
    }

    public static void internal_native_set_mMaxHandBrakeTorque(long this_addr, float mMaxHandBrakeTorque) {
        try {
            FFMHandles.internal_native_set_mMaxHandBrakeTorque__JF.invokeExact(this_addr, mMaxHandBrakeTorque);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mInertia__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_get_minertia", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mInertia__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_set_minertia", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_mAngularDamping__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_get_mangulardamping", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mAngularDamping__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_set_mangulardamping", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_mMaxSteerAngle__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_get_mmaxsteerangle", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mMaxSteerAngle__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_set_mmaxsteerangle", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_mLongitudinalFriction_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_get_mlongitudinalfriction_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mLongitudinalFriction__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_set_mlongitudinalfriction", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mLateralFriction_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_get_mlateralfriction_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mLateralFriction__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_set_mlateralfriction", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mMaxBrakeTorque__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_get_mmaxbraketorque", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mMaxBrakeTorque__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_set_mmaxbraketorque", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_mMaxHandBrakeTorque__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_get_mmaxhandbraketorque", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mMaxHandBrakeTorque__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_vehicle_wheelsettingswv_set_mmaxhandbraketorque", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));
    }
}
