/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.hair;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.compute.ComputeSystem;
import jolt.math.Mat44;
import jolt.math.Mat44MemRef;
import jolt.math.ArrayVec3;
import jolt.physics.StateRecorder;
import jolt.math.VertexList;
import jolt.geometry.IndexedTriangleNoMaterialList;
import jolt.math.ArrayMat44;
import jolt.math.UVec4;
import jolt.math.Vec3;
import jolt.geometry.AABox;
import jolt.math.ArrayFloat;
import jolt.compute.ComputeBuffer;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class HairSettings extends NativeObject {

    private ArrayHairSettingsSVertex ArrayHairSettingsSVertex_TEMP_GEN_0;

    private ArrayHairSettingsSStrand ArrayHairSettingsSStrand_TEMP_GEN_0;

    private ArrayHairSettingsRVertex ArrayHairSettingsRVertex_TEMP_GEN_0;

    private ArrayHairSettingsRStrand ArrayHairSettingsRStrand_TEMP_GEN_0;

    private VertexList VertexList_TEMP_GEN_0;

    private IndexedTriangleNoMaterialList IndexedTriangleNoMaterialList_TEMP_GEN_0;

    private ArrayMat44 ArrayMat44_TEMP_GEN_0;

    private ArrayHairSettingsSkinWeight ArrayHairSettingsSkinWeight_TEMP_GEN_0;

    private UVec4 UVec4_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_1;

    private ArrayHairSettingsMaterial ArrayHairSettingsMaterial_TEMP_GEN_0;

    private ArrayHairSettingsSkinPoint ArrayHairSettingsSkinPoint_TEMP_GEN_0;

    private AABox AABox_TEMP_GEN_0;

    private ArrayFloat ArrayFloat_TEMP_GEN_0;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_0;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_1;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_2;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_3;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_4;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_5;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_6;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_7;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_8;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_9;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_10;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_11;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_12;

    private ComputeBuffer ComputeBuffer_TEMP_GEN_13;

    static public final HairSettings NULL = HairSettings.native_new();

    public HairSettings() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected HairSettings(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static HairSettings native_new() {
        return new HairSettings((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetRefCount() {
        return internal_native_GetRefCount(native_address);
    }

    public static int internal_native_GetRefCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetRefCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void AddRef() {
        internal_native_AddRef(native_address);
    }

    public static void internal_native_AddRef(long this_addr) {
        try {
            FFMHandles.internal_native_AddRef__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Release() {
        internal_native_Release(native_address);
    }

    public static void internal_native_Release(long this_addr) {
        try {
            FFMHandles.internal_native_Release__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void InitRenderAndSimulationStrands(ArrayHairSettingsSVertex inVertices, ArrayHairSettingsSStrand inStrands) {
        internal_native_InitRenderAndSimulationStrands(native_address, inVertices.native_address, inStrands.native_address);
    }

    public static void internal_native_InitRenderAndSimulationStrands(long this_addr, long inVertices_addr, long inStrands_addr) {
        try {
            FFMHandles.internal_native_InitRenderAndSimulationStrands__JJJ.invokeExact(this_addr, inVertices_addr, inStrands_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static void sResample(ArrayHairSettingsSVertex ioVertices, ArrayHairSettingsSStrand ioStrands, int inNumVerticesPerStrand) {
        internal_native_sResample(ioVertices.native_address, ioStrands.native_address, inNumVerticesPerStrand);
    }

    public static void internal_native_sResample(long ioVertices_addr, long ioStrands_addr, int inNumVerticesPerStrand) {
        try {
            FFMHandles.internal_native_sResample__JJI.invokeExact(ioVertices_addr, ioStrands_addr, inNumVerticesPerStrand);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void InitCompute(ComputeSystem inComputeSystem) {
        internal_native_InitCompute(native_address, inComputeSystem.native_address);
    }

    public static void internal_native_InitCompute(long this_addr, long inComputeSystem_addr) {
        try {
            FFMHandles.internal_native_InitCompute__JJ.invokeExact(this_addr, inComputeSystem_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetNeutralDensity(int inX, int inY, int inZ) {
        return internal_native_GetNeutralDensity(native_address, inX, inY, inZ);
    }

    public static float internal_native_GetNeutralDensity(long this_addr, int inX, int inY, int inZ) {
        try {
            return (float) FFMHandles.internal_native_GetNeutralDensity__JIII.invokeExact(this_addr, inX, inY, inZ);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetNumVerticesPadded() {
        return internal_native_GetNumVerticesPadded(native_address);
    }

    public static int internal_native_GetNumVerticesPadded(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetNumVerticesPadded__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void PrepareForScalpSkinning(Mat44 inJointToHair, Mat44MemRef inJointMatrices, Mat44MemRef outJointMatrices) {
        internal_native_PrepareForScalpSkinning(native_address, inJointToHair.native_address, inJointMatrices.native_address, outJointMatrices.native_address);
    }

    public static void internal_native_PrepareForScalpSkinning(long this_addr, long inJointToHair_addr, long inJointMatrices_addr, long outJointMatrices_addr) {
        try {
            FFMHandles.internal_native_PrepareForScalpSkinning__JJJJ.invokeExact(this_addr, inJointToHair_addr, inJointMatrices_addr, outJointMatrices_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SkinScalpVertices(Mat44 inJointToHair, Mat44MemRef inJointMatrices, ArrayVec3 outVertices) {
        internal_native_SkinScalpVertices(native_address, inJointToHair.native_address, inJointMatrices.native_address, outVertices.native_address);
    }

    public static void internal_native_SkinScalpVertices(long this_addr, long inJointToHair_addr, long inJointMatrices_addr, long outVertices_addr) {
        try {
            FFMHandles.internal_native_SkinScalpVertices__JJJJ.invokeExact(this_addr, inJointToHair_addr, inJointMatrices_addr, outVertices_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SaveBinaryState(StateRecorder inStream) {
        internal_native_SaveBinaryState(native_address, inStream.native_address);
    }

    public static void internal_native_SaveBinaryState(long this_addr, long inStream_addr) {
        try {
            FFMHandles.internal_native_SaveBinaryState__JJ.invokeExact(this_addr, inStream_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void RestoreBinaryState(StateRecorder inStream) {
        internal_native_RestoreBinaryState(native_address, inStream.native_address);
    }

    public static void internal_native_RestoreBinaryState(long this_addr, long inStream_addr) {
        try {
            FFMHandles.internal_native_RestoreBinaryState__JJ.invokeExact(this_addr, inStream_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static int get_cNoInfluence() {
        return internal_native_get_cNoInfluence();
    }

    public static int internal_native_get_cNoInfluence() {
        try {
            return (int) FFMHandles.internal_native_get_cNoInfluence__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static int get_cDefaultIterationsPerSecond() {
        return internal_native_get_cDefaultIterationsPerSecond();
    }

    public static int internal_native_get_cDefaultIterationsPerSecond() {
        try {
            return (int) FFMHandles.internal_native_get_cDefaultIterationsPerSecond__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ArrayHairSettingsSVertex get_mSimVertices() {
        long addr = internal_native_get_mSimVertices_addr(native_address);
        if (addr == 0)
            return ArrayHairSettingsSVertex.NULL;
        if (ArrayHairSettingsSVertex_TEMP_GEN_0 == null)
            ArrayHairSettingsSVertex_TEMP_GEN_0 = ArrayHairSettingsSVertex.native_new();
        ArrayHairSettingsSVertex_TEMP_GEN_0.internal_reset(addr, false);
        return ArrayHairSettingsSVertex_TEMP_GEN_0;
    }

    public static long internal_native_get_mSimVertices_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mSimVertices_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mSimVertices(ArrayHairSettingsSVertex mSimVertices) {
        internal_native_set_mSimVertices(native_address, mSimVertices.native_address);
    }

    public static void internal_native_set_mSimVertices(long this_addr, long mSimVertices_addr) {
        try {
            FFMHandles.internal_native_set_mSimVertices__JJ.invokeExact(this_addr, mSimVertices_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ArrayHairSettingsSStrand get_mSimStrands() {
        long addr = internal_native_get_mSimStrands_addr(native_address);
        if (addr == 0)
            return ArrayHairSettingsSStrand.NULL;
        if (ArrayHairSettingsSStrand_TEMP_GEN_0 == null)
            ArrayHairSettingsSStrand_TEMP_GEN_0 = ArrayHairSettingsSStrand.native_new();
        ArrayHairSettingsSStrand_TEMP_GEN_0.internal_reset(addr, false);
        return ArrayHairSettingsSStrand_TEMP_GEN_0;
    }

    public static long internal_native_get_mSimStrands_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mSimStrands_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mSimStrands(ArrayHairSettingsSStrand mSimStrands) {
        internal_native_set_mSimStrands(native_address, mSimStrands.native_address);
    }

    public static void internal_native_set_mSimStrands(long this_addr, long mSimStrands_addr) {
        try {
            FFMHandles.internal_native_set_mSimStrands__JJ.invokeExact(this_addr, mSimStrands_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ArrayHairSettingsRVertex get_mRenderVertices() {
        long addr = internal_native_get_mRenderVertices_addr(native_address);
        if (addr == 0)
            return ArrayHairSettingsRVertex.NULL;
        if (ArrayHairSettingsRVertex_TEMP_GEN_0 == null)
            ArrayHairSettingsRVertex_TEMP_GEN_0 = ArrayHairSettingsRVertex.native_new();
        ArrayHairSettingsRVertex_TEMP_GEN_0.internal_reset(addr, false);
        return ArrayHairSettingsRVertex_TEMP_GEN_0;
    }

    public static long internal_native_get_mRenderVertices_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mRenderVertices_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mRenderVertices(ArrayHairSettingsRVertex mRenderVertices) {
        internal_native_set_mRenderVertices(native_address, mRenderVertices.native_address);
    }

    public static void internal_native_set_mRenderVertices(long this_addr, long mRenderVertices_addr) {
        try {
            FFMHandles.internal_native_set_mRenderVertices__JJ.invokeExact(this_addr, mRenderVertices_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ArrayHairSettingsRStrand get_mRenderStrands() {
        long addr = internal_native_get_mRenderStrands_addr(native_address);
        if (addr == 0)
            return ArrayHairSettingsRStrand.NULL;
        if (ArrayHairSettingsRStrand_TEMP_GEN_0 == null)
            ArrayHairSettingsRStrand_TEMP_GEN_0 = ArrayHairSettingsRStrand.native_new();
        ArrayHairSettingsRStrand_TEMP_GEN_0.internal_reset(addr, false);
        return ArrayHairSettingsRStrand_TEMP_GEN_0;
    }

    public static long internal_native_get_mRenderStrands_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mRenderStrands_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mRenderStrands(ArrayHairSettingsRStrand mRenderStrands) {
        internal_native_set_mRenderStrands(native_address, mRenderStrands.native_address);
    }

    public static void internal_native_set_mRenderStrands(long this_addr, long mRenderStrands_addr) {
        try {
            FFMHandles.internal_native_set_mRenderStrands__JJ.invokeExact(this_addr, mRenderStrands_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public VertexList get_mScalpVertices() {
        long addr = internal_native_get_mScalpVertices_addr(native_address);
        if (addr == 0)
            return VertexList.NULL;
        if (VertexList_TEMP_GEN_0 == null)
            VertexList_TEMP_GEN_0 = VertexList.native_new();
        VertexList_TEMP_GEN_0.internal_reset(addr, false);
        return VertexList_TEMP_GEN_0;
    }

    public static long internal_native_get_mScalpVertices_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mScalpVertices_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mScalpVertices(VertexList mScalpVertices) {
        internal_native_set_mScalpVertices(native_address, mScalpVertices.native_address);
    }

    public static void internal_native_set_mScalpVertices(long this_addr, long mScalpVertices_addr) {
        try {
            FFMHandles.internal_native_set_mScalpVertices__JJ.invokeExact(this_addr, mScalpVertices_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public IndexedTriangleNoMaterialList get_mScalpTriangles() {
        long addr = internal_native_get_mScalpTriangles_addr(native_address);
        if (addr == 0)
            return IndexedTriangleNoMaterialList.NULL;
        if (IndexedTriangleNoMaterialList_TEMP_GEN_0 == null)
            IndexedTriangleNoMaterialList_TEMP_GEN_0 = IndexedTriangleNoMaterialList.native_new();
        IndexedTriangleNoMaterialList_TEMP_GEN_0.internal_reset(addr, false);
        return IndexedTriangleNoMaterialList_TEMP_GEN_0;
    }

    public static long internal_native_get_mScalpTriangles_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mScalpTriangles_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mScalpTriangles(IndexedTriangleNoMaterialList mScalpTriangles) {
        internal_native_set_mScalpTriangles(native_address, mScalpTriangles.native_address);
    }

    public static void internal_native_set_mScalpTriangles(long this_addr, long mScalpTriangles_addr) {
        try {
            FFMHandles.internal_native_set_mScalpTriangles__JJ.invokeExact(this_addr, mScalpTriangles_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ArrayMat44 get_mScalpInverseBindPose() {
        long addr = internal_native_get_mScalpInverseBindPose_addr(native_address);
        if (addr == 0)
            return ArrayMat44.NULL;
        if (ArrayMat44_TEMP_GEN_0 == null)
            ArrayMat44_TEMP_GEN_0 = ArrayMat44.native_new();
        ArrayMat44_TEMP_GEN_0.internal_reset(addr, false);
        return ArrayMat44_TEMP_GEN_0;
    }

    public static long internal_native_get_mScalpInverseBindPose_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mScalpInverseBindPose_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mScalpInverseBindPose(ArrayMat44 mScalpInverseBindPose) {
        internal_native_set_mScalpInverseBindPose(native_address, mScalpInverseBindPose.native_address);
    }

    public static void internal_native_set_mScalpInverseBindPose(long this_addr, long mScalpInverseBindPose_addr) {
        try {
            FFMHandles.internal_native_set_mScalpInverseBindPose__JJ.invokeExact(this_addr, mScalpInverseBindPose_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ArrayHairSettingsSkinWeight get_mScalpSkinWeights() {
        long addr = internal_native_get_mScalpSkinWeights_addr(native_address);
        if (addr == 0)
            return ArrayHairSettingsSkinWeight.NULL;
        if (ArrayHairSettingsSkinWeight_TEMP_GEN_0 == null)
            ArrayHairSettingsSkinWeight_TEMP_GEN_0 = ArrayHairSettingsSkinWeight.native_new();
        ArrayHairSettingsSkinWeight_TEMP_GEN_0.internal_reset(addr, false);
        return ArrayHairSettingsSkinWeight_TEMP_GEN_0;
    }

    public static long internal_native_get_mScalpSkinWeights_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mScalpSkinWeights_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mScalpSkinWeights(ArrayHairSettingsSkinWeight mScalpSkinWeights) {
        internal_native_set_mScalpSkinWeights(native_address, mScalpSkinWeights.native_address);
    }

    public static void internal_native_set_mScalpSkinWeights(long this_addr, long mScalpSkinWeights_addr) {
        try {
            FFMHandles.internal_native_set_mScalpSkinWeights__JJ.invokeExact(this_addr, mScalpSkinWeights_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_mScalpNumSkinWeightsPerVertex() {
        return internal_native_get_mScalpNumSkinWeightsPerVertex(native_address);
    }

    public static int internal_native_get_mScalpNumSkinWeightsPerVertex(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_mScalpNumSkinWeightsPerVertex__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mScalpNumSkinWeightsPerVertex(int mScalpNumSkinWeightsPerVertex) {
        internal_native_set_mScalpNumSkinWeightsPerVertex(native_address, mScalpNumSkinWeightsPerVertex);
    }

    public static void internal_native_set_mScalpNumSkinWeightsPerVertex(long this_addr, int mScalpNumSkinWeightsPerVertex) {
        try {
            FFMHandles.internal_native_set_mScalpNumSkinWeightsPerVertex__JI.invokeExact(this_addr, mScalpNumSkinWeightsPerVertex);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_mNumIterationsPerSecond() {
        return internal_native_get_mNumIterationsPerSecond(native_address);
    }

    public static int internal_native_get_mNumIterationsPerSecond(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_mNumIterationsPerSecond__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mNumIterationsPerSecond(int mNumIterationsPerSecond) {
        internal_native_set_mNumIterationsPerSecond(native_address, mNumIterationsPerSecond);
    }

    public static void internal_native_set_mNumIterationsPerSecond(long this_addr, int mNumIterationsPerSecond) {
        try {
            FFMHandles.internal_native_set_mNumIterationsPerSecond__JI.invokeExact(this_addr, mNumIterationsPerSecond);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mMaxDeltaTime() {
        return internal_native_get_mMaxDeltaTime(native_address);
    }

    public static float internal_native_get_mMaxDeltaTime(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mMaxDeltaTime__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mMaxDeltaTime(float mMaxDeltaTime) {
        internal_native_set_mMaxDeltaTime(native_address, mMaxDeltaTime);
    }

    public static void internal_native_set_mMaxDeltaTime(long this_addr, float mMaxDeltaTime) {
        try {
            FFMHandles.internal_native_set_mMaxDeltaTime__JF.invokeExact(this_addr, mMaxDeltaTime);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public UVec4 get_mGridSize() {
        long addr = internal_native_get_mGridSize_addr(native_address);
        if (addr == 0)
            return UVec4.NULL;
        if (UVec4_TEMP_GEN_0 == null)
            UVec4_TEMP_GEN_0 = UVec4.native_new();
        UVec4_TEMP_GEN_0.internal_reset(addr, false);
        return UVec4_TEMP_GEN_0;
    }

    public static long internal_native_get_mGridSize_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mGridSize_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mGridSize(UVec4 mGridSize) {
        internal_native_set_mGridSize(native_address, mGridSize.native_address);
    }

    public static void internal_native_set_mGridSize(long this_addr, long mGridSize_addr) {
        try {
            FFMHandles.internal_native_set_mGridSize__JJ.invokeExact(this_addr, mGridSize_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 get_mSimulationBoundsPadding() {
        long addr = internal_native_get_mSimulationBoundsPadding_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.native_new();
        Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return Vec3_TEMP_GEN_0;
    }

    public static long internal_native_get_mSimulationBoundsPadding_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mSimulationBoundsPadding_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mSimulationBoundsPadding(Vec3 mSimulationBoundsPadding) {
        internal_native_set_mSimulationBoundsPadding(native_address, mSimulationBoundsPadding.native_address);
    }

    public static void internal_native_set_mSimulationBoundsPadding(long this_addr, long mSimulationBoundsPadding_addr) {
        try {
            FFMHandles.internal_native_set_mSimulationBoundsPadding__JJ.invokeExact(this_addr, mSimulationBoundsPadding_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 get_mInitialGravity() {
        long addr = internal_native_get_mInitialGravity_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_1 == null)
            Vec3_TEMP_GEN_1 = Vec3.native_new();
        Vec3_TEMP_GEN_1.internal_reset(addr, false);
        return Vec3_TEMP_GEN_1;
    }

    public static long internal_native_get_mInitialGravity_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mInitialGravity_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mInitialGravity(Vec3 mInitialGravity) {
        internal_native_set_mInitialGravity(native_address, mInitialGravity.native_address);
    }

    public static void internal_native_set_mInitialGravity(long this_addr, long mInitialGravity_addr) {
        try {
            FFMHandles.internal_native_set_mInitialGravity__JJ.invokeExact(this_addr, mInitialGravity_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ArrayHairSettingsMaterial get_mMaterials() {
        long addr = internal_native_get_mMaterials_addr(native_address);
        if (addr == 0)
            return ArrayHairSettingsMaterial.NULL;
        if (ArrayHairSettingsMaterial_TEMP_GEN_0 == null)
            ArrayHairSettingsMaterial_TEMP_GEN_0 = ArrayHairSettingsMaterial.native_new();
        ArrayHairSettingsMaterial_TEMP_GEN_0.internal_reset(addr, false);
        return ArrayHairSettingsMaterial_TEMP_GEN_0;
    }

    public static long internal_native_get_mMaterials_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mMaterials_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mMaterials(ArrayHairSettingsMaterial mMaterials) {
        internal_native_set_mMaterials(native_address, mMaterials.native_address);
    }

    public static void internal_native_set_mMaterials(long this_addr, long mMaterials_addr) {
        try {
            FFMHandles.internal_native_set_mMaterials__JJ.invokeExact(this_addr, mMaterials_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ArrayHairSettingsSkinPoint get_mSkinPoints() {
        long addr = internal_native_get_mSkinPoints_addr(native_address);
        if (addr == 0)
            return ArrayHairSettingsSkinPoint.NULL;
        if (ArrayHairSettingsSkinPoint_TEMP_GEN_0 == null)
            ArrayHairSettingsSkinPoint_TEMP_GEN_0 = ArrayHairSettingsSkinPoint.native_new();
        ArrayHairSettingsSkinPoint_TEMP_GEN_0.internal_reset(addr, false);
        return ArrayHairSettingsSkinPoint_TEMP_GEN_0;
    }

    public static long internal_native_get_mSkinPoints_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mSkinPoints_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mSkinPoints(ArrayHairSettingsSkinPoint mSkinPoints) {
        internal_native_set_mSkinPoints(native_address, mSkinPoints.native_address);
    }

    public static void internal_native_set_mSkinPoints(long this_addr, long mSkinPoints_addr) {
        try {
            FFMHandles.internal_native_set_mSkinPoints__JJ.invokeExact(this_addr, mSkinPoints_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public AABox get_mSimulationBounds() {
        long addr = internal_native_get_mSimulationBounds_addr(native_address);
        if (addr == 0)
            return AABox.NULL;
        if (AABox_TEMP_GEN_0 == null)
            AABox_TEMP_GEN_0 = AABox.native_new();
        AABox_TEMP_GEN_0.internal_reset(addr, false);
        return AABox_TEMP_GEN_0;
    }

    public static long internal_native_get_mSimulationBounds_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mSimulationBounds_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mSimulationBounds(AABox mSimulationBounds) {
        internal_native_set_mSimulationBounds(native_address, mSimulationBounds.native_address);
    }

    public static void internal_native_set_mSimulationBounds(long this_addr, long mSimulationBounds_addr) {
        try {
            FFMHandles.internal_native_set_mSimulationBounds__JJ.invokeExact(this_addr, mSimulationBounds_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ArrayFloat get_mNeutralDensity() {
        long addr = internal_native_get_mNeutralDensity_addr(native_address);
        if (addr == 0)
            return ArrayFloat.NULL;
        if (ArrayFloat_TEMP_GEN_0 == null)
            ArrayFloat_TEMP_GEN_0 = ArrayFloat.native_new();
        ArrayFloat_TEMP_GEN_0.internal_reset(addr, false);
        return ArrayFloat_TEMP_GEN_0;
    }

    public static long internal_native_get_mNeutralDensity_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mNeutralDensity_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mNeutralDensity(ArrayFloat mNeutralDensity) {
        internal_native_set_mNeutralDensity(native_address, mNeutralDensity.native_address);
    }

    public static void internal_native_set_mNeutralDensity(long this_addr, long mNeutralDensity_addr) {
        try {
            FFMHandles.internal_native_set_mNeutralDensity__JJ.invokeExact(this_addr, mNeutralDensity_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mDensityScale() {
        return internal_native_get_mDensityScale(native_address);
    }

    public static float internal_native_get_mDensityScale(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mDensityScale__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mDensityScale(float mDensityScale) {
        internal_native_set_mDensityScale(native_address, mDensityScale);
    }

    public static void internal_native_set_mDensityScale(long this_addr, float mDensityScale) {
        try {
            FFMHandles.internal_native_set_mDensityScale__JF.invokeExact(this_addr, mDensityScale);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_mMaxVerticesPerStrand() {
        return internal_native_get_mMaxVerticesPerStrand(native_address);
    }

    public static int internal_native_get_mMaxVerticesPerStrand(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_mMaxVerticesPerStrand__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mMaxVerticesPerStrand(int mMaxVerticesPerStrand) {
        internal_native_set_mMaxVerticesPerStrand(native_address, mMaxVerticesPerStrand);
    }

    public static void internal_native_set_mMaxVerticesPerStrand(long this_addr, int mMaxVerticesPerStrand) {
        try {
            FFMHandles.internal_native_set_mMaxVerticesPerStrand__JI.invokeExact(this_addr, mMaxVerticesPerStrand);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mScalpVerticesCB() {
        long addr = internal_native_get_mScalpVerticesCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_0 == null)
            ComputeBuffer_TEMP_GEN_0 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_0.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_0;
    }

    public static long internal_native_get_mScalpVerticesCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mScalpVerticesCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mScalpVerticesCB(ComputeBuffer mScalpVerticesCB) {
        internal_native_set_mScalpVerticesCB(native_address, mScalpVerticesCB.native_address);
    }

    public static void internal_native_set_mScalpVerticesCB(long this_addr, long mScalpVerticesCB_addr) {
        try {
            FFMHandles.internal_native_set_mScalpVerticesCB__JJ.invokeExact(this_addr, mScalpVerticesCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mScalpTrianglesCB() {
        long addr = internal_native_get_mScalpTrianglesCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_1 == null)
            ComputeBuffer_TEMP_GEN_1 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_1.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_1;
    }

    public static long internal_native_get_mScalpTrianglesCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mScalpTrianglesCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mScalpTrianglesCB(ComputeBuffer mScalpTrianglesCB) {
        internal_native_set_mScalpTrianglesCB(native_address, mScalpTrianglesCB.native_address);
    }

    public static void internal_native_set_mScalpTrianglesCB(long this_addr, long mScalpTrianglesCB_addr) {
        try {
            FFMHandles.internal_native_set_mScalpTrianglesCB__JJ.invokeExact(this_addr, mScalpTrianglesCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mScalpSkinWeightsCB() {
        long addr = internal_native_get_mScalpSkinWeightsCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_2 == null)
            ComputeBuffer_TEMP_GEN_2 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_2.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_2;
    }

    public static long internal_native_get_mScalpSkinWeightsCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mScalpSkinWeightsCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mScalpSkinWeightsCB(ComputeBuffer mScalpSkinWeightsCB) {
        internal_native_set_mScalpSkinWeightsCB(native_address, mScalpSkinWeightsCB.native_address);
    }

    public static void internal_native_set_mScalpSkinWeightsCB(long this_addr, long mScalpSkinWeightsCB_addr) {
        try {
            FFMHandles.internal_native_set_mScalpSkinWeightsCB__JJ.invokeExact(this_addr, mScalpSkinWeightsCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mSkinPointsCB() {
        long addr = internal_native_get_mSkinPointsCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_3 == null)
            ComputeBuffer_TEMP_GEN_3 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_3.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_3;
    }

    public static long internal_native_get_mSkinPointsCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mSkinPointsCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mSkinPointsCB(ComputeBuffer mSkinPointsCB) {
        internal_native_set_mSkinPointsCB(native_address, mSkinPointsCB.native_address);
    }

    public static void internal_native_set_mSkinPointsCB(long this_addr, long mSkinPointsCB_addr) {
        try {
            FFMHandles.internal_native_set_mSkinPointsCB__JJ.invokeExact(this_addr, mSkinPointsCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mVerticesFixedCB() {
        long addr = internal_native_get_mVerticesFixedCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_4 == null)
            ComputeBuffer_TEMP_GEN_4 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_4.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_4;
    }

    public static long internal_native_get_mVerticesFixedCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mVerticesFixedCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mVerticesFixedCB(ComputeBuffer mVerticesFixedCB) {
        internal_native_set_mVerticesFixedCB(native_address, mVerticesFixedCB.native_address);
    }

    public static void internal_native_set_mVerticesFixedCB(long this_addr, long mVerticesFixedCB_addr) {
        try {
            FFMHandles.internal_native_set_mVerticesFixedCB__JJ.invokeExact(this_addr, mVerticesFixedCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mVerticesPositionCB() {
        long addr = internal_native_get_mVerticesPositionCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_5 == null)
            ComputeBuffer_TEMP_GEN_5 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_5.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_5;
    }

    public static long internal_native_get_mVerticesPositionCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mVerticesPositionCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mVerticesPositionCB(ComputeBuffer mVerticesPositionCB) {
        internal_native_set_mVerticesPositionCB(native_address, mVerticesPositionCB.native_address);
    }

    public static void internal_native_set_mVerticesPositionCB(long this_addr, long mVerticesPositionCB_addr) {
        try {
            FFMHandles.internal_native_set_mVerticesPositionCB__JJ.invokeExact(this_addr, mVerticesPositionCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mVerticesBishopCB() {
        long addr = internal_native_get_mVerticesBishopCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_6 == null)
            ComputeBuffer_TEMP_GEN_6 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_6.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_6;
    }

    public static long internal_native_get_mVerticesBishopCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mVerticesBishopCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mVerticesBishopCB(ComputeBuffer mVerticesBishopCB) {
        internal_native_set_mVerticesBishopCB(native_address, mVerticesBishopCB.native_address);
    }

    public static void internal_native_set_mVerticesBishopCB(long this_addr, long mVerticesBishopCB_addr) {
        try {
            FFMHandles.internal_native_set_mVerticesBishopCB__JJ.invokeExact(this_addr, mVerticesBishopCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mVerticesOmega0CB() {
        long addr = internal_native_get_mVerticesOmega0CB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_7 == null)
            ComputeBuffer_TEMP_GEN_7 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_7.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_7;
    }

    public static long internal_native_get_mVerticesOmega0CB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mVerticesOmega0CB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mVerticesOmega0CB(ComputeBuffer mVerticesOmega0CB) {
        internal_native_set_mVerticesOmega0CB(native_address, mVerticesOmega0CB.native_address);
    }

    public static void internal_native_set_mVerticesOmega0CB(long this_addr, long mVerticesOmega0CB_addr) {
        try {
            FFMHandles.internal_native_set_mVerticesOmega0CB__JJ.invokeExact(this_addr, mVerticesOmega0CB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mVerticesLengthCB() {
        long addr = internal_native_get_mVerticesLengthCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_8 == null)
            ComputeBuffer_TEMP_GEN_8 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_8.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_8;
    }

    public static long internal_native_get_mVerticesLengthCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mVerticesLengthCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mVerticesLengthCB(ComputeBuffer mVerticesLengthCB) {
        internal_native_set_mVerticesLengthCB(native_address, mVerticesLengthCB.native_address);
    }

    public static void internal_native_set_mVerticesLengthCB(long this_addr, long mVerticesLengthCB_addr) {
        try {
            FFMHandles.internal_native_set_mVerticesLengthCB__JJ.invokeExact(this_addr, mVerticesLengthCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mVerticesStrandFractionCB() {
        long addr = internal_native_get_mVerticesStrandFractionCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_9 == null)
            ComputeBuffer_TEMP_GEN_9 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_9.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_9;
    }

    public static long internal_native_get_mVerticesStrandFractionCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mVerticesStrandFractionCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mVerticesStrandFractionCB(ComputeBuffer mVerticesStrandFractionCB) {
        internal_native_set_mVerticesStrandFractionCB(native_address, mVerticesStrandFractionCB.native_address);
    }

    public static void internal_native_set_mVerticesStrandFractionCB(long this_addr, long mVerticesStrandFractionCB_addr) {
        try {
            FFMHandles.internal_native_set_mVerticesStrandFractionCB__JJ.invokeExact(this_addr, mVerticesStrandFractionCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mStrandVertexCountsCB() {
        long addr = internal_native_get_mStrandVertexCountsCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_10 == null)
            ComputeBuffer_TEMP_GEN_10 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_10.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_10;
    }

    public static long internal_native_get_mStrandVertexCountsCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mStrandVertexCountsCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mStrandVertexCountsCB(ComputeBuffer mStrandVertexCountsCB) {
        internal_native_set_mStrandVertexCountsCB(native_address, mStrandVertexCountsCB.native_address);
    }

    public static void internal_native_set_mStrandVertexCountsCB(long this_addr, long mStrandVertexCountsCB_addr) {
        try {
            FFMHandles.internal_native_set_mStrandVertexCountsCB__JJ.invokeExact(this_addr, mStrandVertexCountsCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mStrandMaterialIndexCB() {
        long addr = internal_native_get_mStrandMaterialIndexCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_11 == null)
            ComputeBuffer_TEMP_GEN_11 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_11.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_11;
    }

    public static long internal_native_get_mStrandMaterialIndexCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mStrandMaterialIndexCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mStrandMaterialIndexCB(ComputeBuffer mStrandMaterialIndexCB) {
        internal_native_set_mStrandMaterialIndexCB(native_address, mStrandMaterialIndexCB.native_address);
    }

    public static void internal_native_set_mStrandMaterialIndexCB(long this_addr, long mStrandMaterialIndexCB_addr) {
        try {
            FFMHandles.internal_native_set_mStrandMaterialIndexCB__JJ.invokeExact(this_addr, mStrandMaterialIndexCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mNeutralDensityCB() {
        long addr = internal_native_get_mNeutralDensityCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_12 == null)
            ComputeBuffer_TEMP_GEN_12 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_12.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_12;
    }

    public static long internal_native_get_mNeutralDensityCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mNeutralDensityCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mNeutralDensityCB(ComputeBuffer mNeutralDensityCB) {
        internal_native_set_mNeutralDensityCB(native_address, mNeutralDensityCB.native_address);
    }

    public static void internal_native_set_mNeutralDensityCB(long this_addr, long mNeutralDensityCB_addr) {
        try {
            FFMHandles.internal_native_set_mNeutralDensityCB__JJ.invokeExact(this_addr, mNeutralDensityCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeBuffer get_mSVertexInfluencesCB() {
        long addr = internal_native_get_mSVertexInfluencesCB_addr(native_address);
        if (addr == 0)
            return ComputeBuffer.NULL;
        if (ComputeBuffer_TEMP_GEN_13 == null)
            ComputeBuffer_TEMP_GEN_13 = ComputeBuffer.native_new();
        ComputeBuffer_TEMP_GEN_13.internal_reset(addr, false);
        return ComputeBuffer_TEMP_GEN_13;
    }

    public static long internal_native_get_mSVertexInfluencesCB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mSVertexInfluencesCB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mSVertexInfluencesCB(ComputeBuffer mSVertexInfluencesCB) {
        internal_native_set_mSVertexInfluencesCB(native_address, mSVertexInfluencesCB.native_address);
    }

    public static void internal_native_set_mSVertexInfluencesCB(long this_addr, long mSVertexInfluencesCB_addr) {
        try {
            FFMHandles.internal_native_set_mSVertexInfluencesCB__JJ.invokeExact(this_addr, mSVertexInfluencesCB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetRefCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_getrefcount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_AddRef__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_addref", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Release__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_release", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_InitRenderAndSimulationStrands__JJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_initrenderandsimulationstrands", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_sResample__JJI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_sresample", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_InitCompute__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_initcompute", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetNeutralDensity__JIII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_getneutraldensity", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetNumVerticesPadded__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_getnumverticespadded", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_PrepareForScalpSkinning__JJJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_prepareforscalpskinning", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SkinScalpVertices__JJJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_skinscalpvertices", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SaveBinaryState__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_savebinarystate", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_RestoreBinaryState__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_restorebinarystate", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_cNoInfluence__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_cnoinfluence", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_cDefaultIterationsPerSecond__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_cdefaultiterationspersecond", FunctionDescriptor.of(ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_mSimVertices_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_msimvertices_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mSimVertices__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_msimvertices", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mSimStrands_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_msimstrands_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mSimStrands__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_msimstrands", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mRenderVertices_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mrendervertices_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mRenderVertices__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mrendervertices", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mRenderStrands_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mrenderstrands_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mRenderStrands__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mrenderstrands", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mScalpVertices_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mscalpvertices_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mScalpVertices__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mscalpvertices", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mScalpTriangles_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mscalptriangles_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mScalpTriangles__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mscalptriangles", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mScalpInverseBindPose_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mscalpinversebindpose_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mScalpInverseBindPose__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mscalpinversebindpose", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mScalpSkinWeights_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mscalpskinweights_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mScalpSkinWeights__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mscalpskinweights", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mScalpNumSkinWeightsPerVertex__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mscalpnumskinweightspervertex", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mScalpNumSkinWeightsPerVertex__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mscalpnumskinweightspervertex", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_mNumIterationsPerSecond__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mnumiterationspersecond", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mNumIterationsPerSecond__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mnumiterationspersecond", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_mMaxDeltaTime__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mmaxdeltatime", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mMaxDeltaTime__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mmaxdeltatime", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_mGridSize_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mgridsize_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mGridSize__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mgridsize", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mSimulationBoundsPadding_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_msimulationboundspadding_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mSimulationBoundsPadding__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_msimulationboundspadding", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mInitialGravity_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_minitialgravity_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mInitialGravity__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_minitialgravity", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mMaterials_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mmaterials_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mMaterials__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mmaterials", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mSkinPoints_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mskinpoints_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mSkinPoints__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mskinpoints", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mSimulationBounds_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_msimulationbounds_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mSimulationBounds__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_msimulationbounds", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mNeutralDensity_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mneutraldensity_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mNeutralDensity__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mneutraldensity", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mDensityScale__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mdensityscale", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mDensityScale__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mdensityscale", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_mMaxVerticesPerStrand__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mmaxverticesperstrand", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mMaxVerticesPerStrand__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mmaxverticesperstrand", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_mScalpVerticesCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mscalpverticescb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mScalpVerticesCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mscalpverticescb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mScalpTrianglesCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mscalptrianglescb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mScalpTrianglesCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mscalptrianglescb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mScalpSkinWeightsCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mscalpskinweightscb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mScalpSkinWeightsCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mscalpskinweightscb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mSkinPointsCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mskinpointscb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mSkinPointsCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mskinpointscb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mVerticesFixedCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mverticesfixedcb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mVerticesFixedCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mverticesfixedcb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mVerticesPositionCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mverticespositioncb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mVerticesPositionCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mverticespositioncb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mVerticesBishopCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mverticesbishopcb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mVerticesBishopCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mverticesbishopcb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mVerticesOmega0CB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mverticesomega0cb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mVerticesOmega0CB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mverticesomega0cb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mVerticesLengthCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mverticeslengthcb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mVerticesLengthCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mverticeslengthcb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mVerticesStrandFractionCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mverticesstrandfractioncb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mVerticesStrandFractionCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mverticesstrandfractioncb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mStrandVertexCountsCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mstrandvertexcountscb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mStrandVertexCountsCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mstrandvertexcountscb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mStrandMaterialIndexCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mstrandmaterialindexcb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mStrandMaterialIndexCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mstrandmaterialindexcb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mNeutralDensityCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_mneutraldensitycb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mNeutralDensityCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_mneutraldensitycb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mSVertexInfluencesCB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_get_msvertexinfluencescb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mSVertexInfluencesCB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettings_set_msvertexinfluencescb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
