/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.hair;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.Float3;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class HairSettingsSVertexInfluence extends NativeObject {

    private Float3 Float3_TEMP_GEN_0;

    static public final HairSettingsSVertexInfluence NULL = HairSettingsSVertexInfluence.native_new();

    public HairSettingsSVertexInfluence() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected HairSettingsSVertexInfluence(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static HairSettingsSVertexInfluence native_new() {
        return new HairSettingsSVertexInfluence((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_mVertexIndex() {
        return internal_native_get_mVertexIndex(native_address);
    }

    public static int internal_native_get_mVertexIndex(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_get_mVertexIndex__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mVertexIndex(int mVertexIndex) {
        internal_native_set_mVertexIndex(native_address, mVertexIndex);
    }

    public static void internal_native_set_mVertexIndex(long this_addr, int mVertexIndex) {
        try {
            FFMHandles.internal_native_set_mVertexIndex__JI.invokeExact(this_addr, mVertexIndex);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Float3 get_mRelativePosition() {
        long addr = internal_native_get_mRelativePosition_addr(native_address);
        if (addr == 0)
            return Float3.NULL;
        if (Float3_TEMP_GEN_0 == null)
            Float3_TEMP_GEN_0 = Float3.native_new();
        Float3_TEMP_GEN_0.internal_reset(addr, false);
        return Float3_TEMP_GEN_0;
    }

    public static long internal_native_get_mRelativePosition_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mRelativePosition_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mRelativePosition(Float3 mRelativePosition) {
        internal_native_set_mRelativePosition(native_address, mRelativePosition.native_address);
    }

    public static void internal_native_set_mRelativePosition(long this_addr, long mRelativePosition_addr) {
        try {
            FFMHandles.internal_native_set_mRelativePosition__JJ.invokeExact(this_addr, mRelativePosition_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mWeight() {
        return internal_native_get_mWeight(native_address);
    }

    public static float internal_native_get_mWeight(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mWeight__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mWeight(float mWeight) {
        internal_native_set_mWeight(native_address, mWeight);
    }

    public static void internal_native_set_mWeight(long this_addr, float mWeight) {
        try {
            FFMHandles.internal_native_set_mWeight__JF.invokeExact(this_addr, mWeight);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingssvertexinfluence_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingssvertexinfluence_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mVertexIndex__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingssvertexinfluence_get_mvertexindex", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mVertexIndex__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingssvertexinfluence_set_mvertexindex", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_mRelativePosition_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingssvertexinfluence_get_mrelativeposition_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mRelativePosition__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingssvertexinfluence_set_mrelativeposition", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mWeight__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingssvertexinfluence_get_mweight", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mWeight__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingssvertexinfluence_set_mweight", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));
    }
}
