/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.hair;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.Float3;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class HairSettingsRVertex extends NativeObject {

    private Float3 Float3_TEMP_GEN_0;

    private HairSettingsSVertexInfluence HairSettingsSVertexInfluence_TEMP_GEN_0;

    static public final HairSettingsRVertex NULL = HairSettingsRVertex.native_new();

    public HairSettingsRVertex() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected HairSettingsRVertex(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static HairSettingsRVertex native_new() {
        return new HairSettingsRVertex((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Float3 get_mPosition() {
        long addr = internal_native_get_mPosition_addr(native_address);
        if (addr == 0)
            return Float3.NULL;
        if (Float3_TEMP_GEN_0 == null)
            Float3_TEMP_GEN_0 = Float3.native_new();
        Float3_TEMP_GEN_0.internal_reset(addr, false);
        return Float3_TEMP_GEN_0;
    }

    public static long internal_native_get_mPosition_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mPosition_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mPosition(Float3 mPosition) {
        internal_native_set_mPosition(native_address, mPosition.native_address);
    }

    public static void internal_native_set_mPosition(long this_addr, long mPosition_addr) {
        try {
            FFMHandles.internal_native_set_mPosition__JJ.invokeExact(this_addr, mPosition_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public HairSettingsSVertexInfluence get_mInfluences(int index) {
        long addr = internal_native_get_mInfluences_addr(native_address, index);
        if (addr == 0)
            return HairSettingsSVertexInfluence.NULL;
        if (HairSettingsSVertexInfluence_TEMP_GEN_0 == null)
            HairSettingsSVertexInfluence_TEMP_GEN_0 = HairSettingsSVertexInfluence.native_new();
        HairSettingsSVertexInfluence_TEMP_GEN_0.internal_reset(addr, false);
        return HairSettingsSVertexInfluence_TEMP_GEN_0;
    }

    public static long internal_native_get_mInfluences_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_get_mInfluences_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mInfluences(int index, HairSettingsSVertexInfluence mInfluences) {
        internal_native_set_mInfluences(native_address, index, mInfluences.native_address);
    }

    public static void internal_native_set_mInfluences(long this_addr, int index, long mInfluences_addr) {
        try {
            FFMHandles.internal_native_set_mInfluences__JIJ.invokeExact(this_addr, index, mInfluences_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingsrvertex_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingsrvertex_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mPosition_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingsrvertex_get_mposition_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mPosition__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingsrvertex_set_mposition", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mInfluences_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingsrvertex_get_minfluences_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_set_mInfluences__JIJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_hair_hairsettingsrvertex_set_minfluences", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
    }
}
