/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.compute;

import com.github.xpenatan.jParser.api.NativeObject;
import com.github.xpenatan.jparser.runtime.helper.NativeString;
import jolt.math.ArrayUint8;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class ComputeShaderLoader extends NativeObject {

    static private NativeString NativeString_TEMP_STATIC_GEN_0;

    static private ArrayUint8 ArrayUint8_TEMP_STATIC_GEN_0;

    static private NativeString NativeString_TEMP_STATIC_GEN_1;

    private static final java.lang.invoke.MethodHandles.Lookup callbackLookup = java.lang.invoke.MethodHandles.lookup();

    private static final java.lang.foreign.Linker callbackLinker = java.lang.foreign.Linker.nativeLinker();

    private static final java.lang.invoke.MethodType callbackMethodType_Load = java.lang.invoke.MethodType.methodType(boolean.class, long.class, long.class, long.class);

    private static final java.lang.foreign.FunctionDescriptor callbackDescriptor_Load = java.lang.foreign.FunctionDescriptor.of(java.lang.foreign.ValueLayout.JAVA_BOOLEAN, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG, java.lang.foreign.ValueLayout.JAVA_LONG);

    static public final ComputeShaderLoader NULL = ComputeShaderLoader.native_new();

    @Deprecated()
    protected ComputeShaderLoader(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ComputeShaderLoader native_new() {
        return new ComputeShaderLoader((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
        releaseUpcallResources();
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public ComputeShaderLoader() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        try {
            releaseUpcallResources();
            upcallArena = java.lang.foreign.Arena.ofShared();
            java.lang.invoke.MethodHandle mh_Load = callbackLookup.findVirtual(ComputeShaderLoader.class, "internal_Load", callbackMethodType_Load).bindTo(this);
            upcallStub_Load = callbackLinker.upcallStub(mh_Load, callbackDescriptor_Load, upcallArena);
            internal_native_setupCallback(native_address, upcallStub_Load.address());
        } catch (Throwable e) {
            throw new RuntimeException(e);
        }
    }

    protected boolean Load(NativeString inName, ArrayUint8 outData, NativeString outError) {
        return false;
    }

    private boolean internal_Load(long inName_addr, long outData_addr, long outError_addr) {
        if (NativeString_TEMP_STATIC_GEN_0 == null)
            NativeString_TEMP_STATIC_GEN_0 = NativeString.native_new();
        NativeString_TEMP_STATIC_GEN_0.internal_reset(inName_addr, false);
        if (ArrayUint8_TEMP_STATIC_GEN_0 == null)
            ArrayUint8_TEMP_STATIC_GEN_0 = ArrayUint8.native_new();
        ArrayUint8_TEMP_STATIC_GEN_0.internal_reset(outData_addr, false);
        if (NativeString_TEMP_STATIC_GEN_1 == null)
            NativeString_TEMP_STATIC_GEN_1 = NativeString.native_new();
        NativeString_TEMP_STATIC_GEN_1.internal_reset(outError_addr, false);
        return Load(NativeString_TEMP_STATIC_GEN_0, ArrayUint8_TEMP_STATIC_GEN_0, NativeString_TEMP_STATIC_GEN_1);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private Arena upcallArena;

    private MemorySegment upcallStub_Load;

    private void releaseUpcallResources() {
        Arena arena = upcallArena;
        upcallStub_Load = null;
        upcallArena = null;
        if (arena != null) {
            try {
                arena.close();
            } catch (Exception ignored) {
            }
        }
    }

    public static void internal_native_setupCallback(long this_addr, long Load_fp) {
        try {
            FFMHandles.internal_native_setupCallback__JJ.invokeExact(this_addr, Load_fp);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_compute_computeshaderloader_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_compute_computeshaderloader_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_setupCallback__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_compute_computeshaderloader_setupcallback", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
