/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

import jolt.physics.PhysicsStepListener;

public final class VehicleConstraintStepListener extends PhysicsStepListener {

    static public final VehicleConstraintStepListener NULL = VehicleConstraintStepListener.native_new();

    public VehicleConstraintStepListener(VehicleConstraint inConstraint) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_VehicleConstraint_addr(inConstraint.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_VehicleConstraint_addr(long inConstraint_addr) {
        return jolt.physics.vehicle.natives.JNI_VehicleConstraintStepListener.internal_native_create_VehicleConstraint_addr(inConstraint_addr);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleConstraintStepListener(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleConstraintStepListener native_new() {
        return new VehicleConstraintStepListener((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.vehicle.natives.JNI_VehicleConstraintStepListener.internal_native_deleteNative(this_addr);
    }
}
