/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.vehicle;

public final class VehicleCollisionTesterCastCylinder extends VehicleCollisionTester {

    static public final VehicleCollisionTesterCastCylinder NULL = VehicleCollisionTesterCastCylinder.native_new();

    public VehicleCollisionTesterCastCylinder(int inObjectLayer, float inConvexRadiusFraction) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_int_float_addr(inObjectLayer, inConvexRadiusFraction);
        internal_reset(addr, true);
    }

    public static long internal_native_create_int_float_addr(int inObjectLayer, float inConvexRadiusFraction) {
        return jolt.physics.vehicle.natives.JNI_VehicleCollisionTesterCastCylinder.internal_native_create_int_float_addr(inObjectLayer, inConvexRadiusFraction);
    }

    public VehicleCollisionTesterCastCylinder(int inObjectLayer) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_int_addr(inObjectLayer);
        internal_reset(addr, true);
    }

    public static long internal_native_create_int_addr(int inObjectLayer) {
        return jolt.physics.vehicle.natives.JNI_VehicleCollisionTesterCastCylinder.internal_native_create_int_addr(inObjectLayer);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VehicleCollisionTesterCastCylinder(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static VehicleCollisionTesterCastCylinder native_new() {
        return new VehicleCollisionTesterCastCylinder((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.vehicle.natives.JNI_VehicleCollisionTesterCastCylinder.internal_native_deleteNative(this_addr);
    }
}
