/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.hair.natives;

import jolt.physics.hair.*;

final public class JNI_HairSettingsSVertex {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_Float3_float_addr(long inPosition_addr, float inInvMass);

    public static native long internal_native_create_Float3_addr(long inPosition_addr);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_get_mPosition_addr(long this_addr);

    public static native void internal_native_set_mPosition(long this_addr, long mPosition_addr);

    public static native float internal_native_get_mInvMass(long this_addr);

    public static native void internal_native_set_mInvMass(long this_addr, float mInvMass);

    public static native float internal_native_get_mLength(long this_addr);

    public static native void internal_native_set_mLength(long this_addr, float mLength);

    public static native float internal_native_get_mStrandFraction(long this_addr);

    public static native void internal_native_set_mStrandFraction(long this_addr, float mStrandFraction);

    public static native long internal_native_get_mBishop_addr(long this_addr);

    public static native void internal_native_set_mBishop(long this_addr, long mBishop_addr);

    public static native long internal_native_get_mOmega0_addr(long this_addr);

    public static native void internal_native_set_mOmega0(long this_addr, long mOmega0_addr);
}
