/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.softbody;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.Vec3;
import jolt.physics.body.BodyID;

public final class SoftBodyManifold extends NativeObject {

    static public final SoftBodyManifold NULL = SoftBodyManifold.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected SoftBodyManifold(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static SoftBodyManifold native_new() {
        return new SoftBodyManifold((byte) 0, (char) 0);
    }

    public ArraySoftBodyVertex GetVertices() {
        return null;
    }

    public boolean HasContact(SoftBodyVertex inVertex) {
        return false;
    }

    public Vec3 GetLocalContactPoint(SoftBodyVertex inVertex) {
        return null;
    }

    public Vec3 GetContactNormal(SoftBodyVertex inVertex) {
        return null;
    }

    public BodyID GetContactBodyID(SoftBodyVertex inVertex) {
        return null;
    }

    public int GetNumSensorContacts() {
        return 0;
    }

    public BodyID GetSensorContactBodyID(int inIndex) {
        return null;
    }
}
