/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.softbody;

import com.github.xpenatan.jParser.api.NativeObject;

public final class SoftBodySharedSettingsVolume extends NativeObject {

    static public final SoftBodySharedSettingsVolume NULL = SoftBodySharedSettingsVolume.native_new();

    public SoftBodySharedSettingsVolume(int inVertex1, int inVertex2, int inVertex3, int inVertex4, float inCompliance) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected SoftBodySharedSettingsVolume(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static SoftBodySharedSettingsVolume native_new() {
        return new SoftBodySharedSettingsVolume((byte) 0, (char) 0);
    }

    public int get_mVertex(int index) {
        return 0;
    }

    public void set_mVertex(int index, int mVertex) {
    }

    public float get_mSixRestVolume() {
        return 0;
    }

    public void set_mSixRestVolume(float mSixRestVolume) {
    }

    public float get_mCompliance() {
        return 0;
    }

    public void set_mCompliance(float mCompliance) {
    }
}
