/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.softbody;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.body.BodyID;
import jolt.geometry.Plane;
import jolt.math.Vec3;

public final class SoftBodyVertex extends NativeObject {

    static public final SoftBodyVertex NULL = SoftBodyVertex.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected SoftBodyVertex(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static SoftBodyVertex native_new() {
        return new SoftBodyVertex((byte) 0, (char) 0);
    }

    public void MarkCCDContact(BodyID inBodyID, Plane inContactPlane) {
    }

    public Vec3 get_mPreviousPosition() {
        return null;
    }

    public void set_mPreviousPosition(Vec3 mPreviousPosition) {
    }

    public Vec3 get_mPosition() {
        return null;
    }

    public void set_mPosition(Vec3 mPosition) {
    }

    public Vec3 get_mVelocity() {
        return null;
    }

    public void set_mVelocity(Vec3 mVelocity) {
    }

    public float get_mInvMass() {
        return 0;
    }

    public void set_mInvMass(float mInvMass) {
    }
}
