[versions]
projectGroup = "com.github.xpenatan.jJolt"
projectName = "jJolt"
jJoltRelease = "5.6.0.0"
jJoltSnapshot = "-SNAPSHOT"
joltSource = "5.6.0"

javaMainTarget = "1.8"
javaWebTarget = "17"
javaFfmTarget = "25"

jParser = "-SNAPSHOT"
libfdx = "-SNAPSHOT"
libgdx = "1.14.2"

gdxTeavmVersion = "-SNAPSHOT"
gdxImguiVersion = "1.92.4.0"
junitVersion = "4.12"
useRepoLibs = "false"
exampleVersion = "-SNAPSHOT"

easyPublishingVersion = "0.1.1"
androidGradlePluginVersion = "9.1.1"
androidxTestJunitVersion = "1.2.1"
androidxTestRunnerVersion = "1.6.2"
androidDesugarVersion = "2.0.3"
gdxGltfVersion = "2.2.1"

[plugins]
easyPublishing = { id = "com.github.xpenatan.easy-publishing", version.ref = "easyPublishingVersion" }
androidApplication = { id = "com.android.application", version.ref = "androidGradlePluginVersion" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePluginVersion" }
jparser = { id = "com.github.xpenatan.jparser", version.ref = "jParser" }
libfdx = { id = "io.github.libfdx", version.ref = "libfdx" }

[libraries]
jparserApiCore = { module = "com.github.xpenatan.jParser:api-core", version.ref = "jParser" }
jparserApiWeb = { module = "com.github.xpenatan.jParser:api-web", version.ref = "jParser" }
jparserLoaderC = { module = "com.github.xpenatan.jParser:loader-c", version.ref = "jParser" }
jparserLoaderCore = { module = "com.github.xpenatan.jParser:loader-core", version.ref = "jParser" }
jparserLoaderWeb = { module = "com.github.xpenatan.jParser:loader-web", version.ref = "jParser" }
jparserRuntimeAndroid = { module = "com.github.xpenatan.jParser:runtime-android", version.ref = "jParser" }
jparserRuntimeBase = { module = "com.github.xpenatan.jParser:runtime-base", version.ref = "jParser" }
jparserRuntimeC = { module = "com.github.xpenatan.jParser:runtime-c", version.ref = "jParser" }
jparserRuntimeCore = { module = "com.github.xpenatan.jParser:runtime-core", version.ref = "jParser" }
jparserRuntimeJni = { module = "com.github.xpenatan.jParser:runtime-jni", version.ref = "jParser" }
jparserRuntimeWeb = { module = "com.github.xpenatan.jParser:runtime-web", version.ref = "jParser" }
jparserRuntimeWebWasm = { module = "com.github.xpenatan.jParser:runtime-web_wasm", version.ref = "jParser" }
jparserRuntimeDesktopCWindowsX64 = { module = "com.github.xpenatan.jParser:runtime-desktop-c_windows_x64", version.ref = "jParser" }
jparserRuntimeDesktopCLinuxX64 = { module = "com.github.xpenatan.jParser:runtime-desktop-c_linux_x64", version.ref = "jParser" }
jparserRuntimeDesktopCMacX64 = { module = "com.github.xpenatan.jParser:runtime-desktop-c_mac_x64", version.ref = "jParser" }
jparserRuntimeDesktopCMacArm64 = { module = "com.github.xpenatan.jParser:runtime-desktop-c_mac_arm64", version.ref = "jParser" }
jparserRuntimeDesktopJni = { module = "com.github.xpenatan.jParser:runtime-desktop-jni", version.ref = "jParser" }
jparserRuntimeDesktopJniWindowsX64 = { module = "com.github.xpenatan.jParser:runtime-desktop-jni_windows_x64", version.ref = "jParser" }
jparserRuntimeDesktopJniLinuxX64 = { module = "com.github.xpenatan.jParser:runtime-desktop-jni_linux_x64", version.ref = "jParser" }
jparserRuntimeDesktopJniMacX64 = { module = "com.github.xpenatan.jParser:runtime-desktop-jni_mac_x64", version.ref = "jParser" }
jparserRuntimeDesktopJniMacArm64 = { module = "com.github.xpenatan.jParser:runtime-desktop-jni_mac_arm64", version.ref = "jParser" }
jparserRuntimeDesktopFfm = { module = "com.github.xpenatan.jParser:runtime-desktop-ffm", version.ref = "jParser" }
jparserRuntimeDesktopFfmWindowsX64 = { module = "com.github.xpenatan.jParser:runtime-desktop-ffm_windows_x64", version.ref = "jParser" }
jparserRuntimeDesktopFfmLinuxX64 = { module = "com.github.xpenatan.jParser:runtime-desktop-ffm_linux_x64", version.ref = "jParser" }
jparserRuntimeDesktopFfmMacX64 = { module = "com.github.xpenatan.jParser:runtime-desktop-ffm_mac_x64", version.ref = "jParser" }
jparserRuntimeDesktopFfmMacArm64 = { module = "com.github.xpenatan.jParser:runtime-desktop-ffm_mac_arm64", version.ref = "jParser" }

fdxApplication = { module = "io.github.libfdx:application", version.ref = "libfdx" }
fdxAssetManager = { module = "io.github.libfdx:asset_manager", version.ref = "libfdx" }
fdxBackendAndroid = { module = "io.github.libfdx:backend_android", version.ref = "libfdx" }
fdxBackendDesktop = { module = "io.github.libfdx:backend_desktop", version.ref = "libfdx" }
fdxBackendWeb = { module = "io.github.libfdx:backend_web", version.ref = "libfdx" }
fdxDisplay = { module = "io.github.libfdx:display", version.ref = "libfdx" }
fdxG3d = { module = "io.github.libfdx:g3d", version.ref = "libfdx" }
fdxGlDesktop = { module = "io.github.libfdx:gl_desktop", version.ref = "libfdx" }
fdxGlWeb = { module = "io.github.libfdx:gl_web", version.ref = "libfdx" }
fdxGraphics = { module = "io.github.libfdx:graphics", version.ref = "libfdx" }
fdxVulkanAndroidJni = { module = "io.github.libfdx:vulkan_android_jni", version.ref = "libfdx" }
fdxVulkanDesktop = { module = "io.github.libfdx:vulkan_desktop", version.ref = "libfdx" }
fdxWgpuAndroidJni = { module = "io.github.libfdx:wgpu_android_jni", version.ref = "libfdx" }
fdxWgpuCore = { module = "io.github.libfdx:wgpu_core", version.ref = "libfdx" }
fdxWgpuDesktopFfm = { module = "io.github.libfdx:wgpu_desktop_ffm", version.ref = "libfdx" }
fdxWgpuDesktopJni = { module = "io.github.libfdx:wgpu_desktop_jni", version.ref = "libfdx" }
fdxWgpuWeb = { module = "io.github.libfdx:wgpu_web", version.ref = "libfdx" }

gdxCore = { module = "com.badlogicgames.gdx:gdx", version.ref = "libgdx" }
gdxBackendAndroid = { module = "com.badlogicgames.gdx:gdx-backend-android", version.ref = "libgdx" }
gdxBackendLwjgl3 = { module = "com.badlogicgames.gdx:gdx-backend-lwjgl3", version.ref = "libgdx" }
gdxPlatform = { module = "com.badlogicgames.gdx:gdx-platform", version.ref = "libgdx" }
gdxTeavmBackendGlfw = { module = "com.github.xpenatan.gdx-teavm:backend-glfw", version.ref = "gdxTeavmVersion" }
gdxTeavmBackendWeb = { module = "com.github.xpenatan.gdx-teavm:backend-web", version.ref = "gdxTeavmVersion" }
gdxGltfCore = { module = "com.github.mgsx-dev.gdx-gltf:core", version.ref = "gdxGltfVersion" }

imguiCore = { module = "com.github.xpenatan.xImGui:imgui-core", version.ref = "gdxImguiVersion" }
imguiDesktop = { module = "com.github.xpenatan.xImGui:imgui-desktop", version.ref = "gdxImguiVersion" }
imguiGdxGl = { module = "com.github.xpenatan.xImGui:gdx-gl-impl", version.ref = "gdxImguiVersion" }
imguiGdxShared = { module = "com.github.xpenatan.xImGui:gdx-shared-impl", version.ref = "gdxImguiVersion" }

jjoltAndroidJni = { module = "com.github.xpenatan.jJolt:android-jni", version.ref = "exampleVersion" }
jjoltCore = { module = "com.github.xpenatan.jJolt:core", version.ref = "exampleVersion" }
jjoltDesktopFfm = { module = "com.github.xpenatan.jJolt:desktop-ffm", version.ref = "exampleVersion" }
jjoltDesktopJni = { module = "com.github.xpenatan.jJolt:desktop-jni", version.ref = "exampleVersion" }
jjoltGdxGl = { module = "com.github.xpenatan.jJolt:gdx-gl", version.ref = "exampleVersion" }
jjoltJoltFdx = { module = "com.github.xpenatan.jJolt:jolt-fdx", version.ref = "exampleVersion" }
jjoltWebWasm = { module = "com.github.xpenatan.jJolt:web-wasm", version.ref = "exampleVersion" }

androidDesugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "androidDesugarVersion" }
androidxTestJunit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunitVersion" }
androidxTestRunner = { module = "androidx.test:runner", version.ref = "androidxTestRunnerVersion" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
