/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.body;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.collision.shape.Shape;
import jolt.math.Vec3;
import jolt.math.Quat;
import jolt.enums.EMotionType;
import jolt.physics.collision.shape.ShapeSettings;
import jolt.physics.collision.shape.ShapeResult;
import jolt.physics.collision.CollisionGroup;
import jolt.enums.EAllowedDOFs;
import jolt.enums.EMotionQuality;
import jolt.enums.EOverrideMassProperties;

public class BodyCreationSettings extends NativeObject {

    static public final BodyCreationSettings NULL = BodyCreationSettings.native_new();

    public BodyCreationSettings() {
    }

    public BodyCreationSettings(Shape inShape, Vec3 inPosition, Quat inRotation, EMotionType inMotionType, int inObjectLayer) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected BodyCreationSettings(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static BodyCreationSettings native_new() {
        return new BodyCreationSettings((byte) 0, (char) 0);
    }

    public boolean Equals(BodyCreationSettings inRHS) {
        return false;
    }

    public boolean NotEquals(BodyCreationSettings inRHS) {
        return false;
    }

    public ShapeSettings GetShapeSettings() {
        return null;
    }

    public void SetShapeSettings(ShapeSettings inShape) {
    }

    public ShapeResult ConvertShapeSettings() {
        return null;
    }

    public Shape GetShape() {
        return null;
    }

    public void SetShape(Shape inShape) {
    }

    public boolean HasMassProperties() {
        return false;
    }

    public MassProperties GetMassProperties() {
        return null;
    }

    public Vec3 get_mPosition() {
        return null;
    }

    public void set_mPosition(Vec3 mPosition) {
    }

    public Quat get_mRotation() {
        return null;
    }

    public void set_mRotation(Quat mRotation) {
    }

    public Vec3 get_mLinearVelocity() {
        return null;
    }

    public void set_mLinearVelocity(Vec3 mLinearVelocity) {
    }

    public Vec3 get_mAngularVelocity() {
        return null;
    }

    public void set_mAngularVelocity(Vec3 mAngularVelocity) {
    }

    public long get_mUserData() {
        return 0;
    }

    public void set_mUserData(long mUserData) {
    }

    public int get_mObjectLayer() {
        return 0;
    }

    public void set_mObjectLayer(int mObjectLayer) {
    }

    public CollisionGroup get_mCollisionGroup() {
        return null;
    }

    public void set_mCollisionGroup(CollisionGroup mCollisionGroup) {
    }

    public EMotionType get_mMotionType() {
        return null;
    }

    public void set_mMotionType(EMotionType mMotionType) {
    }

    public EAllowedDOFs get_mAllowedDOFs() {
        return null;
    }

    public void set_mAllowedDOFs(EAllowedDOFs mAllowedDOFs) {
    }

    public boolean get_mAllowDynamicOrKinematic() {
        return false;
    }

    public void set_mAllowDynamicOrKinematic(boolean mAllowDynamicOrKinematic) {
    }

    public boolean get_mIsSensor() {
        return false;
    }

    public void set_mIsSensor(boolean mIsSensor) {
    }

    public boolean get_mUseManifoldReduction() {
        return false;
    }

    public void set_mUseManifoldReduction(boolean mUseManifoldReduction) {
    }

    public boolean get_mCollideKinematicVsNonDynamic() {
        return false;
    }

    public void set_mCollideKinematicVsNonDynamic(boolean mCollideKinematicVsNonDynamic) {
    }

    public boolean get_mApplyGyroscopicForce() {
        return false;
    }

    public void set_mApplyGyroscopicForce(boolean mApplyGyroscopicForce) {
    }

    public EMotionQuality get_mMotionQuality() {
        return null;
    }

    public void set_mMotionQuality(EMotionQuality mMotionQuality) {
    }

    public boolean get_mEnhancedInternalEdgeRemoval() {
        return false;
    }

    public void set_mEnhancedInternalEdgeRemoval(boolean mEnhancedInternalEdgeRemoval) {
    }

    public boolean get_mAllowSleeping() {
        return false;
    }

    public void set_mAllowSleeping(boolean mAllowSleeping) {
    }

    public float get_mFriction() {
        return 0;
    }

    public void set_mFriction(float mFriction) {
    }

    public float get_mRestitution() {
        return 0;
    }

    public void set_mRestitution(float mRestitution) {
    }

    public float get_mLinearDamping() {
        return 0;
    }

    public void set_mLinearDamping(float mLinearDamping) {
    }

    public float get_mAngularDamping() {
        return 0;
    }

    public void set_mAngularDamping(float mAngularDamping) {
    }

    public float get_mMaxLinearVelocity() {
        return 0;
    }

    public void set_mMaxLinearVelocity(float mMaxLinearVelocity) {
    }

    public float get_mMaxAngularVelocity() {
        return 0;
    }

    public void set_mMaxAngularVelocity(float mMaxAngularVelocity) {
    }

    public float get_mGravityFactor() {
        return 0;
    }

    public void set_mGravityFactor(float mGravityFactor) {
    }

    public int get_mNumVelocityStepsOverride() {
        return 0;
    }

    public void set_mNumVelocityStepsOverride(int mNumVelocityStepsOverride) {
    }

    public int get_mNumPositionStepsOverride() {
        return 0;
    }

    public void set_mNumPositionStepsOverride(int mNumPositionStepsOverride) {
    }

    public EOverrideMassProperties get_mOverrideMassProperties() {
        return null;
    }

    public void set_mOverrideMassProperties(EOverrideMassProperties mOverrideMassProperties) {
    }

    public float get_mInertiaMultiplier() {
        return 0;
    }

    public void set_mInertiaMultiplier(float mInertiaMultiplier) {
    }

    public MassProperties get_mMassPropertiesOverride() {
        return null;
    }

    public void set_mMassPropertiesOverride(MassProperties mMassPropertiesOverride) {
    }
}
