/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.compute;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ComputeShader extends NativeObject {

    static public final ComputeShader NULL = ComputeShader.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ComputeShader(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ComputeShader native_new() {
        return new ComputeShader((byte) 0, (char) 0);
    }

    public int GetRefCount() {
        return internal_native_GetRefCount(native_address);
    }

    public static int internal_native_GetRefCount(long this_addr) {
        return jolt.compute.natives.JNI_ComputeShader.internal_native_GetRefCount(this_addr);
    }

    public void AddRef() {
        internal_native_AddRef(native_address);
    }

    public static void internal_native_AddRef(long this_addr) {
        jolt.compute.natives.JNI_ComputeShader.internal_native_AddRef(this_addr);
    }

    public void Release() {
        internal_native_Release(native_address);
    }

    public static void internal_native_Release(long this_addr) {
        jolt.compute.natives.JNI_ComputeShader.internal_native_Release(this_addr);
    }

    public int GetGroupSizeX() {
        return internal_native_GetGroupSizeX(native_address);
    }

    public static int internal_native_GetGroupSizeX(long this_addr) {
        return jolt.compute.natives.JNI_ComputeShader.internal_native_GetGroupSizeX(this_addr);
    }

    public int GetGroupSizeY() {
        return internal_native_GetGroupSizeY(native_address);
    }

    public static int internal_native_GetGroupSizeY(long this_addr) {
        return jolt.compute.natives.JNI_ComputeShader.internal_native_GetGroupSizeY(this_addr);
    }

    public int GetGroupSizeZ() {
        return internal_native_GetGroupSizeZ(native_address);
    }

    public static int internal_native_GetGroupSizeZ(long this_addr) {
        return jolt.compute.natives.JNI_ComputeShader.internal_native_GetGroupSizeZ(this_addr);
    }
}
