/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.compute;

import com.github.xpenatan.jParser.api.NativeObject;
import com.github.xpenatan.jparser.runtime.helper.NativeString;

public final class ComputeShaderResult extends NativeObject {

    private NativeString NativeString_TEMP_GEN_0;

    private ComputeShader ComputeShader_TEMP_GEN_0;

    static public final ComputeShaderResult NULL = ComputeShaderResult.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ComputeShaderResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ComputeShaderResult native_new() {
        return new ComputeShaderResult((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.compute.natives.JNI_ComputeShaderResult.internal_native_deleteNative(this_addr);
    }

    public boolean IsValid() {
        return internal_native_IsValid(native_address);
    }

    public static boolean internal_native_IsValid(long this_addr) {
        return jolt.compute.natives.JNI_ComputeShaderResult.internal_native_IsValid(this_addr);
    }

    public boolean HasError() {
        return internal_native_HasError(native_address);
    }

    public static boolean internal_native_HasError(long this_addr) {
        return jolt.compute.natives.JNI_ComputeShaderResult.internal_native_HasError(this_addr);
    }

    public NativeString GetError() {
        long addr = internal_native_GetError_addr(native_address);
        if (addr == 0)
            return NativeString.NULL;
        if (NativeString_TEMP_GEN_0 == null)
            NativeString_TEMP_GEN_0 = NativeString.native_new();
        NativeString_TEMP_GEN_0.internal_reset(addr, false);
        return NativeString_TEMP_GEN_0;
    }

    public static long internal_native_GetError_addr(long this_addr) {
        return jolt.compute.natives.JNI_ComputeShaderResult.internal_native_GetError_addr(this_addr);
    }

    public ComputeShader Get() {
        long addr = internal_native_Get_addr(native_address);
        if (addr == 0)
            return ComputeShader.NULL;
        if (ComputeShader_TEMP_GEN_0 == null)
            ComputeShader_TEMP_GEN_0 = ComputeShader.native_new();
        ComputeShader_TEMP_GEN_0.internal_reset(addr, false);
        return ComputeShader_TEMP_GEN_0;
    }

    public static long internal_native_Get_addr(long this_addr) {
        return jolt.compute.natives.JNI_ComputeShaderResult.internal_native_Get_addr(this_addr);
    }

    public void Clear() {
        internal_native_Clear(native_address);
    }

    public static void internal_native_Clear(long this_addr) {
        jolt.compute.natives.JNI_ComputeShaderResult.internal_native_Clear(this_addr);
    }
}
