/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.softbody.natives;

import jolt.physics.softbody.*;

final public class JNI_SoftBodyMotionProperties {

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetSettings_addr(long this_addr);

    public static native long internal_native_GetVertices_addr(long this_addr);

    public static native long internal_native_GetVertex_addr(long this_addr, int inIndex);

    public static native long internal_native_GetRodRotation_addr(long this_addr, int inIndex);

    public static native long internal_native_GetRodAngularVelocity_addr(long this_addr, int inIndex);

    public static native long internal_native_GetMaterials_addr(long this_addr);

    public static native long internal_native_GetFaces_addr(long this_addr);

    public static native long internal_native_GetFace_addr(long this_addr, int inIndex);

    public static native int internal_native_GetNumIterations(long this_addr);

    public static native void internal_native_SetNumIterations(long this_addr, int inNumIterations);

    public static native float internal_native_GetPressure(long this_addr);

    public static native void internal_native_SetPressure(long this_addr, float inPressure);

    public static native boolean internal_native_GetUpdatePosition(long this_addr);

    public static native void internal_native_SetUpdatePosition(long this_addr, boolean inUpdatePosition);

    public static native boolean internal_native_GetEnableSkinConstraints(long this_addr);

    public static native void internal_native_SetEnableSkinConstraints(long this_addr, boolean inEnableSkinConstraints);

    public static native float internal_native_GetSkinnedMaxDistanceMultiplier(long this_addr);

    public static native void internal_native_SetSkinnedMaxDistanceMultiplier(long this_addr, float inSkinnedMaxDistanceMultiplier);

    public static native float internal_native_GetVertexRadius(long this_addr);

    public static native void internal_native_SetVertexRadius(long this_addr, float inVertexRadius);

    public static native long internal_native_GetLocalBounds_addr(long this_addr);

    public static native void internal_native_CustomUpdate(long this_addr, float inDeltaTime, long ioSoftBody_addr, long inSystem_addr);

    public static native void internal_native_SkinVertices(long this_addr, long inRootTransform_addr, long inJointMatrices_addr, int inNumJoints, boolean inHardSkinAll, long ioTempAllocator_addr);

    public static native void internal_native_RequestContactCallback(long this_addr);
}
