/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import jolt.physics.softbody.CastRayCollector;

public final class CastRayAnyHitCollisionCollector extends CastRayCollector {

    private RayCastResult RayCastResult_TEMP_GEN_0;

    static public final CastRayAnyHitCollisionCollector NULL = CastRayAnyHitCollisionCollector.native_new();

    public CastRayAnyHitCollisionCollector() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.collision.natives.JNI_CastRayAnyHitCollisionCollector.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CastRayAnyHitCollisionCollector(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static CastRayAnyHitCollisionCollector native_new() {
        return new CastRayAnyHitCollisionCollector((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.collision.natives.JNI_CastRayAnyHitCollisionCollector.internal_native_deleteNative(this_addr);
    }

    public boolean HadHit() {
        return internal_native_HadHit(native_address);
    }

    public static boolean internal_native_HadHit(long this_addr) {
        return jolt.physics.collision.natives.JNI_CastRayAnyHitCollisionCollector.internal_native_HadHit(this_addr);
    }

    public RayCastResult get_mHit() {
        long addr = internal_native_get_mHit_addr(native_address);
        if (addr == 0)
            return RayCastResult.NULL;
        if (RayCastResult_TEMP_GEN_0 == null)
            RayCastResult_TEMP_GEN_0 = RayCastResult.native_new();
        RayCastResult_TEMP_GEN_0.internal_reset(addr, false);
        return RayCastResult_TEMP_GEN_0;
    }

    public static long internal_native_get_mHit_addr(long this_addr) {
        return jolt.physics.collision.natives.JNI_CastRayAnyHitCollisionCollector.internal_native_get_mHit_addr(this_addr);
    }

    public void set_mHit(RayCastResult mHit) {
        internal_native_set_mHit(native_address, mHit.native_address);
    }

    public static void internal_native_set_mHit(long this_addr, long mHit_addr) {
        jolt.physics.collision.natives.JNI_CastRayAnyHitCollisionCollector.internal_native_set_mHit(this_addr, mHit_addr);
    }
}
