/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import jolt.physics.collision.shape.SubShapeID;

public final class RayCastResult extends BroadPhaseCastResult {

    private SubShapeID SubShapeID_TEMP_GEN_0;

    static public final RayCastResult NULL = RayCastResult.native_new();

    public RayCastResult() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.collision.natives.JNI_RayCastResult.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected RayCastResult(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static RayCastResult native_new() {
        return new RayCastResult((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.collision.natives.JNI_RayCastResult.internal_native_deleteNative(this_addr);
    }

    public SubShapeID get_mSubShapeID2() {
        long addr = internal_native_get_mSubShapeID2_addr(native_address);
        if (addr == 0)
            return SubShapeID.NULL;
        if (SubShapeID_TEMP_GEN_0 == null)
            SubShapeID_TEMP_GEN_0 = SubShapeID.native_new();
        SubShapeID_TEMP_GEN_0.internal_reset(addr, false);
        return SubShapeID_TEMP_GEN_0;
    }

    public static long internal_native_get_mSubShapeID2_addr(long this_addr) {
        return jolt.physics.collision.natives.JNI_RayCastResult.internal_native_get_mSubShapeID2_addr(this_addr);
    }

    public void set_mSubShapeID2(SubShapeID mSubShapeID2) {
        internal_native_set_mSubShapeID2(native_address, mSubShapeID2.native_address);
    }

    public static void internal_native_set_mSubShapeID2(long this_addr, long mSubShapeID2_addr) {
        jolt.physics.collision.natives.JNI_RayCastResult.internal_native_set_mSubShapeID2(this_addr, mSubShapeID2_addr);
    }
}
