/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape.natives;

import jolt.physics.collision.shape.*;

final public class JNI_Shape {

    public static native int internal_native_GetRefCount(long this_addr);

    public static native void internal_native_AddRef(long this_addr);

    public static native void internal_native_Release(long this_addr);

    public static native int internal_native_GetType(long this_addr);

    public static native int internal_native_GetSubType(long this_addr);

    public static native boolean internal_native_MustBeStatic(long this_addr);

    public static native long internal_native_GetLocalBounds_addr(long this_addr);

    public static native long internal_native_GetWorldSpaceBounds_addr(long this_addr, long inCenterOfMassTransform_addr, long inScale_addr);

    public static native long internal_native_GetCenterOfMass_addr(long this_addr);

    public static native long internal_native_GetUserData(long this_addr);

    public static native void internal_native_SetUserData(long this_addr, long inUserData);

    public static native int internal_native_GetSubShapeIDBitsRecursive(long this_addr);

    public static native float internal_native_GetInnerRadius(long this_addr);

    public static native long internal_native_GetMassProperties_addr(long this_addr);

    public static native long internal_native_GetLeafShape_addr(long this_addr, long inSubShapeID_addr, long outRemainder_addr);

    public static native long internal_native_GetMaterial_addr(long this_addr, long inSubShapeID_addr);

    public static native long internal_native_GetSurfaceNormal_addr(long this_addr, long inSubShapeID_addr, long inLocalSurfacePosition_addr);

    public static native long internal_native_GetSubShapeUserData(long this_addr, long inSubShapeID_addr);

    public static native long internal_native_GetSubShapeTransformedShape_addr(long this_addr, long inSubShapeID_addr, long inPositionCOM_addr, long inRotation_addr, long inScale_addr, long outRemainder_addr);

    public static native float internal_native_GetVolume(long this_addr);

    public static native boolean internal_native_IsValidScale(long this_addr, long inScale_addr);

    public static native long internal_native_MakeScaleValid_addr(long this_addr, long inScale_addr);

    public static native long internal_native_ScaleShape_addr(long this_addr, long inScale_addr);

    public static native void internal_native_Draw(long this_addr, long inRenderer_addr, long inCenterOfMassTransform_addr, long inScale_addr, long inColor_addr, boolean inUseMaterialColors, boolean inDrawWireframe);
}
