/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.raddoll;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.TwoBodyConstraintSettings;

public final class RagdollAdditionalConstraint extends NativeObject {

    static public final RagdollAdditionalConstraint NULL = RagdollAdditionalConstraint.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected RagdollAdditionalConstraint(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static RagdollAdditionalConstraint native_new() {
        return new RagdollAdditionalConstraint((byte) 0, (char) 0);
    }

    public int get_mBodyIdx(int index) {
        return 0;
    }

    public void set_mBodyIdx(int index, int mBodyIdx) {
    }

    public TwoBodyConstraintSettings get_mConstraint() {
        return null;
    }

    public void set_mConstraint(TwoBodyConstraintSettings mConstraint) {
    }
}
