/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.body;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.Vec3;
import jolt.math.Mat44;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class MassProperties extends NativeObject {

    static private Vec3 Vec3_TEMP_STATIC_GEN_0;

    private Mat44 Mat44_TEMP_GEN_0;

    static public final MassProperties NULL = MassProperties.native_new();

    public MassProperties() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected MassProperties(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static MassProperties native_new() {
        return new MassProperties((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean Equals(MassProperties inRHS) {
        return internal_native_Equals(native_address, inRHS.native_address);
    }

    public static boolean internal_native_Equals(long this_addr, long inRHS_addr) {
        try {
            return (boolean) FFMHandles.internal_native_Equals__JJ.invokeExact(this_addr, inRHS_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean NotEquals(MassProperties inRHS) {
        return internal_native_NotEquals(native_address, inRHS.native_address);
    }

    public static boolean internal_native_NotEquals(long this_addr, long inRHS_addr) {
        try {
            return (boolean) FFMHandles.internal_native_NotEquals__JJ.invokeExact(this_addr, inRHS_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetMassAndInertiaOfSolidBox(Vec3 inBoxSize, float inDensity) {
        internal_native_SetMassAndInertiaOfSolidBox(native_address, inBoxSize.native_address, inDensity);
    }

    public static void internal_native_SetMassAndInertiaOfSolidBox(long this_addr, long inBoxSize_addr, float inDensity) {
        try {
            FFMHandles.internal_native_SetMassAndInertiaOfSolidBox__JJF.invokeExact(this_addr, inBoxSize_addr, inDensity);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ScaleToMass(float inMass) {
        internal_native_ScaleToMass(native_address, inMass);
    }

    public static void internal_native_ScaleToMass(long this_addr, float inMass) {
        try {
            FFMHandles.internal_native_ScaleToMass__JF.invokeExact(this_addr, inMass);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static Vec3 sGetEquivalentSolidBoxSize(float inMass, Vec3 inInertiaDiagonal) {
        long addr = internal_native_sGetEquivalentSolidBoxSize_addr(inMass, inInertiaDiagonal.native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_STATIC_GEN_0 == null)
            Vec3_TEMP_STATIC_GEN_0 = Vec3.native_new();
        Vec3_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return Vec3_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_sGetEquivalentSolidBoxSize_addr(float inMass, long inInertiaDiagonal_addr) {
        try {
            return (long) FFMHandles.internal_native_sGetEquivalentSolidBoxSize_addr__FJ.invokeExact(inMass, inInertiaDiagonal_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Rotate(Mat44 inRotation) {
        internal_native_Rotate(native_address, inRotation.native_address);
    }

    public static void internal_native_Rotate(long this_addr, long inRotation_addr) {
        try {
            FFMHandles.internal_native_Rotate__JJ.invokeExact(this_addr, inRotation_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Translate(Vec3 inTranslation) {
        internal_native_Translate(native_address, inTranslation.native_address);
    }

    public static void internal_native_Translate(long this_addr, long inTranslation_addr) {
        try {
            FFMHandles.internal_native_Translate__JJ.invokeExact(this_addr, inTranslation_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Scale(Vec3 inScale) {
        internal_native_Scale(native_address, inScale.native_address);
    }

    public static void internal_native_Scale(long this_addr, long inScale_addr) {
        try {
            FFMHandles.internal_native_Scale__JJ.invokeExact(this_addr, inScale_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mMass() {
        return internal_native_get_mMass(native_address);
    }

    public static float internal_native_get_mMass(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mMass__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mMass(float mMass) {
        internal_native_set_mMass(native_address, mMass);
    }

    public static void internal_native_set_mMass(long this_addr, float mMass) {
        try {
            FFMHandles.internal_native_set_mMass__JF.invokeExact(this_addr, mMass);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Mat44 get_mInertia() {
        long addr = internal_native_get_mInertia_addr(native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_0 == null)
            Mat44_TEMP_GEN_0 = Mat44.native_new();
        Mat44_TEMP_GEN_0.internal_reset(addr, false);
        return Mat44_TEMP_GEN_0;
    }

    public static long internal_native_get_mInertia_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mInertia_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mInertia(Mat44 mInertia) {
        internal_native_set_mInertia(native_address, mInertia.native_address);
    }

    public static void internal_native_set_mInertia(long this_addr, long mInertia_addr) {
        try {
            FFMHandles.internal_native_set_mInertia__JJ.invokeExact(this_addr, mInertia_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Equals__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_equals", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_NotEquals__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_notequals", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetMassAndInertiaOfSolidBox__JJF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_setmassandinertiaofsolidbox", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_ScaleToMass__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_scaletomass", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_sGetEquivalentSolidBoxSize_addr__FJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_sgetequivalentsolidboxsize_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Rotate__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_rotate", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Translate__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_translate", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Scale__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_scale", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mMass__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_get_mmass", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mMass__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_set_mmass", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_mInertia_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_get_minertia_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mInertia__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_body_massproperties_set_minertia", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
