/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.collision.broadphase.BroadPhaseLayerInterface;
import jolt.physics.collision.broadphase.ObjectVsBroadPhaseLayerFilter;
import jolt.physics.collision.ObjectLayerPairFilter;
import jolt.core.TempAllocator;
import jolt.core.JobSystem;
import jolt.math.Vec3;
import jolt.enums.EBodyType;
import jolt.physics.body.BodyIDVector;
import jolt.geometry.AABox;
import jolt.physics.constraints.Constraint;
import jolt.physics.collision.ContactListener;
import jolt.physics.softbody.SoftBodyContactListener;
import jolt.physics.body.BodyInterface;
import jolt.physics.body.BodyLockInterfaceNoLock;
import jolt.physics.body.BodyLockInterfaceLocking;
import jolt.physics.collision.broadphase.BroadPhaseQuery;
import jolt.physics.collision.NarrowPhaseQuery;
import jolt.enums.EStateRecorderState;
import jolt.physics.vehicle.VehicleConstraint;
import jolt.physics.body.BodyActivationListener;
import jolt.physics.body.BodyID;
import jolt.physics.collision.SimShapeFilter;

public final class PhysicsSystem extends NativeObject {

    static public final PhysicsSystem NULL = PhysicsSystem.native_new();

    public PhysicsSystem() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected PhysicsSystem(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static PhysicsSystem native_new() {
        return new PhysicsSystem((byte) 0, (char) 0);
    }

    public void Init(int inMaxBodies, int inNumBodyMutexes, int inMaxBodyPairs, int inMaxContactConstraints, BroadPhaseLayerInterface inBroadPhaseLayerInterface, ObjectVsBroadPhaseLayerFilter inObjectVsBroadPhaseLayerFilter, ObjectLayerPairFilter inObjectLayerPairFilter) {
    }

    public void Update(float inDeltaTime, int inCollisionSteps, TempAllocator inTempAllocator, JobSystem inJobSystem) {
    }

    public void SetGravity(Vec3 inGravity) {
    }

    public Vec3 GetGravity() {
        return null;
    }

    public PhysicsSettings GetPhysicsSettings() {
        return null;
    }

    public void SetPhysicsSettings(PhysicsSettings inPhysicsSettings) {
    }

    public int GetNumBodies() {
        return 0;
    }

    public int GetNumActiveBodies(EBodyType inBodyType) {
        return 0;
    }

    public int GetMaxBodies() {
        return 0;
    }

    public void GetBodies(BodyIDVector outBodies) {
    }

    public void GetActiveBodies(EBodyType inBodyType, BodyIDVector outBodies) {
    }

    public AABox GetBounds() {
        return null;
    }

    public void AddConstraint(Constraint inConstraint) {
    }

    public void RemoveConstraint(Constraint inConstraint) {
    }

    public void SetContactListener(ContactListener inListener) {
    }

    public ContactListener GetContactListener() {
        return null;
    }

    public void SetSoftBodyContactListener(SoftBodyContactListener inListener) {
    }

    public SoftBodyContactListener GetSoftBodyContactListener() {
        return null;
    }

    public void OptimizeBroadPhase() {
    }

    public BodyInterface GetBodyInterface() {
        return null;
    }

    public BodyInterface GetBodyInterfaceNoLock() {
        return null;
    }

    public BodyLockInterfaceNoLock GetBodyLockInterfaceNoLock() {
        return null;
    }

    public BodyLockInterfaceLocking GetBodyLockInterface() {
        return null;
    }

    public BroadPhaseQuery GetBroadPhaseQuery() {
        return null;
    }

    public NarrowPhaseQuery GetNarrowPhaseQuery() {
        return null;
    }

    public NarrowPhaseQuery GetNarrowPhaseQueryNoLock() {
        return null;
    }

    public void SaveState(StateRecorder inStream, EStateRecorderState inState, StateRecorderFilter inFilter) {
    }

    public void SaveState(StateRecorder inStream, EStateRecorderState inState) {
    }

    public void SaveState(StateRecorder inStream) {
    }

    public boolean RestoreState(StateRecorder inStream, StateRecorderFilter inFilter) {
        return false;
    }

    public boolean RestoreState(StateRecorder inStream) {
        return false;
    }

    public void AddStepListener(PhysicsStepListener inListener) {
    }

    public void AddStepListener(VehicleConstraint inListener) {
    }

    public void RemoveStepListener(PhysicsStepListener inListener) {
    }

    public void RemoveStepListener(VehicleConstraint inListener) {
    }

    public void SetBodyActivationListener(BodyActivationListener inListener) {
    }

    public BodyActivationListener GetBodyActivationListener() {
        return null;
    }

    public boolean WereBodiesInContact(BodyID inBodyID1, BodyID inBodyID2) {
        return false;
    }

    public void SetSimShapeFilter(SimShapeFilter inShapeFilter) {
    }

    public SimShapeFilter GetSimShapeFilter() {
        return null;
    }
}
