/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.softbody;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.physics.body.BodyID;
import jolt.geometry.Plane;
import jolt.math.Vec3;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class SoftBodyVertex extends NativeObject {

    private Vec3 Vec3_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_1;

    private Vec3 Vec3_TEMP_GEN_2;

    static public final SoftBodyVertex NULL = SoftBodyVertex.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected SoftBodyVertex(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static SoftBodyVertex native_new() {
        return new SoftBodyVertex((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void MarkCCDContact(BodyID inBodyID, Plane inContactPlane) {
        internal_native_MarkCCDContact(native_address, inBodyID.native_address, inContactPlane.native_address);
    }

    public static void internal_native_MarkCCDContact(long this_addr, long inBodyID_addr, long inContactPlane_addr) {
        try {
            FFMHandles.internal_native_MarkCCDContact__JJJ.invokeExact(this_addr, inBodyID_addr, inContactPlane_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 get_mPreviousPosition() {
        long addr = internal_native_get_mPreviousPosition_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.native_new();
        Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return Vec3_TEMP_GEN_0;
    }

    public static long internal_native_get_mPreviousPosition_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mPreviousPosition_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mPreviousPosition(Vec3 mPreviousPosition) {
        internal_native_set_mPreviousPosition(native_address, mPreviousPosition.native_address);
    }

    public static void internal_native_set_mPreviousPosition(long this_addr, long mPreviousPosition_addr) {
        try {
            FFMHandles.internal_native_set_mPreviousPosition__JJ.invokeExact(this_addr, mPreviousPosition_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 get_mPosition() {
        long addr = internal_native_get_mPosition_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_1 == null)
            Vec3_TEMP_GEN_1 = Vec3.native_new();
        Vec3_TEMP_GEN_1.internal_reset(addr, false);
        return Vec3_TEMP_GEN_1;
    }

    public static long internal_native_get_mPosition_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mPosition_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mPosition(Vec3 mPosition) {
        internal_native_set_mPosition(native_address, mPosition.native_address);
    }

    public static void internal_native_set_mPosition(long this_addr, long mPosition_addr) {
        try {
            FFMHandles.internal_native_set_mPosition__JJ.invokeExact(this_addr, mPosition_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 get_mVelocity() {
        long addr = internal_native_get_mVelocity_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_2 == null)
            Vec3_TEMP_GEN_2 = Vec3.native_new();
        Vec3_TEMP_GEN_2.internal_reset(addr, false);
        return Vec3_TEMP_GEN_2;
    }

    public static long internal_native_get_mVelocity_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mVelocity_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mVelocity(Vec3 mVelocity) {
        internal_native_set_mVelocity(native_address, mVelocity.native_address);
    }

    public static void internal_native_set_mVelocity(long this_addr, long mVelocity_addr) {
        try {
            FFMHandles.internal_native_set_mVelocity__JJ.invokeExact(this_addr, mVelocity_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mInvMass() {
        return internal_native_get_mInvMass(native_address);
    }

    public static float internal_native_get_mInvMass(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mInvMass__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mInvMass(float mInvMass) {
        internal_native_set_mInvMass(native_address, mInvMass);
    }

    public static void internal_native_set_mInvMass(long this_addr, float mInvMass) {
        try {
            FFMHandles.internal_native_set_mInvMass__JF.invokeExact(this_addr, mInvMass);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodyvertex_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_MarkCCDContact__JJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodyvertex_markccdcontact", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mPreviousPosition_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodyvertex_get_mpreviousposition_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mPreviousPosition__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodyvertex_set_mpreviousposition", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mPosition_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodyvertex_get_mposition_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mPosition__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodyvertex_set_mposition", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mVelocity_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodyvertex_get_mvelocity_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mVelocity__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodyvertex_set_mvelocity", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mInvMass__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodyvertex_get_minvmass", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mInvMass__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodyvertex_set_minvmass", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));
    }
}
