/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.softbody;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.Quat;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class SoftBodySharedSettingsRodBendTwist extends NativeObject {

    private Quat Quat_TEMP_GEN_0;

    static public final SoftBodySharedSettingsRodBendTwist NULL = SoftBodySharedSettingsRodBendTwist.native_new();

    public SoftBodySharedSettingsRodBendTwist(int inRod1, int inRod2, float inCompliance) {
        long addr = internal_native_create_int_int_float_addr(inRod1, inRod2, inCompliance);
        internal_reset(addr, true);
    }

    public static long internal_native_create_int_int_float_addr(int inRod1, int inRod2, float inCompliance) {
        try {
            return (long) FFMHandles.internal_native_create_int_int_float_addr__IIF.invokeExact(inRod1, inRod2, inCompliance);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected SoftBodySharedSettingsRodBendTwist(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static SoftBodySharedSettingsRodBendTwist native_new() {
        return new SoftBodySharedSettingsRodBendTwist((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_mRod(int index) {
        return internal_native_get_mRod(native_address, index);
    }

    public static int internal_native_get_mRod(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_get_mRod__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mRod(int index, int mRod) {
        internal_native_set_mRod(native_address, index, mRod);
    }

    public static void internal_native_set_mRod(long this_addr, int index, int mRod) {
        try {
            FFMHandles.internal_native_set_mRod__JII.invokeExact(this_addr, index, mRod);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mCompliance() {
        return internal_native_get_mCompliance(native_address);
    }

    public static float internal_native_get_mCompliance(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mCompliance__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mCompliance(float mCompliance) {
        internal_native_set_mCompliance(native_address, mCompliance);
    }

    public static void internal_native_set_mCompliance(long this_addr, float mCompliance) {
        try {
            FFMHandles.internal_native_set_mCompliance__JF.invokeExact(this_addr, mCompliance);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Quat get_mOmega0() {
        long addr = internal_native_get_mOmega0_addr(native_address);
        if (addr == 0)
            return Quat.NULL;
        if (Quat_TEMP_GEN_0 == null)
            Quat_TEMP_GEN_0 = Quat.native_new();
        Quat_TEMP_GEN_0.internal_reset(addr, false);
        return Quat_TEMP_GEN_0;
    }

    public static long internal_native_get_mOmega0_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mOmega0_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mOmega0(Quat mOmega0) {
        internal_native_set_mOmega0(native_address, mOmega0.native_address);
    }

    public static void internal_native_set_mOmega0(long this_addr, long mOmega0_addr) {
        try {
            FFMHandles.internal_native_set_mOmega0__JJ.invokeExact(this_addr, mOmega0_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_int_int_float_addr__IIF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodysharedsettingsrodbendtwist_create_int_int_float_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodysharedsettingsrodbendtwist_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mRod__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodysharedsettingsrodbendtwist_get_mrod", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_set_mRod__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodysharedsettingsrodbendtwist_set_mrod", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_get_mCompliance__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodysharedsettingsrodbendtwist_get_mcompliance", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mCompliance__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodysharedsettingsrodbendtwist_set_mcompliance", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_get_mOmega0_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodysharedsettingsrodbendtwist_get_momega0_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mOmega0__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_softbody_softbodysharedsettingsrodbendtwist_set_momega0", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
