/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape;

import jolt.physics.collision.PhysicsMaterial;

public final class CylinderShape extends ConvexShape {

    static public final CylinderShape NULL = CylinderShape.native_new();

    public CylinderShape(float inHalfHeight, float inRadius, float inConvexRadius, PhysicsMaterial inMaterial) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_float_float_float_PhysicsMaterial_addr(inHalfHeight, inRadius, inConvexRadius, inMaterial.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_float_float_float_PhysicsMaterial_addr(float inHalfHeight, float inRadius, float inConvexRadius, long inMaterial_addr) {
        return jolt.physics.collision.shape.natives.JNI_CylinderShape.internal_native_create_float_float_float_PhysicsMaterial_addr(inHalfHeight, inRadius, inConvexRadius, inMaterial_addr);
    }

    public CylinderShape(float inHalfHeight, float inRadius, float inConvexRadius) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_float_float_float_addr(inHalfHeight, inRadius, inConvexRadius);
        internal_reset(addr, true);
    }

    public static long internal_native_create_float_float_float_addr(float inHalfHeight, float inRadius, float inConvexRadius) {
        return jolt.physics.collision.shape.natives.JNI_CylinderShape.internal_native_create_float_float_float_addr(inHalfHeight, inRadius, inConvexRadius);
    }

    public CylinderShape(float inHalfHeight, float inRadius) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_float_float_addr(inHalfHeight, inRadius);
        internal_reset(addr, true);
    }

    public static long internal_native_create_float_float_addr(float inHalfHeight, float inRadius) {
        return jolt.physics.collision.shape.natives.JNI_CylinderShape.internal_native_create_float_float_addr(inHalfHeight, inRadius);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CylinderShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static CylinderShape native_new() {
        return new CylinderShape((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.collision.shape.natives.JNI_CylinderShape.internal_native_deleteNative(this_addr);
    }

    public float GetRadius() {
        return internal_native_GetRadius(native_address);
    }

    public static float internal_native_GetRadius(long this_addr) {
        return jolt.physics.collision.shape.natives.JNI_CylinderShape.internal_native_GetRadius(this_addr);
    }

    public float GetHalfHeight() {
        return internal_native_GetHalfHeight(native_address);
    }

    public static float internal_native_GetHalfHeight(long this_addr) {
        return jolt.physics.collision.shape.natives.JNI_CylinderShape.internal_native_GetHalfHeight(this_addr);
    }
}
