/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape;

public final class MutableCompoundShapeSettings extends CompoundShapeSettings {

    static public final MutableCompoundShapeSettings NULL = MutableCompoundShapeSettings.native_new();

    public MutableCompoundShapeSettings() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.collision.shape.natives.JNI_MutableCompoundShapeSettings.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected MutableCompoundShapeSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static MutableCompoundShapeSettings native_new() {
        return new MutableCompoundShapeSettings((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.collision.shape.natives.JNI_MutableCompoundShapeSettings.internal_native_deleteNative(this_addr);
    }
}
