/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape;

import jolt.physics.collision.PhysicsMaterial;

public final class SphereShapeSettings extends ConvexShapeSettings {

    static public final SphereShapeSettings NULL = SphereShapeSettings.native_new();

    public SphereShapeSettings(float inRadius, PhysicsMaterial inMaterial) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_float_PhysicsMaterial_addr(inRadius, inMaterial.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_float_PhysicsMaterial_addr(float inRadius, long inMaterial_addr) {
        return jolt.physics.collision.shape.natives.JNI_SphereShapeSettings.internal_native_create_float_PhysicsMaterial_addr(inRadius, inMaterial_addr);
    }

    public SphereShapeSettings(float inRadius) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_float_addr(inRadius);
        internal_reset(addr, true);
    }

    public static long internal_native_create_float_addr(float inRadius) {
        return jolt.physics.collision.shape.natives.JNI_SphereShapeSettings.internal_native_create_float_addr(inRadius);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected SphereShapeSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static SphereShapeSettings native_new() {
        return new SphereShapeSettings((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.collision.shape.natives.JNI_SphereShapeSettings.internal_native_deleteNative(this_addr);
    }

    public float get_mRadius() {
        return internal_native_get_mRadius(native_address);
    }

    public static float internal_native_get_mRadius(long this_addr) {
        return jolt.physics.collision.shape.natives.JNI_SphereShapeSettings.internal_native_get_mRadius(this_addr);
    }

    public void set_mRadius(float mRadius) {
        internal_native_set_mRadius(native_address, mRadius);
    }

    public static void internal_native_set_mRadius(long this_addr, float mRadius) {
        jolt.physics.collision.shape.natives.JNI_SphereShapeSettings.internal_native_set_mRadius(this_addr, mRadius);
    }
}
