/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape;

import jolt.physics.collision.PhysicsMaterial;

public final class TaperedCapsuleShapeSettings extends ConvexShapeSettings {

    static public final TaperedCapsuleShapeSettings NULL = TaperedCapsuleShapeSettings.native_new();

    public TaperedCapsuleShapeSettings(float inHalfHeightOfTaperedCylinder, float inTopRadius, float inBottomRadius, PhysicsMaterial inMaterial) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_float_float_float_PhysicsMaterial_addr(inHalfHeightOfTaperedCylinder, inTopRadius, inBottomRadius, inMaterial.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_float_float_float_PhysicsMaterial_addr(float inHalfHeightOfTaperedCylinder, float inTopRadius, float inBottomRadius, long inMaterial_addr) {
        return jolt.physics.collision.shape.natives.JNI_TaperedCapsuleShapeSettings.internal_native_create_float_float_float_PhysicsMaterial_addr(inHalfHeightOfTaperedCylinder, inTopRadius, inBottomRadius, inMaterial_addr);
    }

    public TaperedCapsuleShapeSettings(float inHalfHeightOfTaperedCylinder, float inTopRadius, float inBottomRadius) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_float_float_float_addr(inHalfHeightOfTaperedCylinder, inTopRadius, inBottomRadius);
        internal_reset(addr, true);
    }

    public static long internal_native_create_float_float_float_addr(float inHalfHeightOfTaperedCylinder, float inTopRadius, float inBottomRadius) {
        return jolt.physics.collision.shape.natives.JNI_TaperedCapsuleShapeSettings.internal_native_create_float_float_float_addr(inHalfHeightOfTaperedCylinder, inTopRadius, inBottomRadius);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected TaperedCapsuleShapeSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static TaperedCapsuleShapeSettings native_new() {
        return new TaperedCapsuleShapeSettings((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.collision.shape.natives.JNI_TaperedCapsuleShapeSettings.internal_native_deleteNative(this_addr);
    }

    public float get_mHalfHeightOfTaperedCylinder() {
        return internal_native_get_mHalfHeightOfTaperedCylinder(native_address);
    }

    public static float internal_native_get_mHalfHeightOfTaperedCylinder(long this_addr) {
        return jolt.physics.collision.shape.natives.JNI_TaperedCapsuleShapeSettings.internal_native_get_mHalfHeightOfTaperedCylinder(this_addr);
    }

    public void set_mHalfHeightOfTaperedCylinder(float mHalfHeightOfTaperedCylinder) {
        internal_native_set_mHalfHeightOfTaperedCylinder(native_address, mHalfHeightOfTaperedCylinder);
    }

    public static void internal_native_set_mHalfHeightOfTaperedCylinder(long this_addr, float mHalfHeightOfTaperedCylinder) {
        jolt.physics.collision.shape.natives.JNI_TaperedCapsuleShapeSettings.internal_native_set_mHalfHeightOfTaperedCylinder(this_addr, mHalfHeightOfTaperedCylinder);
    }

    public float get_mTopRadius() {
        return internal_native_get_mTopRadius(native_address);
    }

    public static float internal_native_get_mTopRadius(long this_addr) {
        return jolt.physics.collision.shape.natives.JNI_TaperedCapsuleShapeSettings.internal_native_get_mTopRadius(this_addr);
    }

    public void set_mTopRadius(float mTopRadius) {
        internal_native_set_mTopRadius(native_address, mTopRadius);
    }

    public static void internal_native_set_mTopRadius(long this_addr, float mTopRadius) {
        jolt.physics.collision.shape.natives.JNI_TaperedCapsuleShapeSettings.internal_native_set_mTopRadius(this_addr, mTopRadius);
    }

    public float get_mBottomRadius() {
        return internal_native_get_mBottomRadius(native_address);
    }

    public static float internal_native_get_mBottomRadius(long this_addr) {
        return jolt.physics.collision.shape.natives.JNI_TaperedCapsuleShapeSettings.internal_native_get_mBottomRadius(this_addr);
    }

    public void set_mBottomRadius(float mBottomRadius) {
        internal_native_set_mBottomRadius(native_address, mBottomRadius);
    }

    public static void internal_native_set_mBottomRadius(long this_addr, float mBottomRadius) {
        jolt.physics.collision.shape.natives.JNI_TaperedCapsuleShapeSettings.internal_native_set_mBottomRadius(this_addr, mBottomRadius);
    }
}
