/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.character;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ArrayCharacterVirtualContact extends NativeObject {

    private CharacterVirtualContact CharacterVirtualContact_TEMP_GEN_0;

    static public final ArrayCharacterVirtualContact NULL = ArrayCharacterVirtualContact.native_new();

    public ArrayCharacterVirtualContact() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.character.natives.JNI_ArrayCharacterVirtualContact.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ArrayCharacterVirtualContact(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ArrayCharacterVirtualContact native_new() {
        return new ArrayCharacterVirtualContact((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.character.natives.JNI_ArrayCharacterVirtualContact.internal_native_deleteNative(this_addr);
    }

    public boolean empty() {
        return internal_native_empty(native_address);
    }

    public static boolean internal_native_empty(long this_addr) {
        return jolt.physics.character.natives.JNI_ArrayCharacterVirtualContact.internal_native_empty(this_addr);
    }

    public int size() {
        return internal_native_size(native_address);
    }

    public static int internal_native_size(long this_addr) {
        return jolt.physics.character.natives.JNI_ArrayCharacterVirtualContact.internal_native_size(this_addr);
    }

    public CharacterVirtualContact at(int inIndex) {
        long addr = internal_native_at_addr(native_address, inIndex);
        if (addr == 0)
            return CharacterVirtualContact.NULL;
        if (CharacterVirtualContact_TEMP_GEN_0 == null)
            CharacterVirtualContact_TEMP_GEN_0 = CharacterVirtualContact.native_new();
        CharacterVirtualContact_TEMP_GEN_0.internal_reset(addr, false);
        return CharacterVirtualContact_TEMP_GEN_0;
    }

    public static long internal_native_at_addr(long this_addr, int inIndex) {
        return jolt.physics.character.natives.JNI_ArrayCharacterVirtualContact.internal_native_at_addr(this_addr, inIndex);
    }
}
