/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.body;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.enums.EShapeColor;
import jolt.enums.ESoftBodyConstraintColor;

public final class BodyManagerDrawSettings extends NativeObject {

    static public final BodyManagerDrawSettings NULL = BodyManagerDrawSettings.native_new();

    public BodyManagerDrawSettings() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected BodyManagerDrawSettings(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static BodyManagerDrawSettings native_new() {
        return new BodyManagerDrawSettings((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_deleteNative(this_addr);
    }

    public boolean get_mDrawGetSupportFunction() {
        return internal_native_get_mDrawGetSupportFunction(native_address);
    }

    public static boolean internal_native_get_mDrawGetSupportFunction(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawGetSupportFunction(this_addr);
    }

    public void set_mDrawGetSupportFunction(boolean mDrawGetSupportFunction) {
        internal_native_set_mDrawGetSupportFunction(native_address, mDrawGetSupportFunction);
    }

    public static void internal_native_set_mDrawGetSupportFunction(long this_addr, boolean mDrawGetSupportFunction) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawGetSupportFunction(this_addr, mDrawGetSupportFunction);
    }

    public boolean get_mDrawSupportDirection() {
        return internal_native_get_mDrawSupportDirection(native_address);
    }

    public static boolean internal_native_get_mDrawSupportDirection(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSupportDirection(this_addr);
    }

    public void set_mDrawSupportDirection(boolean mDrawSupportDirection) {
        internal_native_set_mDrawSupportDirection(native_address, mDrawSupportDirection);
    }

    public static void internal_native_set_mDrawSupportDirection(long this_addr, boolean mDrawSupportDirection) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSupportDirection(this_addr, mDrawSupportDirection);
    }

    public boolean get_mDrawGetSupportingFace() {
        return internal_native_get_mDrawGetSupportingFace(native_address);
    }

    public static boolean internal_native_get_mDrawGetSupportingFace(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawGetSupportingFace(this_addr);
    }

    public void set_mDrawGetSupportingFace(boolean mDrawGetSupportingFace) {
        internal_native_set_mDrawGetSupportingFace(native_address, mDrawGetSupportingFace);
    }

    public static void internal_native_set_mDrawGetSupportingFace(long this_addr, boolean mDrawGetSupportingFace) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawGetSupportingFace(this_addr, mDrawGetSupportingFace);
    }

    public boolean get_mDrawShape() {
        return internal_native_get_mDrawShape(native_address);
    }

    public static boolean internal_native_get_mDrawShape(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawShape(this_addr);
    }

    public void set_mDrawShape(boolean mDrawShape) {
        internal_native_set_mDrawShape(native_address, mDrawShape);
    }

    public static void internal_native_set_mDrawShape(long this_addr, boolean mDrawShape) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawShape(this_addr, mDrawShape);
    }

    public boolean get_mDrawShapeWireframe() {
        return internal_native_get_mDrawShapeWireframe(native_address);
    }

    public static boolean internal_native_get_mDrawShapeWireframe(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawShapeWireframe(this_addr);
    }

    public void set_mDrawShapeWireframe(boolean mDrawShapeWireframe) {
        internal_native_set_mDrawShapeWireframe(native_address, mDrawShapeWireframe);
    }

    public static void internal_native_set_mDrawShapeWireframe(long this_addr, boolean mDrawShapeWireframe) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawShapeWireframe(this_addr, mDrawShapeWireframe);
    }

    public EShapeColor get_mDrawShapeColor() {
        int value = internal_native_get_mDrawShapeColor(native_address);
        EShapeColor[] values = EShapeColor.values();
        for (int i = 0; i < values.length; i++) {
            EShapeColor enumVal = values[i];
            if (enumVal != EShapeColor.CUSTOM && enumVal.getValue() == value)
                return enumVal;
        }
        return EShapeColor.CUSTOM.setValue(value);
    }

    public static int internal_native_get_mDrawShapeColor(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawShapeColor(this_addr);
    }

    public void set_mDrawShapeColor(EShapeColor mDrawShapeColor) {
        internal_native_set_mDrawShapeColor(native_address, mDrawShapeColor.getValue());
    }

    public static void internal_native_set_mDrawShapeColor(long this_addr, int mDrawShapeColor) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawShapeColor(this_addr, mDrawShapeColor);
    }

    public boolean get_mDrawBoundingBox() {
        return internal_native_get_mDrawBoundingBox(native_address);
    }

    public static boolean internal_native_get_mDrawBoundingBox(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawBoundingBox(this_addr);
    }

    public void set_mDrawBoundingBox(boolean mDrawBoundingBox) {
        internal_native_set_mDrawBoundingBox(native_address, mDrawBoundingBox);
    }

    public static void internal_native_set_mDrawBoundingBox(long this_addr, boolean mDrawBoundingBox) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawBoundingBox(this_addr, mDrawBoundingBox);
    }

    public boolean get_mDrawCenterOfMassTransform() {
        return internal_native_get_mDrawCenterOfMassTransform(native_address);
    }

    public static boolean internal_native_get_mDrawCenterOfMassTransform(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawCenterOfMassTransform(this_addr);
    }

    public void set_mDrawCenterOfMassTransform(boolean mDrawCenterOfMassTransform) {
        internal_native_set_mDrawCenterOfMassTransform(native_address, mDrawCenterOfMassTransform);
    }

    public static void internal_native_set_mDrawCenterOfMassTransform(long this_addr, boolean mDrawCenterOfMassTransform) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawCenterOfMassTransform(this_addr, mDrawCenterOfMassTransform);
    }

    public boolean get_mDrawWorldTransform() {
        return internal_native_get_mDrawWorldTransform(native_address);
    }

    public static boolean internal_native_get_mDrawWorldTransform(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawWorldTransform(this_addr);
    }

    public void set_mDrawWorldTransform(boolean mDrawWorldTransform) {
        internal_native_set_mDrawWorldTransform(native_address, mDrawWorldTransform);
    }

    public static void internal_native_set_mDrawWorldTransform(long this_addr, boolean mDrawWorldTransform) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawWorldTransform(this_addr, mDrawWorldTransform);
    }

    public boolean get_mDrawVelocity() {
        return internal_native_get_mDrawVelocity(native_address);
    }

    public static boolean internal_native_get_mDrawVelocity(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawVelocity(this_addr);
    }

    public void set_mDrawVelocity(boolean mDrawVelocity) {
        internal_native_set_mDrawVelocity(native_address, mDrawVelocity);
    }

    public static void internal_native_set_mDrawVelocity(long this_addr, boolean mDrawVelocity) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawVelocity(this_addr, mDrawVelocity);
    }

    public boolean get_mDrawMassAndInertia() {
        return internal_native_get_mDrawMassAndInertia(native_address);
    }

    public static boolean internal_native_get_mDrawMassAndInertia(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawMassAndInertia(this_addr);
    }

    public void set_mDrawMassAndInertia(boolean mDrawMassAndInertia) {
        internal_native_set_mDrawMassAndInertia(native_address, mDrawMassAndInertia);
    }

    public static void internal_native_set_mDrawMassAndInertia(long this_addr, boolean mDrawMassAndInertia) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawMassAndInertia(this_addr, mDrawMassAndInertia);
    }

    public boolean get_mDrawSleepStats() {
        return internal_native_get_mDrawSleepStats(native_address);
    }

    public static boolean internal_native_get_mDrawSleepStats(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSleepStats(this_addr);
    }

    public void set_mDrawSleepStats(boolean mDrawSleepStats) {
        internal_native_set_mDrawSleepStats(native_address, mDrawSleepStats);
    }

    public static void internal_native_set_mDrawSleepStats(long this_addr, boolean mDrawSleepStats) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSleepStats(this_addr, mDrawSleepStats);
    }

    public boolean get_mDrawSoftBodyVertices() {
        return internal_native_get_mDrawSoftBodyVertices(native_address);
    }

    public static boolean internal_native_get_mDrawSoftBodyVertices(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSoftBodyVertices(this_addr);
    }

    public void set_mDrawSoftBodyVertices(boolean mDrawSoftBodyVertices) {
        internal_native_set_mDrawSoftBodyVertices(native_address, mDrawSoftBodyVertices);
    }

    public static void internal_native_set_mDrawSoftBodyVertices(long this_addr, boolean mDrawSoftBodyVertices) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSoftBodyVertices(this_addr, mDrawSoftBodyVertices);
    }

    public boolean get_mDrawSoftBodyVertexVelocities() {
        return internal_native_get_mDrawSoftBodyVertexVelocities(native_address);
    }

    public static boolean internal_native_get_mDrawSoftBodyVertexVelocities(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSoftBodyVertexVelocities(this_addr);
    }

    public void set_mDrawSoftBodyVertexVelocities(boolean mDrawSoftBodyVertexVelocities) {
        internal_native_set_mDrawSoftBodyVertexVelocities(native_address, mDrawSoftBodyVertexVelocities);
    }

    public static void internal_native_set_mDrawSoftBodyVertexVelocities(long this_addr, boolean mDrawSoftBodyVertexVelocities) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSoftBodyVertexVelocities(this_addr, mDrawSoftBodyVertexVelocities);
    }

    public boolean get_mDrawSoftBodyEdgeConstraints() {
        return internal_native_get_mDrawSoftBodyEdgeConstraints(native_address);
    }

    public static boolean internal_native_get_mDrawSoftBodyEdgeConstraints(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSoftBodyEdgeConstraints(this_addr);
    }

    public void set_mDrawSoftBodyEdgeConstraints(boolean mDrawSoftBodyEdgeConstraints) {
        internal_native_set_mDrawSoftBodyEdgeConstraints(native_address, mDrawSoftBodyEdgeConstraints);
    }

    public static void internal_native_set_mDrawSoftBodyEdgeConstraints(long this_addr, boolean mDrawSoftBodyEdgeConstraints) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSoftBodyEdgeConstraints(this_addr, mDrawSoftBodyEdgeConstraints);
    }

    public boolean get_mDrawSoftBodyBendConstraints() {
        return internal_native_get_mDrawSoftBodyBendConstraints(native_address);
    }

    public static boolean internal_native_get_mDrawSoftBodyBendConstraints(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSoftBodyBendConstraints(this_addr);
    }

    public void set_mDrawSoftBodyBendConstraints(boolean mDrawSoftBodyBendConstraints) {
        internal_native_set_mDrawSoftBodyBendConstraints(native_address, mDrawSoftBodyBendConstraints);
    }

    public static void internal_native_set_mDrawSoftBodyBendConstraints(long this_addr, boolean mDrawSoftBodyBendConstraints) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSoftBodyBendConstraints(this_addr, mDrawSoftBodyBendConstraints);
    }

    public boolean get_mDrawSoftBodyVolumeConstraints() {
        return internal_native_get_mDrawSoftBodyVolumeConstraints(native_address);
    }

    public static boolean internal_native_get_mDrawSoftBodyVolumeConstraints(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSoftBodyVolumeConstraints(this_addr);
    }

    public void set_mDrawSoftBodyVolumeConstraints(boolean mDrawSoftBodyVolumeConstraints) {
        internal_native_set_mDrawSoftBodyVolumeConstraints(native_address, mDrawSoftBodyVolumeConstraints);
    }

    public static void internal_native_set_mDrawSoftBodyVolumeConstraints(long this_addr, boolean mDrawSoftBodyVolumeConstraints) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSoftBodyVolumeConstraints(this_addr, mDrawSoftBodyVolumeConstraints);
    }

    public boolean get_mDrawSoftBodySkinConstraints() {
        return internal_native_get_mDrawSoftBodySkinConstraints(native_address);
    }

    public static boolean internal_native_get_mDrawSoftBodySkinConstraints(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSoftBodySkinConstraints(this_addr);
    }

    public void set_mDrawSoftBodySkinConstraints(boolean mDrawSoftBodySkinConstraints) {
        internal_native_set_mDrawSoftBodySkinConstraints(native_address, mDrawSoftBodySkinConstraints);
    }

    public static void internal_native_set_mDrawSoftBodySkinConstraints(long this_addr, boolean mDrawSoftBodySkinConstraints) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSoftBodySkinConstraints(this_addr, mDrawSoftBodySkinConstraints);
    }

    public boolean get_mDrawSoftBodyLRAConstraints() {
        return internal_native_get_mDrawSoftBodyLRAConstraints(native_address);
    }

    public static boolean internal_native_get_mDrawSoftBodyLRAConstraints(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSoftBodyLRAConstraints(this_addr);
    }

    public void set_mDrawSoftBodyLRAConstraints(boolean mDrawSoftBodyLRAConstraints) {
        internal_native_set_mDrawSoftBodyLRAConstraints(native_address, mDrawSoftBodyLRAConstraints);
    }

    public static void internal_native_set_mDrawSoftBodyLRAConstraints(long this_addr, boolean mDrawSoftBodyLRAConstraints) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSoftBodyLRAConstraints(this_addr, mDrawSoftBodyLRAConstraints);
    }

    public boolean get_mDrawSoftBodyRods() {
        return internal_native_get_mDrawSoftBodyRods(native_address);
    }

    public static boolean internal_native_get_mDrawSoftBodyRods(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSoftBodyRods(this_addr);
    }

    public void set_mDrawSoftBodyRods(boolean mDrawSoftBodyRods) {
        internal_native_set_mDrawSoftBodyRods(native_address, mDrawSoftBodyRods);
    }

    public static void internal_native_set_mDrawSoftBodyRods(long this_addr, boolean mDrawSoftBodyRods) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSoftBodyRods(this_addr, mDrawSoftBodyRods);
    }

    public boolean get_mDrawSoftBodyRodStates() {
        return internal_native_get_mDrawSoftBodyRodStates(native_address);
    }

    public static boolean internal_native_get_mDrawSoftBodyRodStates(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSoftBodyRodStates(this_addr);
    }

    public void set_mDrawSoftBodyRodStates(boolean mDrawSoftBodyRodStates) {
        internal_native_set_mDrawSoftBodyRodStates(native_address, mDrawSoftBodyRodStates);
    }

    public static void internal_native_set_mDrawSoftBodyRodStates(long this_addr, boolean mDrawSoftBodyRodStates) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSoftBodyRodStates(this_addr, mDrawSoftBodyRodStates);
    }

    public boolean get_mDrawSoftBodyRodBendTwistConstraints() {
        return internal_native_get_mDrawSoftBodyRodBendTwistConstraints(native_address);
    }

    public static boolean internal_native_get_mDrawSoftBodyRodBendTwistConstraints(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSoftBodyRodBendTwistConstraints(this_addr);
    }

    public void set_mDrawSoftBodyRodBendTwistConstraints(boolean mDrawSoftBodyRodBendTwistConstraints) {
        internal_native_set_mDrawSoftBodyRodBendTwistConstraints(native_address, mDrawSoftBodyRodBendTwistConstraints);
    }

    public static void internal_native_set_mDrawSoftBodyRodBendTwistConstraints(long this_addr, boolean mDrawSoftBodyRodBendTwistConstraints) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSoftBodyRodBendTwistConstraints(this_addr, mDrawSoftBodyRodBendTwistConstraints);
    }

    public boolean get_mDrawSoftBodyPredictedBounds() {
        return internal_native_get_mDrawSoftBodyPredictedBounds(native_address);
    }

    public static boolean internal_native_get_mDrawSoftBodyPredictedBounds(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSoftBodyPredictedBounds(this_addr);
    }

    public void set_mDrawSoftBodyPredictedBounds(boolean mDrawSoftBodyPredictedBounds) {
        internal_native_set_mDrawSoftBodyPredictedBounds(native_address, mDrawSoftBodyPredictedBounds);
    }

    public static void internal_native_set_mDrawSoftBodyPredictedBounds(long this_addr, boolean mDrawSoftBodyPredictedBounds) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSoftBodyPredictedBounds(this_addr, mDrawSoftBodyPredictedBounds);
    }

    public ESoftBodyConstraintColor get_mDrawSoftBodyConstraintColor() {
        int value = internal_native_get_mDrawSoftBodyConstraintColor(native_address);
        ESoftBodyConstraintColor[] values = ESoftBodyConstraintColor.values();
        for (int i = 0; i < values.length; i++) {
            ESoftBodyConstraintColor enumVal = values[i];
            if (enumVal != ESoftBodyConstraintColor.CUSTOM && enumVal.getValue() == value)
                return enumVal;
        }
        return ESoftBodyConstraintColor.CUSTOM.setValue(value);
    }

    public static int internal_native_get_mDrawSoftBodyConstraintColor(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_get_mDrawSoftBodyConstraintColor(this_addr);
    }

    public void set_mDrawSoftBodyConstraintColor(ESoftBodyConstraintColor mDrawSoftBodyConstraintColor) {
        internal_native_set_mDrawSoftBodyConstraintColor(native_address, mDrawSoftBodyConstraintColor.getValue());
    }

    public static void internal_native_set_mDrawSoftBodyConstraintColor(long this_addr, int mDrawSoftBodyConstraintColor) {
        jolt.physics.body.natives.JNI_BodyManagerDrawSettings.internal_native_set_mDrawSoftBodyConstraintColor(this_addr, mDrawSoftBodyConstraintColor);
    }
}
