/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.body;

import com.github.xpenatan.jParser.api.NativeObject;

public final class BodyIDVector extends NativeObject {

    private BodyID BodyID_TEMP_GEN_0;

    static public final BodyIDVector NULL = BodyIDVector.native_new();

    public BodyIDVector() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.body.natives.JNI_BodyIDVector.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected BodyIDVector(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static BodyIDVector native_new() {
        return new BodyIDVector((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.body.natives.JNI_BodyIDVector.internal_native_deleteNative(this_addr);
    }

    public boolean empty() {
        return internal_native_empty(native_address);
    }

    public static boolean internal_native_empty(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyIDVector.internal_native_empty(this_addr);
    }

    public int size() {
        return internal_native_size(native_address);
    }

    public static int internal_native_size(long this_addr) {
        return jolt.physics.body.natives.JNI_BodyIDVector.internal_native_size(this_addr);
    }

    public BodyID at(int inIndex) {
        long addr = internal_native_at_addr(native_address, inIndex);
        if (addr == 0)
            return BodyID.NULL;
        if (BodyID_TEMP_GEN_0 == null)
            BodyID_TEMP_GEN_0 = BodyID.native_new();
        BodyID_TEMP_GEN_0.internal_reset(addr, false);
        return BodyID_TEMP_GEN_0;
    }

    public static long internal_native_at_addr(long this_addr, int inIndex) {
        return jolt.physics.body.natives.JNI_BodyIDVector.internal_native_at_addr(this_addr, inIndex);
    }

    public void push_back(BodyID inBodyID) {
        internal_native_push_back(native_address, inBodyID.native_address);
    }

    public static void internal_native_push_back(long this_addr, long inBodyID_addr) {
        jolt.physics.body.natives.JNI_BodyIDVector.internal_native_push_back(this_addr, inBodyID_addr);
    }

    public void reserve(int inSize) {
        internal_native_reserve(native_address, inSize);
    }

    public static void internal_native_reserve(long this_addr, int inSize) {
        jolt.physics.body.natives.JNI_BodyIDVector.internal_native_reserve(this_addr, inSize);
    }

    public void resize(int inSize) {
        internal_native_resize(native_address, inSize);
    }

    public static void internal_native_resize(long this_addr, int inSize) {
        jolt.physics.body.natives.JNI_BodyIDVector.internal_native_resize(this_addr, inSize);
    }

    public void clear() {
        internal_native_clear(native_address);
    }

    public static void internal_native_clear(long this_addr) {
        jolt.physics.body.natives.JNI_BodyIDVector.internal_native_clear(this_addr);
    }
}
