/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import jolt.physics.softbody.CastRayCollector;

public final class CastRayAnyHitCollisionCollector extends CastRayCollector {

    static public final CastRayAnyHitCollisionCollector NULL = CastRayAnyHitCollisionCollector.native_new();

    public CastRayAnyHitCollisionCollector() {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CastRayAnyHitCollisionCollector(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static CastRayAnyHitCollisionCollector native_new() {
        return new CastRayAnyHitCollisionCollector((byte) 0, (char) 0);
    }

    public boolean HadHit() {
        return false;
    }

    public RayCastResult get_mHit() {
        return null;
    }

    public void set_mHit(RayCastResult mHit) {
    }
}
