/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import jolt.physics.softbody.CollidePointCollector;

public final class CollidePointAllHitCollisionCollector extends CollidePointCollector {

    static public final CollidePointAllHitCollisionCollector NULL = CollidePointAllHitCollisionCollector.native_new();

    public CollidePointAllHitCollisionCollector() {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CollidePointAllHitCollisionCollector(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static CollidePointAllHitCollisionCollector native_new() {
        return new CollidePointAllHitCollisionCollector((byte) 0, (char) 0);
    }

    public void Sort() {
    }

    public boolean HadHit() {
        return false;
    }

    public ArrayCollidePointResult get_mHits() {
        return null;
    }

    public void set_mHits(ArrayCollidePointResult mHits) {
    }
}
