/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision;

import jolt.enums.EBackFaceMode;

public final class CollideShapeSettings extends CollideSettingsBase {

    static public final CollideShapeSettings NULL = CollideShapeSettings.native_new();

    public CollideShapeSettings() {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CollideShapeSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static CollideShapeSettings native_new() {
        return new CollideShapeSettings((byte) 0, (char) 0);
    }

    public float get_mMaxSeparationDistance() {
        return 0;
    }

    public void set_mMaxSeparationDistance(float mMaxSeparationDistance) {
    }

    public EBackFaceMode get_mBackFaceMode() {
        return null;
    }

    public void set_mBackFaceMode(EBackFaceMode mBackFaceMode) {
    }

    public float get_mInternalEdgeRemovalVertexToleranceSq() {
        return 0;
    }

    public void set_mInternalEdgeRemovalVertexToleranceSq(float mInternalEdgeRemovalVertexToleranceSq) {
    }
}
