/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape;

import jolt.math.Vec3;
import jolt.physics.collision.PhysicsMaterial;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class BoxShapeSettings extends ConvexShapeSettings {

    private Vec3 Vec3_TEMP_GEN_0;

    static public final BoxShapeSettings NULL = BoxShapeSettings.native_new();

    public BoxShapeSettings(Vec3 inHalfExtent, float inConvexRadius, PhysicsMaterial inMaterial) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_Vec3_float_PhysicsMaterial_addr(inHalfExtent.native_address, inConvexRadius, inMaterial.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_Vec3_float_PhysicsMaterial_addr(long inHalfExtent_addr, float inConvexRadius, long inMaterial_addr) {
        try {
            return (long) FFMHandles.internal_native_create_Vec3_float_PhysicsMaterial_addr__JFJ.invokeExact(inHalfExtent_addr, inConvexRadius, inMaterial_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public BoxShapeSettings(Vec3 inHalfExtent, float inConvexRadius) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_Vec3_float_addr(inHalfExtent.native_address, inConvexRadius);
        internal_reset(addr, true);
    }

    public static long internal_native_create_Vec3_float_addr(long inHalfExtent_addr, float inConvexRadius) {
        try {
            return (long) FFMHandles.internal_native_create_Vec3_float_addr__JF.invokeExact(inHalfExtent_addr, inConvexRadius);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public BoxShapeSettings(Vec3 inHalfExtent) {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_Vec3_addr(inHalfExtent.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_Vec3_addr(long inHalfExtent_addr) {
        try {
            return (long) FFMHandles.internal_native_create_Vec3_addr__J.invokeExact(inHalfExtent_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected BoxShapeSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static BoxShapeSettings native_new() {
        return new BoxShapeSettings((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 get_mHalfExtent() {
        long addr = internal_native_get_mHalfExtent_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.native_new();
        Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return Vec3_TEMP_GEN_0;
    }

    public static long internal_native_get_mHalfExtent_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mHalfExtent_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mHalfExtent(Vec3 mHalfExtent) {
        internal_native_set_mHalfExtent(native_address, mHalfExtent.native_address);
    }

    public static void internal_native_set_mHalfExtent(long this_addr, long mHalfExtent_addr) {
        try {
            FFMHandles.internal_native_set_mHalfExtent__JJ.invokeExact(this_addr, mHalfExtent_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float get_mConvexRadius() {
        return internal_native_get_mConvexRadius(native_address);
    }

    public static float internal_native_get_mConvexRadius(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_get_mConvexRadius__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mConvexRadius(float mConvexRadius) {
        internal_native_set_mConvexRadius(native_address, mConvexRadius);
    }

    public static void internal_native_set_mConvexRadius(long this_addr, float mConvexRadius) {
        try {
            FFMHandles.internal_native_set_mConvexRadius__JF.invokeExact(this_addr, mConvexRadius);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_Vec3_float_PhysicsMaterial_addr__JFJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_shape_boxshapesettings_create_vec3_float_physicsmaterial_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_Vec3_float_addr__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_shape_boxshapesettings_create_vec3_float_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_create_Vec3_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_shape_boxshapesettings_create_vec3_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_shape_boxshapesettings_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mHalfExtent_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_shape_boxshapesettings_get_mhalfextent_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mHalfExtent__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_shape_boxshapesettings_set_mhalfextent", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mConvexRadius__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_shape_boxshapesettings_get_mconvexradius", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mConvexRadius__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_collision_shape_boxshapesettings_set_mconvexradius", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));
    }
}
