/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt;

import com.github.xpenatan.jParser.api.NativeObject;

public final class HeightFieldShapeConstantValues extends NativeObject {

    static public final HeightFieldShapeConstantValues NULL = HeightFieldShapeConstantValues.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected HeightFieldShapeConstantValues(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static HeightFieldShapeConstantValues native_new() {
        return new HeightFieldShapeConstantValues((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.natives.JNI_HeightFieldShapeConstantValues.internal_native_deleteNative(this_addr);
    }

    public static float get_cNoCollisionValue() {
        return internal_native_get_cNoCollisionValue();
    }

    public static float internal_native_get_cNoCollisionValue() {
        return jolt.natives.JNI_HeightFieldShapeConstantValues.internal_native_get_cNoCollisionValue();
    }

    public static int get_cMaxBitsPerSample() {
        return internal_native_get_cMaxBitsPerSample();
    }

    public static int internal_native_get_cMaxBitsPerSample() {
        return jolt.natives.JNI_HeightFieldShapeConstantValues.internal_native_get_cMaxBitsPerSample();
    }
}
