/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.Vec3;

public final class RVec3 extends NativeObject {

    static private RVec3 RVec3_TEMP_STATIC_GEN_0;

    static private RVec3 RVec3_TEMP_STATIC_GEN_1;

    static private RVec3 RVec3_TEMP_STATIC_GEN_2;

    static private RVec3 RVec3_TEMP_STATIC_GEN_3;

    static private RVec3 RVec3_TEMP_STATIC_GEN_4;

    static private RVec3 RVec3_TEMP_STATIC_GEN_5;

    static private RVec3 RVec3_TEMP_STATIC_GEN_6;

    static private RVec3 RVec3_TEMP_STATIC_GEN_7;

    static private RVec3 RVec3_TEMP_STATIC_GEN_8;

    private RVec3 RVec3_TEMP_GEN_0;

    private RVec3 RVec3_TEMP_GEN_1;

    private RVec3 RVec3_TEMP_GEN_2;

    private RVec3 RVec3_TEMP_GEN_3;

    private RVec3 RVec3_TEMP_GEN_4;

    private RVec3 RVec3_TEMP_GEN_5;

    private RVec3 RVec3_TEMP_GEN_6;

    private RVec3 RVec3_TEMP_GEN_7;

    private RVec3 RVec3_TEMP_GEN_8;

    private RVec3 RVec3_TEMP_GEN_9;

    private RVec3 RVec3_TEMP_GEN_10;

    private RVec3 RVec3_TEMP_GEN_11;

    static public final RVec3 NULL = RVec3.native_new();

    public RVec3() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return jolt.natives.JNI_RVec3.internal_native_create_addr();
    }

    public RVec3(float inX, float inY, float inZ) {
        long addr = internal_native_create_float_float_float_addr(inX, inY, inZ);
        internal_reset(addr, true);
    }

    public static long internal_native_create_float_float_float_addr(float inX, float inY, float inZ) {
        return jolt.natives.JNI_RVec3.internal_native_create_float_float_float_addr(inX, inY, inZ);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected RVec3(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static RVec3 native_new() {
        return new RVec3((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.natives.JNI_RVec3.internal_native_deleteNative(this_addr);
    }

    public static RVec3 sZero() {
        long addr = internal_native_sZero_addr();
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_STATIC_GEN_0 == null)
            RVec3_TEMP_STATIC_GEN_0 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return RVec3_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_sZero_addr() {
        return jolt.natives.JNI_RVec3.internal_native_sZero_addr();
    }

    public static RVec3 sOne() {
        long addr = internal_native_sOne_addr();
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_STATIC_GEN_1 == null)
            RVec3_TEMP_STATIC_GEN_1 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_1.internal_reset(addr, false);
        return RVec3_TEMP_STATIC_GEN_1;
    }

    public static long internal_native_sOne_addr() {
        return jolt.natives.JNI_RVec3.internal_native_sOne_addr();
    }

    public static RVec3 sAxisX() {
        long addr = internal_native_sAxisX_addr();
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_STATIC_GEN_2 == null)
            RVec3_TEMP_STATIC_GEN_2 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_2.internal_reset(addr, false);
        return RVec3_TEMP_STATIC_GEN_2;
    }

    public static long internal_native_sAxisX_addr() {
        return jolt.natives.JNI_RVec3.internal_native_sAxisX_addr();
    }

    public static RVec3 sAxisY() {
        long addr = internal_native_sAxisY_addr();
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_STATIC_GEN_3 == null)
            RVec3_TEMP_STATIC_GEN_3 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_3.internal_reset(addr, false);
        return RVec3_TEMP_STATIC_GEN_3;
    }

    public static long internal_native_sAxisY_addr() {
        return jolt.natives.JNI_RVec3.internal_native_sAxisY_addr();
    }

    public static RVec3 sAxisZ() {
        long addr = internal_native_sAxisZ_addr();
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_STATIC_GEN_4 == null)
            RVec3_TEMP_STATIC_GEN_4 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_4.internal_reset(addr, false);
        return RVec3_TEMP_STATIC_GEN_4;
    }

    public static long internal_native_sAxisZ_addr() {
        return jolt.natives.JNI_RVec3.internal_native_sAxisZ_addr();
    }

    public static RVec3 sReplicate(float inValue) {
        long addr = internal_native_sReplicate_addr(inValue);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_STATIC_GEN_5 == null)
            RVec3_TEMP_STATIC_GEN_5 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_5.internal_reset(addr, false);
        return RVec3_TEMP_STATIC_GEN_5;
    }

    public static long internal_native_sReplicate_addr(float inValue) {
        return jolt.natives.JNI_RVec3.internal_native_sReplicate_addr(inValue);
    }

    public static RVec3 sMin(RVec3 inLHS, RVec3 inRHS) {
        long addr = internal_native_sMin_addr(inLHS.native_address, inRHS.native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_STATIC_GEN_6 == null)
            RVec3_TEMP_STATIC_GEN_6 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_6.internal_reset(addr, false);
        return RVec3_TEMP_STATIC_GEN_6;
    }

    public static long internal_native_sMin_addr(long inLHS_addr, long inRHS_addr) {
        return jolt.natives.JNI_RVec3.internal_native_sMin_addr(inLHS_addr, inRHS_addr);
    }

    public static RVec3 sMax(RVec3 inLHS, RVec3 inRHS) {
        long addr = internal_native_sMax_addr(inLHS.native_address, inRHS.native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_STATIC_GEN_7 == null)
            RVec3_TEMP_STATIC_GEN_7 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_7.internal_reset(addr, false);
        return RVec3_TEMP_STATIC_GEN_7;
    }

    public static long internal_native_sMax_addr(long inLHS_addr, long inRHS_addr) {
        return jolt.natives.JNI_RVec3.internal_native_sMax_addr(inLHS_addr, inRHS_addr);
    }

    public static RVec3 sClamp(RVec3 inValue, RVec3 inMin, RVec3 inMax) {
        long addr = internal_native_sClamp_addr(inValue.native_address, inMin.native_address, inMax.native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_STATIC_GEN_8 == null)
            RVec3_TEMP_STATIC_GEN_8 = RVec3.native_new();
        RVec3_TEMP_STATIC_GEN_8.internal_reset(addr, false);
        return RVec3_TEMP_STATIC_GEN_8;
    }

    public static long internal_native_sClamp_addr(long inValue_addr, long inMin_addr, long inMax_addr) {
        return jolt.natives.JNI_RVec3.internal_native_sClamp_addr(inValue_addr, inMin_addr, inMax_addr);
    }

    public float GetComponent(int inCoordinate) {
        return internal_native_GetComponent(native_address, inCoordinate);
    }

    public static float internal_native_GetComponent(long this_addr, int inCoordinate) {
        return jolt.natives.JNI_RVec3.internal_native_GetComponent(this_addr, inCoordinate);
    }

    public boolean Equals(RVec3 inV) {
        return internal_native_Equals(native_address, inV.native_address);
    }

    public static boolean internal_native_Equals(long this_addr, long inV_addr) {
        return jolt.natives.JNI_RVec3.internal_native_Equals(this_addr, inV_addr);
    }

    public boolean NotEquals(RVec3 inV) {
        return internal_native_NotEquals(native_address, inV.native_address);
    }

    public static boolean internal_native_NotEquals(long this_addr, long inV_addr) {
        return jolt.natives.JNI_RVec3.internal_native_NotEquals(this_addr, inV_addr);
    }

    public float LengthSq() {
        return internal_native_LengthSq(native_address);
    }

    public static float internal_native_LengthSq(long this_addr) {
        return jolt.natives.JNI_RVec3.internal_native_LengthSq(this_addr);
    }

    public float Length() {
        return internal_native_Length(native_address);
    }

    public static float internal_native_Length(long this_addr) {
        return jolt.natives.JNI_RVec3.internal_native_Length(this_addr);
    }

    public RVec3 Normalized() {
        long addr = internal_native_Normalized_addr(native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_GEN_0 == null)
            RVec3_TEMP_GEN_0 = RVec3.native_new();
        RVec3_TEMP_GEN_0.internal_reset(addr, false);
        return RVec3_TEMP_GEN_0;
    }

    public static long internal_native_Normalized_addr(long this_addr) {
        return jolt.natives.JNI_RVec3.internal_native_Normalized_addr(this_addr);
    }

    public float GetX() {
        return internal_native_GetX(native_address);
    }

    public static float internal_native_GetX(long this_addr) {
        return jolt.natives.JNI_RVec3.internal_native_GetX(this_addr);
    }

    public float GetY() {
        return internal_native_GetY(native_address);
    }

    public static float internal_native_GetY(long this_addr) {
        return jolt.natives.JNI_RVec3.internal_native_GetY(this_addr);
    }

    public float GetZ() {
        return internal_native_GetZ(native_address);
    }

    public static float internal_native_GetZ(long this_addr) {
        return jolt.natives.JNI_RVec3.internal_native_GetZ(this_addr);
    }

    public void SetX(float inX) {
        internal_native_SetX(native_address, inX);
    }

    public static void internal_native_SetX(long this_addr, float inX) {
        jolt.natives.JNI_RVec3.internal_native_SetX(this_addr, inX);
    }

    public void SetY(float inY) {
        internal_native_SetY(native_address, inY);
    }

    public static void internal_native_SetY(long this_addr, float inY) {
        jolt.natives.JNI_RVec3.internal_native_SetY(this_addr, inY);
    }

    public void SetZ(float inZ) {
        internal_native_SetZ(native_address, inZ);
    }

    public static void internal_native_SetZ(long this_addr, float inZ) {
        jolt.natives.JNI_RVec3.internal_native_SetZ(this_addr, inZ);
    }

    public void Set(float inX, float inY, float inZ) {
        internal_native_Set(native_address, inX, inY, inZ);
    }

    public static void internal_native_Set(long this_addr, float inX, float inY, float inZ) {
        jolt.natives.JNI_RVec3.internal_native_Set(this_addr, inX, inY, inZ);
    }

    public void SetComponent(int inCoordinate, float inValue) {
        internal_native_SetComponent(native_address, inCoordinate, inValue);
    }

    public static void internal_native_SetComponent(long this_addr, int inCoordinate, float inValue) {
        jolt.natives.JNI_RVec3.internal_native_SetComponent(this_addr, inCoordinate, inValue);
    }

    public boolean IsNearZero(float inMaxDistSq) {
        return internal_native_IsNearZero(native_address, inMaxDistSq);
    }

    public static boolean internal_native_IsNearZero(long this_addr, float inMaxDistSq) {
        return jolt.natives.JNI_RVec3.internal_native_IsNearZero(this_addr, inMaxDistSq);
    }

    public boolean IsNearZero() {
        return internal_native_IsNearZero(native_address);
    }

    public static boolean internal_native_IsNearZero(long this_addr) {
        return jolt.natives.JNI_RVec3.internal_native_IsNearZero(this_addr);
    }

    public boolean IsClose(RVec3 inV, float inMaxDistSq) {
        return internal_native_IsClose(native_address, inV.native_address, inMaxDistSq);
    }

    public static boolean internal_native_IsClose(long this_addr, long inV_addr, float inMaxDistSq) {
        return jolt.natives.JNI_RVec3.internal_native_IsClose(this_addr, inV_addr, inMaxDistSq);
    }

    public boolean IsClose(RVec3 inV) {
        return internal_native_IsClose(native_address, inV.native_address);
    }

    public static boolean internal_native_IsClose(long this_addr, long inV_addr) {
        return jolt.natives.JNI_RVec3.internal_native_IsClose(this_addr, inV_addr);
    }

    public boolean IsNormalized(float inTolerance) {
        return internal_native_IsNormalized(native_address, inTolerance);
    }

    public static boolean internal_native_IsNormalized(long this_addr, float inTolerance) {
        return jolt.natives.JNI_RVec3.internal_native_IsNormalized(this_addr, inTolerance);
    }

    public boolean IsNormalized() {
        return internal_native_IsNormalized(native_address);
    }

    public static boolean internal_native_IsNormalized(long this_addr) {
        return jolt.natives.JNI_RVec3.internal_native_IsNormalized(this_addr);
    }

    public RVec3 Abs() {
        long addr = internal_native_Abs_addr(native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_GEN_1 == null)
            RVec3_TEMP_GEN_1 = RVec3.native_new();
        RVec3_TEMP_GEN_1.internal_reset(addr, false);
        return RVec3_TEMP_GEN_1;
    }

    public static long internal_native_Abs_addr(long this_addr) {
        return jolt.natives.JNI_RVec3.internal_native_Abs_addr(this_addr);
    }

    public RVec3 Reciprocal() {
        long addr = internal_native_Reciprocal_addr(native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_GEN_2 == null)
            RVec3_TEMP_GEN_2 = RVec3.native_new();
        RVec3_TEMP_GEN_2.internal_reset(addr, false);
        return RVec3_TEMP_GEN_2;
    }

    public static long internal_native_Reciprocal_addr(long this_addr) {
        return jolt.natives.JNI_RVec3.internal_native_Reciprocal_addr(this_addr);
    }

    public RVec3 Cross(RVec3 inRHS) {
        long addr = internal_native_Cross_addr(native_address, inRHS.native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_GEN_3 == null)
            RVec3_TEMP_GEN_3 = RVec3.native_new();
        RVec3_TEMP_GEN_3.internal_reset(addr, false);
        return RVec3_TEMP_GEN_3;
    }

    public static long internal_native_Cross_addr(long this_addr, long inRHS_addr) {
        return jolt.natives.JNI_RVec3.internal_native_Cross_addr(this_addr, inRHS_addr);
    }

    public float Dot(RVec3 inRHS) {
        return internal_native_Dot(native_address, inRHS.native_address);
    }

    public static float internal_native_Dot(long this_addr, long inRHS_addr) {
        return jolt.natives.JNI_RVec3.internal_native_Dot(this_addr, inRHS_addr);
    }

    public RVec3 Add(Vec3 inV) {
        internal_native_Add_addr(native_address, inV.native_address);
        return this;
    }

    public static long internal_native_Add_addr(long this_addr, long inV_addr) {
        return jolt.natives.JNI_RVec3.internal_native_Add_addr(this_addr, inV_addr);
    }

    public RVec3 Sub(Vec3 inV) {
        internal_native_Sub_addr(native_address, inV.native_address);
        return this;
    }

    public static long internal_native_Sub_addr(long this_addr, long inV_addr) {
        return jolt.natives.JNI_RVec3.internal_native_Sub_addr(this_addr, inV_addr);
    }

    public RVec3 Mul(float inV) {
        internal_native_Mul_addr(native_address, inV);
        return this;
    }

    public static long internal_native_Mul_addr(long this_addr, float inV) {
        return jolt.natives.JNI_RVec3.internal_native_Mul_addr(this_addr, inV);
    }

    public RVec3 Div(float inV) {
        internal_native_Div_addr(native_address, inV);
        return this;
    }

    public static long internal_native_Div_addr(long this_addr, float inV) {
        return jolt.natives.JNI_RVec3.internal_native_Div_addr(this_addr, inV);
    }

    public RVec3 MulRVec3(RVec3 inV) {
        long addr = internal_native_MulRVec3_addr(native_address, inV.native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_GEN_4 == null)
            RVec3_TEMP_GEN_4 = RVec3.native_new();
        RVec3_TEMP_GEN_4.internal_reset(addr, false);
        return RVec3_TEMP_GEN_4;
    }

    public static long internal_native_MulRVec3_addr(long this_addr, long inV_addr) {
        return jolt.natives.JNI_RVec3.internal_native_MulRVec3_addr(this_addr, inV_addr);
    }

    public RVec3 MulFloat(float inV) {
        long addr = internal_native_MulFloat_addr(native_address, inV);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_GEN_5 == null)
            RVec3_TEMP_GEN_5 = RVec3.native_new();
        RVec3_TEMP_GEN_5.internal_reset(addr, false);
        return RVec3_TEMP_GEN_5;
    }

    public static long internal_native_MulFloat_addr(long this_addr, float inV) {
        return jolt.natives.JNI_RVec3.internal_native_MulFloat_addr(this_addr, inV);
    }

    public RVec3 DivRVec3(RVec3 inV) {
        long addr = internal_native_DivRVec3_addr(native_address, inV.native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_GEN_6 == null)
            RVec3_TEMP_GEN_6 = RVec3.native_new();
        RVec3_TEMP_GEN_6.internal_reset(addr, false);
        return RVec3_TEMP_GEN_6;
    }

    public static long internal_native_DivRVec3_addr(long this_addr, long inV_addr) {
        return jolt.natives.JNI_RVec3.internal_native_DivRVec3_addr(this_addr, inV_addr);
    }

    public RVec3 DivFloat(float inV) {
        long addr = internal_native_DivFloat_addr(native_address, inV);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_GEN_7 == null)
            RVec3_TEMP_GEN_7 = RVec3.native_new();
        RVec3_TEMP_GEN_7.internal_reset(addr, false);
        return RVec3_TEMP_GEN_7;
    }

    public static long internal_native_DivFloat_addr(long this_addr, float inV) {
        return jolt.natives.JNI_RVec3.internal_native_DivFloat_addr(this_addr, inV);
    }

    public RVec3 AddRVec3(RVec3 inV) {
        long addr = internal_native_AddRVec3_addr(native_address, inV.native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_GEN_8 == null)
            RVec3_TEMP_GEN_8 = RVec3.native_new();
        RVec3_TEMP_GEN_8.internal_reset(addr, false);
        return RVec3_TEMP_GEN_8;
    }

    public static long internal_native_AddRVec3_addr(long this_addr, long inV_addr) {
        return jolt.natives.JNI_RVec3.internal_native_AddRVec3_addr(this_addr, inV_addr);
    }

    public RVec3 SubRVec3(RVec3 inV) {
        long addr = internal_native_SubRVec3_addr(native_address, inV.native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_GEN_9 == null)
            RVec3_TEMP_GEN_9 = RVec3.native_new();
        RVec3_TEMP_GEN_9.internal_reset(addr, false);
        return RVec3_TEMP_GEN_9;
    }

    public static long internal_native_SubRVec3_addr(long this_addr, long inV_addr) {
        return jolt.natives.JNI_RVec3.internal_native_SubRVec3_addr(this_addr, inV_addr);
    }

    public RVec3 Sqrt() {
        long addr = internal_native_Sqrt_addr(native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_GEN_10 == null)
            RVec3_TEMP_GEN_10 = RVec3.native_new();
        RVec3_TEMP_GEN_10.internal_reset(addr, false);
        return RVec3_TEMP_GEN_10;
    }

    public static long internal_native_Sqrt_addr(long this_addr) {
        return jolt.natives.JNI_RVec3.internal_native_Sqrt_addr(this_addr);
    }

    public RVec3 GetSign() {
        long addr = internal_native_GetSign_addr(native_address);
        if (addr == 0)
            return RVec3.NULL;
        if (RVec3_TEMP_GEN_11 == null)
            RVec3_TEMP_GEN_11 = RVec3.native_new();
        RVec3_TEMP_GEN_11.internal_reset(addr, false);
        return RVec3_TEMP_GEN_11;
    }

    public static long internal_native_GetSign_addr(long this_addr) {
        return jolt.natives.JNI_RVec3.internal_native_GetSign_addr(this_addr);
    }
}
