/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.compute.natives;

import jolt.compute.*;

final public class JNI_ComputeShaderResult {

    public static native void internal_native_deleteNative(long this_addr);

    public static native boolean internal_native_IsValid(long this_addr);

    public static native boolean internal_native_HasError(long this_addr);

    public static native long internal_native_GetError_addr(long this_addr);

    public static native long internal_native_Get_addr(long this_addr);

    public static native void internal_native_Clear(long this_addr);
}
