/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape;

import jolt.math.Vec3;
import jolt.physics.collision.PhysicsMaterial;

public final class BoxShape extends ConvexShape {

    static public final BoxShape NULL = BoxShape.native_new();

    public BoxShape(Vec3 inHalfExtent, float inConvexRadius, PhysicsMaterial inMaterial) {
        super((byte) 1, (char) 1);
    }

    public BoxShape(Vec3 inHalfExtent, float inConvexRadius) {
        super((byte) 1, (char) 1);
    }

    public BoxShape(Vec3 inHalfExtent) {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected BoxShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static BoxShape native_new() {
        return new BoxShape((byte) 0, (char) 0);
    }

    public Vec3 GetHalfExtent() {
        return null;
    }
}
