/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape;

import jolt.physics.collision.PhysicsMaterial;

public final class CylinderShapeSettings extends ConvexShapeSettings {

    static public final CylinderShapeSettings NULL = CylinderShapeSettings.native_new();

    public CylinderShapeSettings(float inHalfHeight, float inRadius, float inConvexRadius, PhysicsMaterial inMaterial) {
        super((byte) 1, (char) 1);
    }

    public CylinderShapeSettings(float inHalfHeight, float inRadius, float inConvexRadius) {
        super((byte) 1, (char) 1);
    }

    public CylinderShapeSettings(float inHalfHeight, float inRadius) {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected CylinderShapeSettings(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static CylinderShapeSettings native_new() {
        return new CylinderShapeSettings((byte) 0, (char) 0);
    }

    public float get_mHalfHeight() {
        return 0;
    }

    public void set_mHalfHeight(float mHalfHeight) {
    }

    public float get_mRadius() {
        return 0;
    }

    public void set_mRadius(float mRadius) {
    }

    public float get_mConvexRadius() {
        return 0;
    }

    public void set_mConvexRadius(float mConvexRadius) {
    }
}
