/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape;

import jolt.math.Vec3;
import jolt.math.FloatMemRef;
import jolt.core.TempAllocator;
import jolt.math.Uint8MemRef;
import jolt.physics.collision.PhysicsMaterialList;

public final class HeightFieldShape extends Shape {

    static public final HeightFieldShape NULL = HeightFieldShape.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected HeightFieldShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static HeightFieldShape native_new() {
        return new HeightFieldShape((byte) 0, (char) 0);
    }

    public int GetSampleCount() {
        return 0;
    }

    public int GetBlockSize() {
        return 0;
    }

    public Vec3 GetPosition(int inX, int inY) {
        return null;
    }

    public boolean IsNoCollision(int inX, int inY) {
        return false;
    }

    public float GetMinHeightValue() {
        return 0;
    }

    public float GetMaxHeightValue() {
        return 0;
    }

    public void GetHeights(int inX, int inY, int inSizeX, int inSizeY, FloatMemRef outHeights, int inHeightsStride) {
    }

    public void SetHeights(int inX, int inY, int inSizeX, int inSizeY, FloatMemRef inHeights, int inHeightsStride, TempAllocator inAllocator, float inActiveEdgeCosThresholdAngle) {
    }

    public void SetHeights(int inX, int inY, int inSizeX, int inSizeY, FloatMemRef inHeights, int inHeightsStride, TempAllocator inAllocator) {
    }

    public void GetMaterials(int inX, int inY, int inSizeX, int inSizeY, Uint8MemRef outMaterials, int inMaterialsStride) {
    }

    public boolean SetMaterials(int inX, int inY, int inSizeX, int inSizeY, Uint8MemRef inMaterials, int inMaterialsStride, PhysicsMaterialList inMaterialList, TempAllocator inAllocator) {
        return false;
    }
}
