/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.collision.shape;

import jolt.geometry.Plane;
import jolt.physics.collision.PhysicsMaterial;

public final class PlaneShape extends Shape {

    static public final PlaneShape NULL = PlaneShape.native_new();

    public PlaneShape(Plane inPlane, PhysicsMaterial inMaterial, float inHalfExtent) {
        super((byte) 1, (char) 1);
    }

    public PlaneShape(Plane inPlane, PhysicsMaterial inMaterial) {
        super((byte) 1, (char) 1);
    }

    public PlaneShape(Plane inPlane) {
        super((byte) 1, (char) 1);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected PlaneShape(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static PlaneShape native_new() {
        return new PlaneShape((byte) 0, (char) 0);
    }

    public void SetMaterial(PhysicsMaterial inMaterial) {
    }

    public Plane GetPlane() {
        return null;
    }

    public float GetHalfExtent() {
        return 0;
    }
}
