/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.math;

import com.github.xpenatan.jParser.api.NativeObject;

public final class Mat44 extends NativeObject {

    static private Mat44 Mat44_TEMP_STATIC_GEN_0;

    static private Mat44 Mat44_TEMP_STATIC_GEN_1;

    static private Mat44 Mat44_TEMP_STATIC_GEN_2;

    static private Mat44 Mat44_TEMP_STATIC_GEN_3;

    static private Mat44 Mat44_TEMP_STATIC_GEN_4;

    static private Mat44 Mat44_TEMP_STATIC_GEN_5;

    static private Mat44 Mat44_TEMP_STATIC_GEN_6;

    static private Mat44 Mat44_TEMP_STATIC_GEN_7;

    static private Mat44 Mat44_TEMP_STATIC_GEN_8;

    static private Mat44 Mat44_TEMP_STATIC_GEN_9;

    static private Mat44 Mat44_TEMP_STATIC_GEN_10;

    static private Mat44 Mat44_TEMP_STATIC_GEN_11;

    static private Mat44 Mat44_TEMP_STATIC_GEN_12;

    static private Mat44 Mat44_TEMP_STATIC_GEN_13;

    static private Mat44 Mat44_TEMP_STATIC_GEN_14;

    static private Mat44 Mat44_TEMP_STATIC_GEN_15;

    static private Mat44 Mat44_TEMP_STATIC_GEN_16;

    static private Mat44 Mat44_TEMP_STATIC_GEN_17;

    private Vec3 Vec3_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_1;

    private Vec3 Vec3_TEMP_GEN_2;

    private Vec3 Vec3_TEMP_GEN_3;

    private Vec4 Vec4_TEMP_GEN_0;

    private Mat44 Mat44_TEMP_GEN_0;

    private Mat44 Mat44_TEMP_GEN_1;

    private Quat Quat_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_4;

    private Mat44 Mat44_TEMP_GEN_2;

    private Mat44 Mat44_TEMP_GEN_3;

    private Vec3 Vec3_TEMP_GEN_5;

    private Vec4 Vec4_TEMP_GEN_1;

    private Mat44 Mat44_TEMP_GEN_4;

    private Mat44 Mat44_TEMP_GEN_5;

    private Vec3 Vec3_TEMP_GEN_6;

    private Vec3 Vec3_TEMP_GEN_7;

    private Mat44 Mat44_TEMP_GEN_6;

    private Mat44 Mat44_TEMP_GEN_7;

    private Mat44 Mat44_TEMP_GEN_8;

    private Mat44 Mat44_TEMP_GEN_9;

    private Mat44 Mat44_TEMP_GEN_10;

    private Mat44 Mat44_TEMP_GEN_11;

    private Mat44 Mat44_TEMP_GEN_12;

    private Mat44 Mat44_TEMP_GEN_13;

    private Mat44 Mat44_TEMP_GEN_14;

    private Mat44 Mat44_TEMP_GEN_15;

    private Mat44 Mat44_TEMP_GEN_16;

    private Mat44 Mat44_TEMP_GEN_17;

    private Mat44 Mat44_TEMP_GEN_18;

    private Mat44 Mat44_TEMP_GEN_19;

    private Vec3 Vec3_TEMP_GEN_8;

    private Vec4 Vec4_TEMP_GEN_2;

    static public final Mat44 NULL = Mat44.native_new();

    public Mat44() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return jolt.math.natives.JNI_Mat44.internal_native_create_addr();
    }

    public Mat44(Vec4 inC1, Vec4 inC2, Vec4 inC3, Vec4 inC4) {
        long addr = internal_native_create_Vec4_Vec4_Vec4_Vec4_addr(inC1.native_address, inC2.native_address, inC3.native_address, inC4.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_Vec4_Vec4_Vec4_Vec4_addr(long inC1_addr, long inC2_addr, long inC3_addr, long inC4_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_create_Vec4_Vec4_Vec4_Vec4_addr(inC1_addr, inC2_addr, inC3_addr, inC4_addr);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected Mat44(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static Mat44 native_new() {
        return new Mat44((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.math.natives.JNI_Mat44.internal_native_deleteNative(this_addr);
    }

    public static Mat44 sZero() {
        long addr = internal_native_sZero_addr();
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_0 == null)
            Mat44_TEMP_STATIC_GEN_0 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_sZero_addr() {
        return jolt.math.natives.JNI_Mat44.internal_native_sZero_addr();
    }

    public static Mat44 sIdentity() {
        long addr = internal_native_sIdentity_addr();
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_1 == null)
            Mat44_TEMP_STATIC_GEN_1 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_1.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_1;
    }

    public static long internal_native_sIdentity_addr() {
        return jolt.math.natives.JNI_Mat44.internal_native_sIdentity_addr();
    }

    public static Mat44 sRotationX(float inX) {
        long addr = internal_native_sRotationX_addr(inX);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_2 == null)
            Mat44_TEMP_STATIC_GEN_2 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_2.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_2;
    }

    public static long internal_native_sRotationX_addr(float inX) {
        return jolt.math.natives.JNI_Mat44.internal_native_sRotationX_addr(inX);
    }

    public static Mat44 sRotationY(float inY) {
        long addr = internal_native_sRotationY_addr(inY);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_3 == null)
            Mat44_TEMP_STATIC_GEN_3 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_3.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_3;
    }

    public static long internal_native_sRotationY_addr(float inY) {
        return jolt.math.natives.JNI_Mat44.internal_native_sRotationY_addr(inY);
    }

    public static Mat44 sRotationZ(float inZ) {
        long addr = internal_native_sRotationZ_addr(inZ);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_4 == null)
            Mat44_TEMP_STATIC_GEN_4 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_4.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_4;
    }

    public static long internal_native_sRotationZ_addr(float inZ) {
        return jolt.math.natives.JNI_Mat44.internal_native_sRotationZ_addr(inZ);
    }

    public static Mat44 sRotation(Quat inQ) {
        long addr = internal_native_sRotation_addr(inQ.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_5 == null)
            Mat44_TEMP_STATIC_GEN_5 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_5.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_5;
    }

    public static long internal_native_sRotation_addr(long inQ_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_sRotation_addr(inQ_addr);
    }

    public static Mat44 sRotationAxisAngle(Vec3 inAxis, float inAngle) {
        long addr = internal_native_sRotationAxisAngle_addr(inAxis.native_address, inAngle);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_6 == null)
            Mat44_TEMP_STATIC_GEN_6 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_6.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_6;
    }

    public static long internal_native_sRotationAxisAngle_addr(long inAxis_addr, float inAngle) {
        return jolt.math.natives.JNI_Mat44.internal_native_sRotationAxisAngle_addr(inAxis_addr, inAngle);
    }

    public static Mat44 sTranslation(Vec3 inTranslation) {
        long addr = internal_native_sTranslation_addr(inTranslation.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_7 == null)
            Mat44_TEMP_STATIC_GEN_7 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_7.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_7;
    }

    public static long internal_native_sTranslation_addr(long inTranslation_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_sTranslation_addr(inTranslation_addr);
    }

    public static Mat44 sRotationTranslation(Quat inRotation, Vec3 inTranslation) {
        long addr = internal_native_sRotationTranslation_addr(inRotation.native_address, inTranslation.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_8 == null)
            Mat44_TEMP_STATIC_GEN_8 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_8.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_8;
    }

    public static long internal_native_sRotationTranslation_addr(long inRotation_addr, long inTranslation_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_sRotationTranslation_addr(inRotation_addr, inTranslation_addr);
    }

    public static Mat44 sInverseRotationTranslation(Quat inRotation, Vec3 inTranslation) {
        long addr = internal_native_sInverseRotationTranslation_addr(inRotation.native_address, inTranslation.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_9 == null)
            Mat44_TEMP_STATIC_GEN_9 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_9.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_9;
    }

    public static long internal_native_sInverseRotationTranslation_addr(long inRotation_addr, long inTranslation_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_sInverseRotationTranslation_addr(inRotation_addr, inTranslation_addr);
    }

    public static Mat44 sScale(float inScale) {
        long addr = internal_native_sScale_addr(inScale);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_10 == null)
            Mat44_TEMP_STATIC_GEN_10 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_10.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_10;
    }

    public static long internal_native_sScale_addr(float inScale) {
        return jolt.math.natives.JNI_Mat44.internal_native_sScale_addr(inScale);
    }

    public static Mat44 sScaleVec3(Vec3 inScale) {
        long addr = internal_native_sScaleVec3_addr(inScale.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_11 == null)
            Mat44_TEMP_STATIC_GEN_11 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_11.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_11;
    }

    public static long internal_native_sScaleVec3_addr(long inScale_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_sScaleVec3_addr(inScale_addr);
    }

    public static Mat44 sOuterProduct(Vec3 inV1, Vec3 inV2) {
        long addr = internal_native_sOuterProduct_addr(inV1.native_address, inV2.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_12 == null)
            Mat44_TEMP_STATIC_GEN_12 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_12.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_12;
    }

    public static long internal_native_sOuterProduct_addr(long inV1_addr, long inV2_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_sOuterProduct_addr(inV1_addr, inV2_addr);
    }

    public static Mat44 sCrossProduct(Vec3 inV) {
        long addr = internal_native_sCrossProduct_addr(inV.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_13 == null)
            Mat44_TEMP_STATIC_GEN_13 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_13.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_13;
    }

    public static long internal_native_sCrossProduct_addr(long inV_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_sCrossProduct_addr(inV_addr);
    }

    public static Mat44 sQuatLeftMultiply(Quat inQ) {
        long addr = internal_native_sQuatLeftMultiply_addr(inQ.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_14 == null)
            Mat44_TEMP_STATIC_GEN_14 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_14.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_14;
    }

    public static long internal_native_sQuatLeftMultiply_addr(long inQ_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_sQuatLeftMultiply_addr(inQ_addr);
    }

    public static Mat44 sQuatRightMultiply(Quat inQ) {
        long addr = internal_native_sQuatRightMultiply_addr(inQ.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_15 == null)
            Mat44_TEMP_STATIC_GEN_15 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_15.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_15;
    }

    public static long internal_native_sQuatRightMultiply_addr(long inQ_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_sQuatRightMultiply_addr(inQ_addr);
    }

    public static Mat44 sLookAt(Vec3 inPos, Vec3 inTarget, Vec3 inUp) {
        long addr = internal_native_sLookAt_addr(inPos.native_address, inTarget.native_address, inUp.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_16 == null)
            Mat44_TEMP_STATIC_GEN_16 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_16.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_16;
    }

    public static long internal_native_sLookAt_addr(long inPos_addr, long inTarget_addr, long inUp_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_sLookAt_addr(inPos_addr, inTarget_addr, inUp_addr);
    }

    public static Mat44 sPerspective(float inFovY, float inAspect, float inNear, float inFar) {
        long addr = internal_native_sPerspective_addr(inFovY, inAspect, inNear, inFar);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_STATIC_GEN_17 == null)
            Mat44_TEMP_STATIC_GEN_17 = Mat44.native_new();
        Mat44_TEMP_STATIC_GEN_17.internal_reset(addr, false);
        return Mat44_TEMP_STATIC_GEN_17;
    }

    public static long internal_native_sPerspective_addr(float inFovY, float inAspect, float inNear, float inFar) {
        return jolt.math.natives.JNI_Mat44.internal_native_sPerspective_addr(inFovY, inAspect, inNear, inFar);
    }

    public Vec3 GetAxisX() {
        long addr = internal_native_GetAxisX_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.native_new();
        Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetAxisX_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetAxisX_addr(this_addr);
    }

    public Vec3 GetAxisY() {
        long addr = internal_native_GetAxisY_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_1 == null)
            Vec3_TEMP_GEN_1 = Vec3.native_new();
        Vec3_TEMP_GEN_1.internal_reset(addr, false);
        return Vec3_TEMP_GEN_1;
    }

    public static long internal_native_GetAxisY_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetAxisY_addr(this_addr);
    }

    public Vec3 GetAxisZ() {
        long addr = internal_native_GetAxisZ_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_2 == null)
            Vec3_TEMP_GEN_2 = Vec3.native_new();
        Vec3_TEMP_GEN_2.internal_reset(addr, false);
        return Vec3_TEMP_GEN_2;
    }

    public static long internal_native_GetAxisZ_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetAxisZ_addr(this_addr);
    }

    public Vec3 GetDiagonal3() {
        long addr = internal_native_GetDiagonal3_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_3 == null)
            Vec3_TEMP_GEN_3 = Vec3.native_new();
        Vec3_TEMP_GEN_3.internal_reset(addr, false);
        return Vec3_TEMP_GEN_3;
    }

    public static long internal_native_GetDiagonal3_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetDiagonal3_addr(this_addr);
    }

    public Vec4 GetDiagonal4() {
        long addr = internal_native_GetDiagonal4_addr(native_address);
        if (addr == 0)
            return Vec4.NULL;
        if (Vec4_TEMP_GEN_0 == null)
            Vec4_TEMP_GEN_0 = Vec4.native_new();
        Vec4_TEMP_GEN_0.internal_reset(addr, false);
        return Vec4_TEMP_GEN_0;
    }

    public static long internal_native_GetDiagonal4_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetDiagonal4_addr(this_addr);
    }

    public Mat44 GetRotation() {
        long addr = internal_native_GetRotation_addr(native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_0 == null)
            Mat44_TEMP_GEN_0 = Mat44.native_new();
        Mat44_TEMP_GEN_0.internal_reset(addr, false);
        return Mat44_TEMP_GEN_0;
    }

    public static long internal_native_GetRotation_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetRotation_addr(this_addr);
    }

    public Mat44 GetRotationSafe() {
        long addr = internal_native_GetRotationSafe_addr(native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_1 == null)
            Mat44_TEMP_GEN_1 = Mat44.native_new();
        Mat44_TEMP_GEN_1.internal_reset(addr, false);
        return Mat44_TEMP_GEN_1;
    }

    public static long internal_native_GetRotationSafe_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetRotationSafe_addr(this_addr);
    }

    public Quat GetQuaternion() {
        long addr = internal_native_GetQuaternion_addr(native_address);
        if (addr == 0)
            return Quat.NULL;
        if (Quat_TEMP_GEN_0 == null)
            Quat_TEMP_GEN_0 = Quat.native_new();
        Quat_TEMP_GEN_0.internal_reset(addr, false);
        return Quat_TEMP_GEN_0;
    }

    public static long internal_native_GetQuaternion_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetQuaternion_addr(this_addr);
    }

    public Vec3 GetTranslation() {
        long addr = internal_native_GetTranslation_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_4 == null)
            Vec3_TEMP_GEN_4 = Vec3.native_new();
        Vec3_TEMP_GEN_4.internal_reset(addr, false);
        return Vec3_TEMP_GEN_4;
    }

    public static long internal_native_GetTranslation_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetTranslation_addr(this_addr);
    }

    public boolean Equals(Mat44 inV) {
        return internal_native_Equals(native_address, inV.native_address);
    }

    public static boolean internal_native_Equals(long this_addr, long inV_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Equals(this_addr, inV_addr);
    }

    public boolean NotEquals(Mat44 inV) {
        return internal_native_NotEquals(native_address, inV.native_address);
    }

    public static boolean internal_native_NotEquals(long this_addr, long inV_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_NotEquals(this_addr, inV_addr);
    }

    public boolean IsClose(Mat44 inM, float inMaxDistSq) {
        return internal_native_IsClose(native_address, inM.native_address, inMaxDistSq);
    }

    public static boolean internal_native_IsClose(long this_addr, long inM_addr, float inMaxDistSq) {
        return jolt.math.natives.JNI_Mat44.internal_native_IsClose(this_addr, inM_addr, inMaxDistSq);
    }

    public boolean IsClose(Mat44 inM) {
        return internal_native_IsClose(native_address, inM.native_address);
    }

    public static boolean internal_native_IsClose(long this_addr, long inM_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_IsClose(this_addr, inM_addr);
    }

    public Mat44 Set(Mat44 other) {
        internal_native_Set__0_addr(native_address, other.native_address);
        return this;
    }

    public static long internal_native_Set__0_addr(long this_addr, long other_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Set__0_addr(this_addr, other_addr);
    }

    public Mat44 Add(Mat44 inM) {
        internal_native_Add_addr(native_address, inM.native_address);
        return this;
    }

    public static long internal_native_Add_addr(long this_addr, long inM_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Add_addr(this_addr, inM_addr);
    }

    public Mat44 MulFloat(float inV) {
        long addr = internal_native_MulFloat_addr(native_address, inV);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_2 == null)
            Mat44_TEMP_GEN_2 = Mat44.native_new();
        Mat44_TEMP_GEN_2.internal_reset(addr, false);
        return Mat44_TEMP_GEN_2;
    }

    public static long internal_native_MulFloat_addr(long this_addr, float inV) {
        return jolt.math.natives.JNI_Mat44.internal_native_MulFloat_addr(this_addr, inV);
    }

    public Mat44 MulMat44(Mat44 inM) {
        long addr = internal_native_MulMat44_addr(native_address, inM.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_3 == null)
            Mat44_TEMP_GEN_3 = Mat44.native_new();
        Mat44_TEMP_GEN_3.internal_reset(addr, false);
        return Mat44_TEMP_GEN_3;
    }

    public static long internal_native_MulMat44_addr(long this_addr, long inM_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_MulMat44_addr(this_addr, inM_addr);
    }

    public Vec3 MulVec3(Vec3 inV) {
        long addr = internal_native_MulVec3_addr(native_address, inV.native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_5 == null)
            Vec3_TEMP_GEN_5 = Vec3.native_new();
        Vec3_TEMP_GEN_5.internal_reset(addr, false);
        return Vec3_TEMP_GEN_5;
    }

    public static long internal_native_MulVec3_addr(long this_addr, long inV_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_MulVec3_addr(this_addr, inV_addr);
    }

    public Vec4 MulVec4(Vec4 inV) {
        long addr = internal_native_MulVec4_addr(native_address, inV.native_address);
        if (addr == 0)
            return Vec4.NULL;
        if (Vec4_TEMP_GEN_1 == null)
            Vec4_TEMP_GEN_1 = Vec4.native_new();
        Vec4_TEMP_GEN_1.internal_reset(addr, false);
        return Vec4_TEMP_GEN_1;
    }

    public static long internal_native_MulVec4_addr(long this_addr, long inV_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_MulVec4_addr(this_addr, inV_addr);
    }

    public Mat44 AddMat44(Mat44 inM) {
        long addr = internal_native_AddMat44_addr(native_address, inM.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_4 == null)
            Mat44_TEMP_GEN_4 = Mat44.native_new();
        Mat44_TEMP_GEN_4.internal_reset(addr, false);
        return Mat44_TEMP_GEN_4;
    }

    public static long internal_native_AddMat44_addr(long this_addr, long inM_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_AddMat44_addr(this_addr, inM_addr);
    }

    public Mat44 SubMat44(Mat44 inM) {
        long addr = internal_native_SubMat44_addr(native_address, inM.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_5 == null)
            Mat44_TEMP_GEN_5 = Mat44.native_new();
        Mat44_TEMP_GEN_5.internal_reset(addr, false);
        return Mat44_TEMP_GEN_5;
    }

    public static long internal_native_SubMat44_addr(long this_addr, long inM_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_SubMat44_addr(this_addr, inM_addr);
    }

    public Vec3 Multiply3x3(Vec3 inV) {
        long addr = internal_native_Multiply3x3_addr(native_address, inV.native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_6 == null)
            Vec3_TEMP_GEN_6 = Vec3.native_new();
        Vec3_TEMP_GEN_6.internal_reset(addr, false);
        return Vec3_TEMP_GEN_6;
    }

    public static long internal_native_Multiply3x3_addr(long this_addr, long inV_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Multiply3x3_addr(this_addr, inV_addr);
    }

    public Vec3 Multiply3x3Transposed(Vec3 inV) {
        long addr = internal_native_Multiply3x3Transposed_addr(native_address, inV.native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_7 == null)
            Vec3_TEMP_GEN_7 = Vec3.native_new();
        Vec3_TEMP_GEN_7.internal_reset(addr, false);
        return Vec3_TEMP_GEN_7;
    }

    public static long internal_native_Multiply3x3Transposed_addr(long this_addr, long inV_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Multiply3x3Transposed_addr(this_addr, inV_addr);
    }

    public Mat44 Multiply3x3LeftTransposed(Mat44 inM) {
        long addr = internal_native_Multiply3x3LeftTransposed_addr(native_address, inM.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_6 == null)
            Mat44_TEMP_GEN_6 = Mat44.native_new();
        Mat44_TEMP_GEN_6.internal_reset(addr, false);
        return Mat44_TEMP_GEN_6;
    }

    public static long internal_native_Multiply3x3LeftTransposed_addr(long this_addr, long inM_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Multiply3x3LeftTransposed_addr(this_addr, inM_addr);
    }

    public Mat44 Multiply3x3RightTransposed(Mat44 inM) {
        long addr = internal_native_Multiply3x3RightTransposed_addr(native_address, inM.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_7 == null)
            Mat44_TEMP_GEN_7 = Mat44.native_new();
        Mat44_TEMP_GEN_7.internal_reset(addr, false);
        return Mat44_TEMP_GEN_7;
    }

    public static long internal_native_Multiply3x3RightTransposed_addr(long this_addr, long inM_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Multiply3x3RightTransposed_addr(this_addr, inM_addr);
    }

    public Mat44 Transposed() {
        long addr = internal_native_Transposed_addr(native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_8 == null)
            Mat44_TEMP_GEN_8 = Mat44.native_new();
        Mat44_TEMP_GEN_8.internal_reset(addr, false);
        return Mat44_TEMP_GEN_8;
    }

    public static long internal_native_Transposed_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Transposed_addr(this_addr);
    }

    public Mat44 Transposed3x3() {
        long addr = internal_native_Transposed3x3_addr(native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_9 == null)
            Mat44_TEMP_GEN_9 = Mat44.native_new();
        Mat44_TEMP_GEN_9.internal_reset(addr, false);
        return Mat44_TEMP_GEN_9;
    }

    public static long internal_native_Transposed3x3_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Transposed3x3_addr(this_addr);
    }

    public Mat44 Inversed() {
        long addr = internal_native_Inversed_addr(native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_10 == null)
            Mat44_TEMP_GEN_10 = Mat44.native_new();
        Mat44_TEMP_GEN_10.internal_reset(addr, false);
        return Mat44_TEMP_GEN_10;
    }

    public static long internal_native_Inversed_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Inversed_addr(this_addr);
    }

    public Mat44 InversedRotationTranslation() {
        long addr = internal_native_InversedRotationTranslation_addr(native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_11 == null)
            Mat44_TEMP_GEN_11 = Mat44.native_new();
        Mat44_TEMP_GEN_11.internal_reset(addr, false);
        return Mat44_TEMP_GEN_11;
    }

    public static long internal_native_InversedRotationTranslation_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_InversedRotationTranslation_addr(this_addr);
    }

    public Mat44 Adjointed3x3() {
        long addr = internal_native_Adjointed3x3_addr(native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_12 == null)
            Mat44_TEMP_GEN_12 = Mat44.native_new();
        Mat44_TEMP_GEN_12.internal_reset(addr, false);
        return Mat44_TEMP_GEN_12;
    }

    public static long internal_native_Adjointed3x3_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Adjointed3x3_addr(this_addr);
    }

    public boolean SetInversed3x3(Mat44 inM) {
        return internal_native_SetInversed3x3(native_address, inM.native_address);
    }

    public static boolean internal_native_SetInversed3x3(long this_addr, long inM_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_SetInversed3x3(this_addr, inM_addr);
    }

    public float GetDeterminant3x3() {
        return internal_native_GetDeterminant3x3(native_address);
    }

    public static float internal_native_GetDeterminant3x3(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetDeterminant3x3(this_addr);
    }

    public Mat44 Inversed3x3() {
        long addr = internal_native_Inversed3x3_addr(native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_13 == null)
            Mat44_TEMP_GEN_13 = Mat44.native_new();
        Mat44_TEMP_GEN_13.internal_reset(addr, false);
        return Mat44_TEMP_GEN_13;
    }

    public static long internal_native_Inversed3x3_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Inversed3x3_addr(this_addr);
    }

    public Mat44 GetDirectionPreservingMatrix() {
        long addr = internal_native_GetDirectionPreservingMatrix_addr(native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_14 == null)
            Mat44_TEMP_GEN_14 = Mat44.native_new();
        Mat44_TEMP_GEN_14.internal_reset(addr, false);
        return Mat44_TEMP_GEN_14;
    }

    public static long internal_native_GetDirectionPreservingMatrix_addr(long this_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetDirectionPreservingMatrix_addr(this_addr);
    }

    public Mat44 PreTranslated(Vec3 inTranslation) {
        long addr = internal_native_PreTranslated_addr(native_address, inTranslation.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_15 == null)
            Mat44_TEMP_GEN_15 = Mat44.native_new();
        Mat44_TEMP_GEN_15.internal_reset(addr, false);
        return Mat44_TEMP_GEN_15;
    }

    public static long internal_native_PreTranslated_addr(long this_addr, long inTranslation_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_PreTranslated_addr(this_addr, inTranslation_addr);
    }

    public Mat44 PostTranslated(Vec3 inTranslation) {
        long addr = internal_native_PostTranslated_addr(native_address, inTranslation.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_16 == null)
            Mat44_TEMP_GEN_16 = Mat44.native_new();
        Mat44_TEMP_GEN_16.internal_reset(addr, false);
        return Mat44_TEMP_GEN_16;
    }

    public static long internal_native_PostTranslated_addr(long this_addr, long inTranslation_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_PostTranslated_addr(this_addr, inTranslation_addr);
    }

    public Mat44 PreScaled(Vec3 inScale) {
        long addr = internal_native_PreScaled_addr(native_address, inScale.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_17 == null)
            Mat44_TEMP_GEN_17 = Mat44.native_new();
        Mat44_TEMP_GEN_17.internal_reset(addr, false);
        return Mat44_TEMP_GEN_17;
    }

    public static long internal_native_PreScaled_addr(long this_addr, long inScale_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_PreScaled_addr(this_addr, inScale_addr);
    }

    public Mat44 PostScaled(Vec3 inScale) {
        long addr = internal_native_PostScaled_addr(native_address, inScale.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_18 == null)
            Mat44_TEMP_GEN_18 = Mat44.native_new();
        Mat44_TEMP_GEN_18.internal_reset(addr, false);
        return Mat44_TEMP_GEN_18;
    }

    public static long internal_native_PostScaled_addr(long this_addr, long inScale_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_PostScaled_addr(this_addr, inScale_addr);
    }

    public Mat44 Decompose(Vec3 outScale) {
        long addr = internal_native_Decompose_addr(native_address, outScale.native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_19 == null)
            Mat44_TEMP_GEN_19 = Mat44.native_new();
        Mat44_TEMP_GEN_19.internal_reset(addr, false);
        return Mat44_TEMP_GEN_19;
    }

    public static long internal_native_Decompose_addr(long this_addr, long outScale_addr) {
        return jolt.math.natives.JNI_Mat44.internal_native_Decompose_addr(this_addr, outScale_addr);
    }

    public void SetColumn3(int inCol, Vec3 inV) {
        internal_native_SetColumn3(native_address, inCol, inV.native_address);
    }

    public static void internal_native_SetColumn3(long this_addr, int inCol, long inV_addr) {
        jolt.math.natives.JNI_Mat44.internal_native_SetColumn3(this_addr, inCol, inV_addr);
    }

    public void SetColumn4(int inCol, Vec4 inV) {
        internal_native_SetColumn4(native_address, inCol, inV.native_address);
    }

    public static void internal_native_SetColumn4(long this_addr, int inCol, long inV_addr) {
        jolt.math.natives.JNI_Mat44.internal_native_SetColumn4(this_addr, inCol, inV_addr);
    }

    public void SetAxisX(Vec3 inV) {
        internal_native_SetAxisX(native_address, inV.native_address);
    }

    public static void internal_native_SetAxisX(long this_addr, long inV_addr) {
        jolt.math.natives.JNI_Mat44.internal_native_SetAxisX(this_addr, inV_addr);
    }

    public void SetAxisY(Vec3 inV) {
        internal_native_SetAxisY(native_address, inV.native_address);
    }

    public static void internal_native_SetAxisY(long this_addr, long inV_addr) {
        jolt.math.natives.JNI_Mat44.internal_native_SetAxisY(this_addr, inV_addr);
    }

    public void SetAxisZ(Vec3 inV) {
        internal_native_SetAxisZ(native_address, inV.native_address);
    }

    public static void internal_native_SetAxisZ(long this_addr, long inV_addr) {
        jolt.math.natives.JNI_Mat44.internal_native_SetAxisZ(this_addr, inV_addr);
    }

    public void SetDiagonal3(Vec3 inV) {
        internal_native_SetDiagonal3(native_address, inV.native_address);
    }

    public static void internal_native_SetDiagonal3(long this_addr, long inV_addr) {
        jolt.math.natives.JNI_Mat44.internal_native_SetDiagonal3(this_addr, inV_addr);
    }

    public void SetDiagonal4(Vec4 inV) {
        internal_native_SetDiagonal4(native_address, inV.native_address);
    }

    public static void internal_native_SetDiagonal4(long this_addr, long inV_addr) {
        jolt.math.natives.JNI_Mat44.internal_native_SetDiagonal4(this_addr, inV_addr);
    }

    public void SetTranslation(Vec3 inV) {
        internal_native_SetTranslation(native_address, inV.native_address);
    }

    public static void internal_native_SetTranslation(long this_addr, long inV_addr) {
        jolt.math.natives.JNI_Mat44.internal_native_SetTranslation(this_addr, inV_addr);
    }

    public Vec3 GetColumn3(int inCol) {
        long addr = internal_native_GetColumn3_addr(native_address, inCol);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_8 == null)
            Vec3_TEMP_GEN_8 = Vec3.native_new();
        Vec3_TEMP_GEN_8.internal_reset(addr, false);
        return Vec3_TEMP_GEN_8;
    }

    public static long internal_native_GetColumn3_addr(long this_addr, int inCol) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetColumn3_addr(this_addr, inCol);
    }

    public Vec4 GetColumn4(int inCol) {
        long addr = internal_native_GetColumn4_addr(native_address, inCol);
        if (addr == 0)
            return Vec4.NULL;
        if (Vec4_TEMP_GEN_2 == null)
            Vec4_TEMP_GEN_2 = Vec4.native_new();
        Vec4_TEMP_GEN_2.internal_reset(addr, false);
        return Vec4_TEMP_GEN_2;
    }

    public static long internal_native_GetColumn4_addr(long this_addr, int inCol) {
        return jolt.math.natives.JNI_Mat44.internal_native_GetColumn4_addr(this_addr, inCol);
    }
}
