/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.math;

import com.github.xpenatan.jParser.api.NativeObject;

public final class UintMemRef extends NativeObject {

    static public final UintMemRef NULL = UintMemRef.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected UintMemRef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static UintMemRef native_new() {
        return new UintMemRef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.math.natives.JNI_UintMemRef.internal_native_deleteNative(this_addr);
    }
}
