/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.geometry;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.VertexList;
import jolt.math.Vec3;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class IndexedTriangleNoMaterial extends NativeObject {

    private Vec3 Vec3_TEMP_GEN_0;

    static public final IndexedTriangleNoMaterial NULL = IndexedTriangleNoMaterial.native_new();

    public IndexedTriangleNoMaterial() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public IndexedTriangleNoMaterial(int inI1, int inI2, int inI3) {
        long addr = internal_native_create_int_int_int_addr(inI1, inI2, inI3);
        internal_reset(addr, true);
    }

    public static long internal_native_create_int_int_int_addr(int inI1, int inI2, int inI3) {
        try {
            return (long) FFMHandles.internal_native_create_int_int_int_addr__III.invokeExact(inI1, inI2, inI3);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected IndexedTriangleNoMaterial(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static IndexedTriangleNoMaterial native_new() {
        return new IndexedTriangleNoMaterial((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean Equals(IndexedTriangleNoMaterial inRHS) {
        return internal_native_Equals(native_address, inRHS.native_address);
    }

    public static boolean internal_native_Equals(long this_addr, long inRHS_addr) {
        try {
            return (boolean) FFMHandles.internal_native_Equals__JJ.invokeExact(this_addr, inRHS_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsEquivalent(IndexedTriangleNoMaterial inRHS) {
        return internal_native_IsEquivalent(native_address, inRHS.native_address);
    }

    public static boolean internal_native_IsEquivalent(long this_addr, long inRHS_addr) {
        try {
            return (boolean) FFMHandles.internal_native_IsEquivalent__JJ.invokeExact(this_addr, inRHS_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsOpposite(IndexedTriangleNoMaterial inRHS) {
        return internal_native_IsOpposite(native_address, inRHS.native_address);
    }

    public static boolean internal_native_IsOpposite(long this_addr, long inRHS_addr) {
        try {
            return (boolean) FFMHandles.internal_native_IsOpposite__JJ.invokeExact(this_addr, inRHS_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsDegenerate(VertexList inVertices) {
        return internal_native_IsDegenerate(native_address, inVertices.native_address);
    }

    public static boolean internal_native_IsDegenerate(long this_addr, long inVertices_addr) {
        try {
            return (boolean) FFMHandles.internal_native_IsDegenerate__JJ.invokeExact(this_addr, inVertices_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Rotate() {
        internal_native_Rotate(native_address);
    }

    public static void internal_native_Rotate(long this_addr) {
        try {
            FFMHandles.internal_native_Rotate__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 GetCentroid(VertexList inVertices) {
        long addr = internal_native_GetCentroid_addr(native_address, inVertices.native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.native_new();
        Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetCentroid_addr(long this_addr, long inVertices_addr) {
        try {
            return (long) FFMHandles.internal_native_GetCentroid_addr__JJ.invokeExact(this_addr, inVertices_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetHash() {
        return internal_native_GetHash(native_address);
    }

    public static long internal_native_GetHash(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetHash__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int get_mIdx(int index) {
        return internal_native_get_mIdx(native_address, index);
    }

    public static int internal_native_get_mIdx(long this_addr, int index) {
        try {
            return (int) FFMHandles.internal_native_get_mIdx__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mIdx(int index, int mIdx) {
        internal_native_set_mIdx(native_address, index, mIdx);
    }

    public static void internal_native_set_mIdx(long this_addr, int index, int mIdx) {
        try {
            FFMHandles.internal_native_set_mIdx__JII.invokeExact(this_addr, index, mIdx);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_indexedtrianglenomaterial_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_int_int_int_addr__III = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_indexedtrianglenomaterial_create_int_int_int_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_indexedtrianglenomaterial_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Equals__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_indexedtrianglenomaterial_equals", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_IsEquivalent__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_indexedtrianglenomaterial_isequivalent", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_IsOpposite__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_indexedtrianglenomaterial_isopposite", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_IsDegenerate__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_indexedtrianglenomaterial_isdegenerate", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Rotate__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_indexedtrianglenomaterial_rotate", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetCentroid_addr__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_indexedtrianglenomaterial_getcentroid_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetHash__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_indexedtrianglenomaterial_gethash", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mIdx__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_indexedtrianglenomaterial_get_midx", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_set_mIdx__JII = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_indexedtrianglenomaterial_set_midx", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    }
}
