/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.geometry;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.Mat44;
import jolt.math.Vec3;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class OrientedBox extends NativeObject {

    private Mat44 Mat44_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_0;

    static public final OrientedBox NULL = OrientedBox.native_new();

    public OrientedBox() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public OrientedBox(Mat44 inOrientation, Vec3 inHalfExtents) {
        long addr = internal_native_create_Mat44_Vec3_addr(inOrientation.native_address, inHalfExtents.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_Mat44_Vec3_addr(long inOrientation_addr, long inHalfExtents_addr) {
        try {
            return (long) FFMHandles.internal_native_create_Mat44_Vec3_addr__JJ.invokeExact(inOrientation_addr, inHalfExtents_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected OrientedBox(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static OrientedBox native_new() {
        return new OrientedBox((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean OverlapsAABox(AABox inBox, float inEpsilon) {
        return internal_native_OverlapsAABox(native_address, inBox.native_address, inEpsilon);
    }

    public static boolean internal_native_OverlapsAABox(long this_addr, long inBox_addr, float inEpsilon) {
        try {
            return (boolean) FFMHandles.internal_native_OverlapsAABox__JJF.invokeExact(this_addr, inBox_addr, inEpsilon);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean OverlapsAABox(AABox inBox) {
        return internal_native_OverlapsAABox(native_address, inBox.native_address);
    }

    public static boolean internal_native_OverlapsAABox(long this_addr, long inBox_addr) {
        try {
            return (boolean) FFMHandles.internal_native_OverlapsAABox__JJ.invokeExact(this_addr, inBox_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean OverlapsOrientedBox(OrientedBox inBox, float inEpsilon) {
        return internal_native_OverlapsOrientedBox(native_address, inBox.native_address, inEpsilon);
    }

    public static boolean internal_native_OverlapsOrientedBox(long this_addr, long inBox_addr, float inEpsilon) {
        try {
            return (boolean) FFMHandles.internal_native_OverlapsOrientedBox__JJF.invokeExact(this_addr, inBox_addr, inEpsilon);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean OverlapsOrientedBox(OrientedBox inBox) {
        return internal_native_OverlapsOrientedBox(native_address, inBox.native_address);
    }

    public static boolean internal_native_OverlapsOrientedBox(long this_addr, long inBox_addr) {
        try {
            return (boolean) FFMHandles.internal_native_OverlapsOrientedBox__JJ.invokeExact(this_addr, inBox_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Mat44 get_mOrientation() {
        long addr = internal_native_get_mOrientation_addr(native_address);
        if (addr == 0)
            return Mat44.NULL;
        if (Mat44_TEMP_GEN_0 == null)
            Mat44_TEMP_GEN_0 = Mat44.native_new();
        Mat44_TEMP_GEN_0.internal_reset(addr, false);
        return Mat44_TEMP_GEN_0;
    }

    public static long internal_native_get_mOrientation_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mOrientation_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mOrientation(Mat44 mOrientation) {
        internal_native_set_mOrientation(native_address, mOrientation.native_address);
    }

    public static void internal_native_set_mOrientation(long this_addr, long mOrientation_addr) {
        try {
            FFMHandles.internal_native_set_mOrientation__JJ.invokeExact(this_addr, mOrientation_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 get_mHalfExtents() {
        long addr = internal_native_get_mHalfExtents_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.native_new();
        Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return Vec3_TEMP_GEN_0;
    }

    public static long internal_native_get_mHalfExtents_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mHalfExtents_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mHalfExtents(Vec3 mHalfExtents) {
        internal_native_set_mHalfExtents(native_address, mHalfExtents.native_address);
    }

    public static void internal_native_set_mHalfExtents(long this_addr, long mHalfExtents_addr) {
        try {
            FFMHandles.internal_native_set_mHalfExtents__JJ.invokeExact(this_addr, mHalfExtents_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_orientedbox_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_Mat44_Vec3_addr__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_orientedbox_create_mat44_vec3_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_orientedbox_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_OverlapsAABox__JJF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_orientedbox_overlapsaabox_l_l_f", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_OverlapsAABox__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_orientedbox_overlapsaabox_l_l", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_OverlapsOrientedBox__JJF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_orientedbox_overlapsorientedbox_l_l_f", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_OverlapsOrientedBox__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_orientedbox_overlapsorientedbox_l_l", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mOrientation_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_orientedbox_get_morientation_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mOrientation__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_orientedbox_set_morientation", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mHalfExtents_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_orientedbox_get_mhalfextents_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mHalfExtents__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_geometry_orientedbox_set_mhalfextents", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
