/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.constraints;

import jolt.math.Vec3;
import jolt.enums.EMotorState;
import jolt.math.Quat;
import jolt.math.Vector2;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class HingeConstraint extends TwoBodyConstraint {

    private Vec3 Vec3_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_1;

    private Vec3 Vec3_TEMP_GEN_2;

    private Vec3 Vec3_TEMP_GEN_3;

    private Vec3 Vec3_TEMP_GEN_4;

    private Vec3 Vec3_TEMP_GEN_5;

    private MotorSettings MotorSettings_TEMP_GEN_0;

    private SpringSettings SpringSettings_TEMP_GEN_0;

    private Vec3 Vec3_TEMP_GEN_6;

    private Vector2 Vector2_TEMP_GEN_0;

    static public final HingeConstraint NULL = HingeConstraint.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected HingeConstraint(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static HingeConstraint native_new() {
        return new HingeConstraint((byte) 0, (char) 0);
    }

    public Vec3 GetLocalSpacePoint1() {
        long addr = internal_native_GetLocalSpacePoint1_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_0 == null)
            Vec3_TEMP_GEN_0 = Vec3.native_new();
        Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetLocalSpacePoint1_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalSpacePoint1_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 GetLocalSpacePoint2() {
        long addr = internal_native_GetLocalSpacePoint2_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_1 == null)
            Vec3_TEMP_GEN_1 = Vec3.native_new();
        Vec3_TEMP_GEN_1.internal_reset(addr, false);
        return Vec3_TEMP_GEN_1;
    }

    public static long internal_native_GetLocalSpacePoint2_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalSpacePoint2_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 GetLocalSpaceHingeAxis1() {
        long addr = internal_native_GetLocalSpaceHingeAxis1_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_2 == null)
            Vec3_TEMP_GEN_2 = Vec3.native_new();
        Vec3_TEMP_GEN_2.internal_reset(addr, false);
        return Vec3_TEMP_GEN_2;
    }

    public static long internal_native_GetLocalSpaceHingeAxis1_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalSpaceHingeAxis1_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 GetLocalSpaceHingeAxis2() {
        long addr = internal_native_GetLocalSpaceHingeAxis2_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_3 == null)
            Vec3_TEMP_GEN_3 = Vec3.native_new();
        Vec3_TEMP_GEN_3.internal_reset(addr, false);
        return Vec3_TEMP_GEN_3;
    }

    public static long internal_native_GetLocalSpaceHingeAxis2_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalSpaceHingeAxis2_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 GetLocalSpaceNormalAxis1() {
        long addr = internal_native_GetLocalSpaceNormalAxis1_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_4 == null)
            Vec3_TEMP_GEN_4 = Vec3.native_new();
        Vec3_TEMP_GEN_4.internal_reset(addr, false);
        return Vec3_TEMP_GEN_4;
    }

    public static long internal_native_GetLocalSpaceNormalAxis1_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalSpaceNormalAxis1_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 GetLocalSpaceNormalAxis2() {
        long addr = internal_native_GetLocalSpaceNormalAxis2_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_5 == null)
            Vec3_TEMP_GEN_5 = Vec3.native_new();
        Vec3_TEMP_GEN_5.internal_reset(addr, false);
        return Vec3_TEMP_GEN_5;
    }

    public static long internal_native_GetLocalSpaceNormalAxis2_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalSpaceNormalAxis2_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetCurrentAngle() {
        return internal_native_GetCurrentAngle(native_address);
    }

    public static float internal_native_GetCurrentAngle(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetCurrentAngle__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetMaxFrictionTorque(float inFrictionTorque) {
        internal_native_SetMaxFrictionTorque(native_address, inFrictionTorque);
    }

    public static void internal_native_SetMaxFrictionTorque(long this_addr, float inFrictionTorque) {
        try {
            FFMHandles.internal_native_SetMaxFrictionTorque__JF.invokeExact(this_addr, inFrictionTorque);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetMaxFrictionTorque() {
        return internal_native_GetMaxFrictionTorque(native_address);
    }

    public static float internal_native_GetMaxFrictionTorque(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetMaxFrictionTorque__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public MotorSettings GetMotorSettings() {
        long addr = internal_native_GetMotorSettings_addr(native_address);
        if (addr == 0)
            return MotorSettings.NULL;
        if (MotorSettings_TEMP_GEN_0 == null)
            MotorSettings_TEMP_GEN_0 = MotorSettings.native_new();
        MotorSettings_TEMP_GEN_0.internal_reset(addr, false);
        return MotorSettings_TEMP_GEN_0;
    }

    public static long internal_native_GetMotorSettings_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetMotorSettings_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetMotorState(EMotorState inState) {
        internal_native_SetMotorState(native_address, inState.getValue());
    }

    public static void internal_native_SetMotorState(long this_addr, int inState) {
        try {
            FFMHandles.internal_native_SetMotorState__JI.invokeExact(this_addr, inState);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public EMotorState GetMotorState() {
        int value = internal_native_GetMotorState(native_address);
        EMotorState[] values = EMotorState.values();
        for (int i = 0; i < values.length; i++) {
            EMotorState enumVal = values[i];
            if (enumVal != EMotorState.CUSTOM && enumVal.getValue() == value)
                return enumVal;
        }
        return EMotorState.CUSTOM.setValue(value);
    }

    public static int internal_native_GetMotorState(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetMotorState__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetTargetAngularVelocity(float inAngularVelocity) {
        internal_native_SetTargetAngularVelocity(native_address, inAngularVelocity);
    }

    public static void internal_native_SetTargetAngularVelocity(long this_addr, float inAngularVelocity) {
        try {
            FFMHandles.internal_native_SetTargetAngularVelocity__JF.invokeExact(this_addr, inAngularVelocity);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetTargetAngularVelocity() {
        return internal_native_GetTargetAngularVelocity(native_address);
    }

    public static float internal_native_GetTargetAngularVelocity(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetTargetAngularVelocity__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetTargetAngle(float inAngle) {
        internal_native_SetTargetAngle(native_address, inAngle);
    }

    public static void internal_native_SetTargetAngle(long this_addr, float inAngle) {
        try {
            FFMHandles.internal_native_SetTargetAngle__JF.invokeExact(this_addr, inAngle);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetTargetAngle() {
        return internal_native_GetTargetAngle(native_address);
    }

    public static float internal_native_GetTargetAngle(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetTargetAngle__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetTargetOrientationBS(Quat inOrientation) {
        internal_native_SetTargetOrientationBS(native_address, inOrientation.native_address);
    }

    public static void internal_native_SetTargetOrientationBS(long this_addr, long inOrientation_addr) {
        try {
            FFMHandles.internal_native_SetTargetOrientationBS__JJ.invokeExact(this_addr, inOrientation_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLimits(float inLimitsMin, float inLimitsMax) {
        internal_native_SetLimits(native_address, inLimitsMin, inLimitsMax);
    }

    public static void internal_native_SetLimits(long this_addr, float inLimitsMin, float inLimitsMax) {
        try {
            FFMHandles.internal_native_SetLimits__JFF.invokeExact(this_addr, inLimitsMin, inLimitsMax);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetLimitsMin() {
        return internal_native_GetLimitsMin(native_address);
    }

    public static float internal_native_GetLimitsMin(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetLimitsMin__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetLimitsMax() {
        return internal_native_GetLimitsMax(native_address);
    }

    public static float internal_native_GetLimitsMax(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetLimitsMax__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean HasLimits() {
        return internal_native_HasLimits(native_address);
    }

    public static boolean internal_native_HasLimits(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_HasLimits__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public SpringSettings GetLimitsSpringSettings() {
        long addr = internal_native_GetLimitsSpringSettings_addr(native_address);
        if (addr == 0)
            return SpringSettings.NULL;
        if (SpringSettings_TEMP_GEN_0 == null)
            SpringSettings_TEMP_GEN_0 = SpringSettings.native_new();
        SpringSettings_TEMP_GEN_0.internal_reset(addr, false);
        return SpringSettings_TEMP_GEN_0;
    }

    public static long internal_native_GetLimitsSpringSettings_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLimitsSpringSettings_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLimitsSpringSettings(SpringSettings inLimitsSpringSettings) {
        internal_native_SetLimitsSpringSettings(native_address, inLimitsSpringSettings.native_address);
    }

    public static void internal_native_SetLimitsSpringSettings(long this_addr, long inLimitsSpringSettings_addr) {
        try {
            FFMHandles.internal_native_SetLimitsSpringSettings__JJ.invokeExact(this_addr, inLimitsSpringSettings_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vec3 GetTotalLambdaPosition() {
        long addr = internal_native_GetTotalLambdaPosition_addr(native_address);
        if (addr == 0)
            return Vec3.NULL;
        if (Vec3_TEMP_GEN_6 == null)
            Vec3_TEMP_GEN_6 = Vec3.native_new();
        Vec3_TEMP_GEN_6.internal_reset(addr, false);
        return Vec3_TEMP_GEN_6;
    }

    public static long internal_native_GetTotalLambdaPosition_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetTotalLambdaPosition_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public Vector2 GetTotalLambdaRotation() {
        long addr = internal_native_GetTotalLambdaRotation_addr(native_address);
        if (addr == 0)
            return Vector2.NULL;
        if (Vector2_TEMP_GEN_0 == null)
            Vector2_TEMP_GEN_0 = Vector2.native_new();
        Vector2_TEMP_GEN_0.internal_reset(addr, false);
        return Vector2_TEMP_GEN_0;
    }

    public static long internal_native_GetTotalLambdaRotation_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetTotalLambdaRotation_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetTotalLambdaRotationLimits() {
        return internal_native_GetTotalLambdaRotationLimits(native_address);
    }

    public static float internal_native_GetTotalLambdaRotationLimits(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetTotalLambdaRotationLimits__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetTotalLambdaMotor() {
        return internal_native_GetTotalLambdaMotor(native_address);
    }

    public static float internal_native_GetTotalLambdaMotor(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetTotalLambdaMotor__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_GetLocalSpacePoint1_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getlocalspacepoint1_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalSpacePoint2_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getlocalspacepoint2_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalSpaceHingeAxis1_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getlocalspacehingeaxis1_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalSpaceHingeAxis2_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getlocalspacehingeaxis2_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalSpaceNormalAxis1_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getlocalspacenormalaxis1_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalSpaceNormalAxis2_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getlocalspacenormalaxis2_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetCurrentAngle__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getcurrentangle", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetMaxFrictionTorque__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_setmaxfrictiontorque", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetMaxFrictionTorque__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getmaxfrictiontorque", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetMotorSettings_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getmotorsettings_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetMotorState__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_setmotorstate", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_GetMotorState__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getmotorstate", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetTargetAngularVelocity__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_settargetangularvelocity", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetTargetAngularVelocity__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_gettargetangularvelocity", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetTargetAngle__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_settargetangle", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetTargetAngle__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_gettargetangle", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetTargetOrientationBS__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_settargetorientationbs", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLimits__JFF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_setlimits", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetLimitsMin__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getlimitsmin", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLimitsMax__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getlimitsmax", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_HasLimits__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_haslimits", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLimitsSpringSettings_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_getlimitsspringsettings_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLimitsSpringSettings__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_setlimitsspringsettings", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetTotalLambdaPosition_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_gettotallambdaposition_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetTotalLambdaRotation_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_gettotallambdarotation_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetTotalLambdaRotationLimits__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_gettotallambdarotationlimits", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetTotalLambdaMotor__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_constraints_hingeconstraint_gettotallambdamotor", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));
    }
}
