/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.hair;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ArrayHairSettingsMaterial extends NativeObject {

    static public final ArrayHairSettingsMaterial NULL = ArrayHairSettingsMaterial.native_new();

    public ArrayHairSettingsMaterial() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ArrayHairSettingsMaterial(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ArrayHairSettingsMaterial native_new() {
        return new ArrayHairSettingsMaterial((byte) 0, (char) 0);
    }

    public boolean empty() {
        return false;
    }

    public int size() {
        return 0;
    }

    public HairSettingsMaterial at(int inIndex) {
        return null;
    }

    public void push_back(HairSettingsMaterial inValue) {
    }

    public void reserve(int inSize) {
    }

    public void resize(int inSize) {
    }

    public void clear() {
    }
}
