/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.hair;

import com.github.xpenatan.jParser.api.NativeObject;

public final class ArrayHairSettingsRStrand extends NativeObject {

    static public final ArrayHairSettingsRStrand NULL = ArrayHairSettingsRStrand.native_new();

    public ArrayHairSettingsRStrand() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ArrayHairSettingsRStrand(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ArrayHairSettingsRStrand native_new() {
        return new ArrayHairSettingsRStrand((byte) 0, (char) 0);
    }

    public boolean empty() {
        return false;
    }

    public int size() {
        return 0;
    }

    public HairSettingsRStrand at(int inIndex) {
        return null;
    }

    public void push_back(HairSettingsRStrand inValue) {
    }

    public void reserve(int inSize) {
    }

    public void resize(int inSize) {
    }

    public void clear() {
    }
}
