/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.hair;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.RVec3;
import jolt.math.Quat;
import jolt.compute.ComputeSystem;
import jolt.RMat44;
import jolt.compute.ComputeBuffer;
import jolt.math.Mat44;
import jolt.math.Mat44MemRef;
import jolt.physics.PhysicsSystem;
import jolt.compute.ComputeQueue;
import jolt.renderer.DebugRenderer;

public final class Hair extends NativeObject {

    static public final Hair NULL = Hair.native_new();

    public Hair(HairSettings inSettings, RVec3 inPosition, Quat inRotation, int inLayer) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected Hair(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static Hair native_new() {
        return new Hair((byte) 0, (char) 0);
    }

    public void Init(ComputeSystem inComputeSystem) {
    }

    public void SetPosition(RVec3 inPosition) {
    }

    public void SetRotation(Quat inRotation) {
    }

    public RMat44 GetWorldTransform() {
        return null;
    }

    public HairSettings GetHairSettings() {
        return null;
    }

    public void OnTeleported() {
    }

    public void SetScalpVerticesCB(ComputeBuffer inBuffer) {
    }

    public void SetScalpTrianglesCB(ComputeBuffer inBuffer) {
    }

    public void SetScalpToHead(Mat44 inMat) {
    }

    public void SetRenderPositionsCB(ComputeBuffer inBuffer) {
    }

    public void Update(float inDeltaTime, Mat44 inJointToHair, Mat44MemRef inJointMatrices, PhysicsSystem inSystem, HairShaders inShaders, ComputeSystem inComputeSystem, ComputeQueue inComputeQueue) {
    }

    public ComputeBuffer GetScalpVerticesCB() {
        return null;
    }

    public ComputeBuffer GetScalpTrianglesCB() {
        return null;
    }

    public ComputeBuffer GetPositionsCB() {
        return null;
    }

    public ComputeBuffer GetVelocitiesCB() {
        return null;
    }

    public ComputeBuffer GetVelocityAndDensityCB() {
        return null;
    }

    public ComputeBuffer GetRenderPositionsCB() {
        return null;
    }

    public void ReadBackGPUState(ComputeQueue inComputeQueue) {
    }

    public void LockReadBackBuffers() {
    }

    public void UnlockReadBackBuffers() {
    }

    public void Draw(HairDrawSettings inSettings, DebugRenderer inRenderer) {
    }

    private HairRenderPositionsToFloat3 internalRenderPositionsConverter;

    void internal_retainRenderPositionsConverter(HairRenderPositionsToFloat3 value) {
        internalRenderPositionsConverter = value;
    }
}
