/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.hair;

import com.github.xpenatan.jParser.api.NativeObject;
import jolt.math.Float3;

public final class HairSettingsRVertex extends NativeObject {

    static public final HairSettingsRVertex NULL = HairSettingsRVertex.native_new();

    public HairSettingsRVertex() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected HairSettingsRVertex(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static HairSettingsRVertex native_new() {
        return new HairSettingsRVertex((byte) 0, (char) 0);
    }

    public Float3 get_mPosition() {
        return null;
    }

    public void set_mPosition(Float3 mPosition) {
    }

    public HairSettingsSVertexInfluence get_mInfluences(int index) {
        return null;
    }

    public void set_mInfluences(int index, HairSettingsSVertexInfluence mInfluences) {
    }
}
