/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.compute;

import com.github.xpenatan.jParser.api.NativeEnum;

public enum ComputeBuffer_EMode implements NativeEnum<ComputeBuffer_EMode> {

    CUSTOM(0), Read(ComputeBuffer_EMode_Read_NATIVE()), Write(ComputeBuffer_EMode_Write_NATIVE());

    private int value;

    private ComputeBuffer_EMode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public ComputeBuffer_EMode setValue(int value) {
        if (this != CUSTOM) {
            throw new RuntimeException("Cannot change none CUSTOM value");
        }
        this.value = value;
        return this;
    }

    public ComputeBuffer_EMode getCustom() {
        return CUSTOM;
    }

    private static native int ComputeBuffer_EMode_Read_NATIVE();

    private static native int ComputeBuffer_EMode_Write_NATIVE();
}
