/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.compute;

import com.github.xpenatan.jParser.api.NativeObject;
import com.github.xpenatan.jparser.runtime.helper.NativeString;

public final class ComputeBufferResult extends NativeObject {

    static public final ComputeBufferResult NULL = ComputeBufferResult.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected ComputeBufferResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static ComputeBufferResult native_new() {
        return new ComputeBufferResult((byte) 0, (char) 0);
    }

    public boolean IsValid() {
        return false;
    }

    public boolean HasError() {
        return false;
    }

    public NativeString GetError() {
        return null;
    }

    public ComputeBuffer Get() {
        return null;
    }

    public void Clear() {
    }
}
