/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.raddoll;

import jolt.physics.body.BodyCreationSettings;
import jolt.math.TwoBodyConstraintSettings;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class RagdollPart extends BodyCreationSettings {

    private TwoBodyConstraintSettings TwoBodyConstraintSettings_TEMP_GEN_0;

    static public final RagdollPart NULL = RagdollPart.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected RagdollPart(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static RagdollPart native_new() {
        return new RagdollPart((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public TwoBodyConstraintSettings get_mToParent() {
        long addr = internal_native_get_mToParent_addr(native_address);
        if (addr == 0)
            return TwoBodyConstraintSettings.NULL;
        if (TwoBodyConstraintSettings_TEMP_GEN_0 == null)
            TwoBodyConstraintSettings_TEMP_GEN_0 = TwoBodyConstraintSettings.native_new();
        TwoBodyConstraintSettings_TEMP_GEN_0.internal_reset(addr, false);
        return TwoBodyConstraintSettings_TEMP_GEN_0;
    }

    public static long internal_native_get_mToParent_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_get_mToParent_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void set_mToParent(TwoBodyConstraintSettings mToParent) {
        internal_native_set_mToParent(native_address, mToParent.native_address);
    }

    public static void internal_native_set_mToParent(long this_addr, long mToParent_addr) {
        try {
            FFMHandles.internal_native_set_mToParent__JJ.invokeExact(this_addr, mToParent_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_raddoll_ragdollpart_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_get_mToParent_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_raddoll_ragdollpart_get_mtoparent_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_set_mToParent__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("jolt_physics_raddoll_ragdollpart_set_mtoparent", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
