/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.skeleton;

import com.github.xpenatan.jParser.api.NativeObject;

public final class SkeletalAnimation extends NativeObject {

    private ArraySkeletonAnimatedJoint ArraySkeletonAnimatedJoint_TEMP_GEN_0;

    static public final SkeletalAnimation NULL = SkeletalAnimation.native_new();

    public SkeletalAnimation() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return jolt.skeleton.natives.JNI_SkeletalAnimation.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected SkeletalAnimation(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static SkeletalAnimation native_new() {
        return new SkeletalAnimation((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.skeleton.natives.JNI_SkeletalAnimation.internal_native_deleteNative(this_addr);
    }

    public float GetDuration() {
        return internal_native_GetDuration(native_address);
    }

    public static float internal_native_GetDuration(long this_addr) {
        return jolt.skeleton.natives.JNI_SkeletalAnimation.internal_native_GetDuration(this_addr);
    }

    public void ScaleJoints(float inScale) {
        internal_native_ScaleJoints(native_address, inScale);
    }

    public static void internal_native_ScaleJoints(long this_addr, float inScale) {
        jolt.skeleton.natives.JNI_SkeletalAnimation.internal_native_ScaleJoints(this_addr, inScale);
    }

    public void Sample(float inTime, SkeletonPose ioPose) {
        internal_native_Sample(native_address, inTime, ioPose.native_address);
    }

    public static void internal_native_Sample(long this_addr, float inTime, long ioPose_addr) {
        jolt.skeleton.natives.JNI_SkeletalAnimation.internal_native_Sample(this_addr, inTime, ioPose_addr);
    }

    public ArraySkeletonAnimatedJoint GetAnimatedJoints() {
        long addr = internal_native_GetAnimatedJoints_addr(native_address);
        if (addr == 0)
            return ArraySkeletonAnimatedJoint.NULL;
        if (ArraySkeletonAnimatedJoint_TEMP_GEN_0 == null)
            ArraySkeletonAnimatedJoint_TEMP_GEN_0 = ArraySkeletonAnimatedJoint.native_new();
        ArraySkeletonAnimatedJoint_TEMP_GEN_0.internal_reset(addr, false);
        return ArraySkeletonAnimatedJoint_TEMP_GEN_0;
    }

    public static long internal_native_GetAnimatedJoints_addr(long this_addr) {
        return jolt.skeleton.natives.JNI_SkeletalAnimation.internal_native_GetAnimatedJoints_addr(this_addr);
    }

    public boolean IsLooping() {
        return internal_native_IsLooping(native_address);
    }

    public static boolean internal_native_IsLooping(long this_addr) {
        return jolt.skeleton.natives.JNI_SkeletalAnimation.internal_native_IsLooping(this_addr);
    }

    public void SetIsLooping(boolean inIsLooping) {
        internal_native_SetIsLooping(native_address, inIsLooping);
    }

    public static void internal_native_SetIsLooping(long this_addr, boolean inIsLooping) {
        jolt.skeleton.natives.JNI_SkeletalAnimation.internal_native_SetIsLooping(this_addr, inIsLooping);
    }
}
