/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics;

public final class StateRecorderImpl extends StateRecorder {

    static public final StateRecorderImpl NULL = StateRecorderImpl.native_new();

    public StateRecorderImpl() {
        super((byte) 1, (char) 1);
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.natives.JNI_StateRecorderImpl.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected StateRecorderImpl(byte b, char c) {
        super((byte) 1, (char) 1);
    }

    /**
     * @return An empty instance without a native address
     */
    public static StateRecorderImpl native_new() {
        return new StateRecorderImpl((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.natives.JNI_StateRecorderImpl.internal_native_deleteNative(this_addr);
    }

    public void Clear() {
        internal_native_Clear(native_address);
    }

    public static void internal_native_Clear(long this_addr) {
        jolt.physics.natives.JNI_StateRecorderImpl.internal_native_Clear(this_addr);
    }

    public void Rewind() {
        internal_native_Rewind(native_address);
    }

    public static void internal_native_Rewind(long this_addr) {
        jolt.physics.natives.JNI_StateRecorderImpl.internal_native_Rewind(this_addr);
    }

    public boolean IsEqual(StateRecorderImpl inReference) {
        return internal_native_IsEqual(native_address, inReference.native_address);
    }

    public static boolean internal_native_IsEqual(long this_addr, long inReference_addr) {
        return jolt.physics.natives.JNI_StateRecorderImpl.internal_native_IsEqual(this_addr, inReference_addr);
    }
}
