/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.physics.hair;

import com.github.xpenatan.jParser.api.NativeObject;

public final class HairSettingsSkinWeight extends NativeObject {

    static public final HairSettingsSkinWeight NULL = HairSettingsSkinWeight.native_new();

    public HairSettingsSkinWeight() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return jolt.physics.hair.natives.JNI_HairSettingsSkinWeight.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected HairSettingsSkinWeight(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static HairSettingsSkinWeight native_new() {
        return new HairSettingsSkinWeight((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        jolt.physics.hair.natives.JNI_HairSettingsSkinWeight.internal_native_deleteNative(this_addr);
    }

    public int get_mJointIdx() {
        return internal_native_get_mJointIdx(native_address);
    }

    public static int internal_native_get_mJointIdx(long this_addr) {
        return jolt.physics.hair.natives.JNI_HairSettingsSkinWeight.internal_native_get_mJointIdx(this_addr);
    }

    public void set_mJointIdx(int mJointIdx) {
        internal_native_set_mJointIdx(native_address, mJointIdx);
    }

    public static void internal_native_set_mJointIdx(long this_addr, int mJointIdx) {
        jolt.physics.hair.natives.JNI_HairSettingsSkinWeight.internal_native_set_mJointIdx(this_addr, mJointIdx);
    }

    public float get_mWeight() {
        return internal_native_get_mWeight(native_address);
    }

    public static float internal_native_get_mWeight(long this_addr) {
        return jolt.physics.hair.natives.JNI_HairSettingsSkinWeight.internal_native_get_mWeight(this_addr);
    }

    public void set_mWeight(float mWeight) {
        internal_native_set_mWeight(native_address, mWeight);
    }

    public static void internal_native_set_mWeight(long this_addr, float mWeight) {
        jolt.physics.hair.natives.JNI_HairSettingsSkinWeight.internal_native_set_mWeight(this_addr, mWeight);
    }
}
