/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package jolt.math;

import com.github.xpenatan.jParser.api.NativeObject;

public final class VertexList extends NativeObject {

    static public final VertexList NULL = VertexList.native_new();

    public VertexList() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected VertexList(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static VertexList native_new() {
        return new VertexList((byte) 0, (char) 0);
    }

    public boolean empty() {
        return false;
    }

    public int size() {
        return 0;
    }

    public Float3 at(int inIndex) {
        return null;
    }

    public void push_back(Float3 inVertex) {
    }

    public void reserve(int inSize) {
    }

    public void resize(int inSize) {
    }

    public void clear() {
    }
}
